### DISCUSSION TITLE
How to add a button starting « music assistant »

### DISCUSSION THREAD

**Discussion by MarcMTLDK** [music-assistant/support#1004] [Q&A] [answered]
Hej guy's

I've been looking around but I couldn't find anything related to my topic. 

Basically, I'd like to be able to add a button in my GUI to initiate music assistant instead of having to navigate to the side panel. 

BTW, I LOVE IT... it's very nice to have this, instead of the previous MUSIC application.

Thank you ..

**Comment by gieljnssns** [comment, marked as answer]
Do you mean like this?

<img width="389" alt="Scherm­afbeelding 2022-11-26 om 01 02 00" src="https://user-images.githubusercontent.com/17234951/204064236-27f5eb98-ce2f-43e8-8c6f-5d268bc4e7c0.png">


Add a new card to your dashboard
```
show_name: false
show_icon: true
type: button
tap_action:
  action: navigate
  navigation_path: /music-assistant
icon: mdi:play-circle
```
