### DISCUSSION TITLE
Formatting URI with Artist and Album Name

### DISCUSSION THREAD

**Discussion by cornerkilling** [music-assistant/support#1070] [Q&A]
Hi, I am using a sensor state to pass through the album that I want to play from Youtube music. I am only able to use the album name though to start playing on Youtube music. Is there a way to format the URI to search for the artist and album name? I would like to avoid playing the wrong album because a different artist has an album by the same name. Here is my current automation yaml.

```
service: mass.queue_command
data:
  command: play_media
  uri: "{{ states('sensor.albumstoday') }}"
  enqueue_mode: play
target:
  entity_id: media_player.kitchen_speaker_2
```
