### DISCUSSION TITLE
[MA v2 Beta] Automaton / Media Browser support?

### DISCUSSION THREAD

**Discussion by raymonvdm** [music-assistant/support#1154] [Feature requests and ideas]
Last week i changed from Ha Core to Ha OS and after that i found out Music Assistant is no longer supported :-) I have installed the V2 add on (b9 at this moment) but i`m not yet able to play music started by an automation.

Am i doing something wrong or is V2 not yet supporting Media Browser (selecting gives me a mediabrowser error)

```
alias: "[Woonkamer_Shelly_i4] B2 double push"
description: ""
trigger:
  - platform: device
    device_id: 8685ea3f66c47b5b08d1102b61ccb2ab
    domain: shelly
    type: double_push
    subtype: button2
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.woonkamerspelers
  - service: media_player.play_media
    data:
      media_content_id: 4RUApIb1KbM7jwViiJ4RvZ
      media_content_type: playlist
    target:
      entity_id: media_player.woonkamerspelers
  - service: media_player.play_media
    target:
      entity_id: media_player.woonkamerspelers
    data:
      media_content_id: 4RUApIb1KbM7jwViiJ4RvZ
      media_content_type: playlist
    metadata: {}
mode: single
```
![Screenshot from 2023-03-19 22-33-16](https://user-images.githubusercontent.com/5622018/226211531-4851f65e-cc21-4cf5-a85a-94e7b2acec7f.png)
