### DISCUSSION TITLE
HEOS as Player Provider

### DISCUSSION THREAD

**Discussion by bollewolle** [music-assistant/support#1167] [Feature requests and ideas]
This is a feature request to add the HEOS platform as a Player Provider.

The [Home Assistant HEOS integration](https://github.com/home-assistant/core/tree/dev/homeassistant/components/heos) itself is using following library: pyheos ([Github](https://github.com/andrewsayre/pyheos) & [PyPi](https://pypi.org/project/pyheos/)). Last update is from August 2022 on Github but November 2020 on PyPi. 

There's other repo's as well, heospy for example ([Github](https://pypi.org/project/heospy/) & [PyPi](https://pypi.org/project/heospy/)). Both are last updated in 2022. Seems like it has a different approach though as it look more like a wrapper to use the CLI commands to control a HEOS device. So perhaps not usable.

In general not too many libraries to be honest (or at least no Python libraries). Hope it's possible to add to MA though, because it's one of the few platforms that also supports HiRes audio up to 24bits 192kHz.

Thanks in advance!

**Comment by MrHollowX** [comment]
Yes please. Id like to use my Denon AVR to stream music from Music Assistant

**Comment by bollewolle** [comment]
For those interested, there is now a poll to vote on which player support should be added: https://github.com/orgs/music-assistant/discussions/1200. Feel free to vote foe Heos :)

**Reply by MrHollowX** [reply]
Done TY :D

**Comment by OzGav** [comment]
HEOS is the highest voted player provider in the poll. Now that HA players are exposed to MA there is interest to understand if this is a satisfactory solution or if a dedicated player is still desired.

**Reply by bollewolle** [reply]
I'd say no if I wouldn't be having this issue: https://github.com/music-assistant/hass-music-assistant/issues/1939. But perhaps someone else with a Heos device should confirm that bug/behaviour that I'm seeing there to be sure it's not an isolated issue.

Otherwise I see no need to have 2 code bases having the same kind of logic in them (and having to maintain them). But I guess that can be said for most of the existing player providers then as well?

**Reply by GizmoGoody** [reply]
Here's another couple of issues I posted re: HEOS Players exposed via HA.

https://github.com/orgs/music-assistant/discussions/2602

**Reply by quizzical86** [reply]
@OzGav another great advantage of having a dedicated player, is that with a dedicated player it would probably be possible to select which room(s) to play the music on, in a for HEOS enabled receivers that support multiroom (e.g. a 7.1 receiver that is powering a 5.1 setup in de living room and stereo speakers in the kitchen).
Also for me last time I tested the HA Players, when I tried to get Music Assistant to play a playlist, it would take a long time to start playing (e.g. 30 seconds) and also the song playing would be a different song in the playlist than the one Music Assistant thinks is playing.

**Reply by yoavbrog** [reply]
@quizzical86 @OzGav
I'm just getting started with HA and MA, but seems my issue is relevant here. Hopefully you can share some advice..
I have 2 Denon x2800 receivers at my house, each one has 2 zones, and I want to be able to play music to each zone separately, through MA.
In HA I was able to create a separate media player entity for each zone, so I have a total of 4. However, I wasn't able to get the 4 zones as separate players in MA. Initially I tried using Airplay and DLNA as players, but those just get the whole receivers, so just 2 players in total. And when trying to use the Home Assistant player, it won't fetch anything from my receivers (when using the HA [Denon AVR integration](https://www.home-assistant.io/integrations/denonavr)) - I assume it may not support the `play_media` command as required. And if I use the [Heos integration](https://www.home-assistant.io/integrations/heos/) at HA , then in MA, when using Home Assistant player, it does fetch the receivers, but like with Airplay, only 2 players in total.
Hope the scenario is clear.. thanks in advance for your help!

**Reply by OzGav** [reply]
Please see here for an explanation https://music-assistant.io/faq/troubleshooting/#the-second-zone-of-my-amplifier-is-not-seen-by-ma-or-ma-wont-turn-on-my-amplifier

**Reply by yoavbrog** [reply]
Thanks for the quick reply. 
So if I understood correctly MA will never recognize reveiver zones when using Airplay/DLNA... is there any workaround for this? Can I somehow control to which receiver zone MA will play?

**Reply by quizzical86** [reply]
The below applies when using home assistant. I assume it should work as well when using music assistant but I haven't tested it so far, as for me, I can never get music assistant to work well enough with the Denon/Heos ecosystem. So I'm waiting until at some stage maybe Heos is supported formally as a player provider in music assistant (it's the NR 1 requested player provider).


n home assistant you have two integrations, HEOS and Denon.
I use the HEOS integration to play music in home assistant, but I use the Denon integration to select the zone on which to play the music.
If you just start playing music straight away using the HEOS integration, then the music will start playing on the main zone. But it you first turn on the other zone (and possibly select the right input, but probably not needed), and then start playing music using HEOS, then the other zone will play the music.

**Reply by OzGav** [reply]
> Can I somehow control to which receiver zone MA will play?

I have played with this to change to my second zone. Basically, the script turns on the HA player entity, sets the source to AirPlay, waits until everything is playing then turns off the main zone 

```
script:
  play_in_alfresco:
    mode: queued
    alias: "Send Music to Alfresco"
    sequence:
      - action: media_player.turn_on
        target:
          entity_id: media_player.yamaha_receiver_alfresco
      - action: media_player.select_source
        target:
          entity_id: media_player.yamaha_receiver_alfresco
        data:
          source: AirPlay
      - wait_template: "{{ is_state('media_player.yamaha_receiver_alfresco', 'playing') }}"
        timeout: 10
      - repeat:
          sequence:
            # Run command that for some reason doesn't always work
            - action: media_player.turn_off
              target:
                entity_id: media_player.yamaha_receiver_rumpus
            # Give it time to complete
            - delay:
                milliseconds: 500
          until:
            # Did it work?
            - condition: state
              entity_id: media_player.yamaha_receiver_rumpus
              state: "off"
```

**Reply by yoavbrog** [reply]
Thanks @OzGav, I was able to get the script to work!
How do you tie this together with MA though? Do you have some automation in place that picks up when you start playing from MA?
Ideally I'd like to just be able to choose from MA directly the zone that I want to play to. Perhaps there's a way to set up some sort of "virtual player" per each zone that would show up in MA?

**Reply by OzGav** [reply]
No I just have a button in HA. You could also create a custom voice intent.

**Reply by yoavbrog** [reply]
Voice activation is indeed the plan.
You've got my +1 for adding HEOS as a player provider if it enables proper multi zone support :)
Many thanks for your help here and for maintaining this project!

**Reply by quizzical86** [reply]
@yoavbrog you need to put that +1 here https://github.com/orgs/music-assistant/discussions/1200 😉

**Comment by JDAbbeyiii** [comment]
I'd love to see this myself. The Denon Home devices have Heos built in and I have a Heos Amp on my desk I'd love to control through Music Assistant.

**Reply by OzGav** [reply]
We are hoping a dev comes along that has one of these. We see the votes but can't bring it to fruition...

**Reply by quizzical86** [reply]
That's too bad, but I appreciate the honest answer!  Hopefully there will be a dedicated HEOS integration eventually.

**Reply by Webbeh** [reply]
@OzGav would it help if I gave you guys access to two of my devices remotely?

**Reply by OzGav** [reply]
Thanks for the offer. Unfortunately it is manpower that is needed. We had some people make a start but they are now busy with other things in life. Hopefully some more progress will be made soon.

**Reply by Webbeh** [reply]
Open offer!

**Reply by MrHollowX** [reply]
I'd like to take a look at this, is there a small guide or where can i start looking into implementing a plugin for MA ?

**Reply by OzGav** [reply]
Come and look at what has been done so far here https://discord.com/channels/753947050995089438/1341933555957104640

**Reply by kongsted** [reply]
> Come and look at what has been done so far here https://discord.com/channels/753947050995089438/1341933555957104640

I'm trying to open the Discord link, but getting an empty page? :)

**Reply by OzGav** [reply]
Sorry those links expire and for that reason I’m not going to keep posting them. Just go to discord and search.There is also a link here https://www.music-assistant.io/support/

**Reply by ccoenen** [reply]
Discord really is not a great place for an open source community. Linking to a message or a relevant thread worked just fine 30 years ago in the worst PHP forums. Somehow, Discord just forgot that links are useful, I guess.

**Reply by bluearcher-bc** [reply]
it really is a shame how discord has obfuscated so many highly specialized and niche communities... knowledge that is know unsearchable on the general internet

**Comment by zolakt** [comment]
What is the best way to integrate a Denon AVR right now? Through the HA speaker provider?

I guess the only alternative is UPnP/DLNA, if it works. Although for me that provider is useless since all my avrs/speakers are on a different subnet from HA/MA. It only relies on auto discovery and doesn't pick up devices from other subnets. Would it al least be possible to add manual ip entries to UPnP/DLNA?

**Reply by OzGav** [reply]
Sorry we dont support running MA across subnets

**Reply by quizzical86** [reply]
@zolakt I never got it to work smoothly, so for the moment I'm just using the Spotifyplus integration in Home Assistant which works great with the Denon AVR. I'm monitoring Music Assistant though in case there might ever be a Denon/Heros integration. Fill understanding though that there are other priorities for Music Assistant to focus on.

**Reply by OzGav** [reply]
There have been a few nibbles at creating a provider but nothing substantial. Most recent comments on Discord were about using AirPlay which worked well.

**Comment by smoltron** [comment]
I compared HA HEOS and MA DLNA in my Denon x4800h receiver. DLNA sounds much better and I believe the HA HEOS implementation is not optimal for sound quality. The problem with MA DLNA is that it really works only in queue flow mode and in that mode Denon does not receive any information from the stream. In non-flow mode, tracks are skipped and playing is not reliable. A proper HEOS implementation to Music Assistant could make life easier.

**Reply by marcelveldt** [reply]
Why not just live with the flow mode? I guess having good sound is more important than displaying a title on some tiny display?

**Comment by E5tian** [comment]
An implementation of the HEOS specification in Music Assistant would be very useful in order to use the multiroom functions. I found the attached Heos CLI specification from Denon, so maybe someone feels like looking into it :)

[HEOS_CLI_ProtocolSpecification-Version-1.17.pdf](https://github.com/user-attachments/files/23955921/HEOS_CLI_ProtocolSpecification-Version-1.17.pdf)

**Comment by dmutsaers** [comment]
Another vote for HEOS support. 😉

**Reply by NinjArd** [reply]
And here's another vote ✓

**Comment by megapearl** [comment]
Here another vote,

Currently using Home Assistant to set ZONE2 and/or ZONE3 to source 'HEOS Music' first and let Music Assistant grab the playlist from Apple Music/Spotify and cast it to the AirPlay 2 Player of a Denon Amplifier, kind of works, but as soon as I set the source it start playing the last music I streamed before from any service, I can't turn off that 'feature' so must stop the generic HEOS Player first before using the Music Assistant call.

```
    # ============================================================
    # ACTION: PLAY
    # ============================================================
    - if:
        - condition: template
          value_template: "{{ _resolved_action == 'play' }}"
      then:
        - alias: "Set all zones to HEOS Music"
          service: media_player.select_source
          target:
            entity_id: "{{ _zones }}"
          data:
            source: "HEOS Music"

        - delay:
            seconds: 5

        - if:
            - condition: template
              value_template: "{{ not _ma_playing }}"
          then:
            - service: music_assistant.play_media
              target:
                entity_id: "{{ _ma_target }}"
              data:
                media_id: "{{ _playlist }}"
                enqueue: replace

            - delay:
                seconds: 2

        - service: media_player.volume_set
          target:
            entity_id: "{{ _zones }}"
          data:
            volume_level: "{{ _volume }}"

        - service: script.notify_people
          data:
            people: "user1,user2"
            message: |
              {% if _ma_playing %}
              🔗 <b>Zone Added</b>
              📍 {{ _zone_display }}
              🎵 {{ _playlist_name }}
              🔊 {{ _volume_pct }}%
              👤 {{ _person }}
              {% else %}
              ▶️ <b>Music Started</b>
              📍 {{ _zone_display }}
              🎵 {{ _playlist_name }}
              🔊 {{ _volume_pct }}%
              👤 {{ _person }}
              {% endif %}

        - stop: "Play completed"
```
