### DISCUSSION TITLE
possibility to save current queue as playlist

### DISCUSSION THREAD

**Discussion by compujunk** [music-assistant/support#1240] [Feature requests and ideas]
is it possible that there will be a possibility to save the current queue as a playlist

**Comment by OzGav** [comment]
I’d say theoretically but at this stage the  focus is on squashing the bugs in the current beta and getting the HA integration going. See whether you get any traction for this though as we will keep an eye on the popular requests

**Comment by Subspace99** [comment]
I'm here looking for the same thing, or for MASS to be able to play directly from a folder.
I just wanna give a heads up to the above request and thank you all for your work!

**Reply by OzGav** [reply]
Play from a folder is available in MA 2.4

**Comment by OzGav** [comment]
You could do this by first pulling in the queue using this API call (available in MA 2.4):

```yaml
rest_command:
  ma_get_full_queue:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
      authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR......I"
    payload: >
      {
        "message_id": "1",
        "command": "player_queues/items",
        "args": {
          "queue_id": "b8:27:eb:8a:b8:8e",
          "limit": 500,
          "offset": 0
        }
      }
    content_type:  'application/json; charset=utf-8'
```

You would store the returned data in a response variable and then you could use the following template to extract all of the URIs

```yaml
{% set uris = action_response.content | map(attribute='media_item.uri') | map('string') | join('", "') %}
[ "{{ uris }}" ]
```

Once you have the URIs you could store them in an input_text and then use that in the following API call to add to a playlist. The `db_playlist_id` you will need to get by calling `music_assistant.get_library` with the `media_type` set to playlist and noting the number at the end of the URI for the playlist you want to use.

```yaml
  ma_add_playlist_tracks:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
      authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR......I"
    payload: >
      {
        "message_id": "1",
        "command": "music/playlists/add_playlist_tracks",
        "args": {
          "db_playlist_id": "26",
          "uris": input_text.stored_uri_list
        }
      }
    content_type:  'application/json; charset=utf-8'
```
