### DISCUSSION TITLE
Resume queue requested but queue is empty

### DISCUSSION THREAD

**Discussion by ajurna** [music-assistant/support#1307] [Q&A] [answered]
when trying to play an item from a service. i get the error Resume queue requested but queue {queue id} is empty.
i can play items from the music assistant interface but i cant seem to script it.

```
service: mass.queue_command
data:
  repeat_mode: one
  command: play
  uri: >-
    url://track/http://local_ip:8123/media/local/songs/song_file_name.mp3
  player_id: media_player.office_speaker
```
