### DISCUSSION TITLE
automation problem?

### DISCUSSION THREAD

**Discussion by userMak** [music-assistant/support#1308] [Feature requests and ideas]
Hi
after the .35 update the following automation stopped working (it was working fine until then)

I am not sure that this is MA problem but I **think** it is.
Although in the developer states everything seems fine the triggers are not working.
Can you say/see what is wrong?

`- id: Mute Player
  alias: Mute Player
  trigger:
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: idle
      to: offhook

    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      to: ringing

    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: offhook
      to: idle
      
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: ringing
      to: idle
  
  condition: 
      - condition: state
        entity_id: sensor.makis_home
        state: 'home'

  action:
      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'playing'
          sequence:
            - service: media_player.media_pause
              entity_id: media_player.squeezelite_382fd0

      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'paused'
          sequence:
            - service: media_player.media_play
              entity_id: media_player.squeezelite_382fd0

      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'idle'
          sequence:
            - service: media_player.media_play
              entity_id: media_player.squeezelite_382fd0

these are the logs if needed
`2023-06-12 11:44:27 INFO  music_assistant  -- Starting Music Assistant Server (418297b549534dfc87fa6f7be033d17d) - autodetected IP-address: 192.168.1.15
2023-06-12 11:44:48 INFO  music_assistant.web  -- Starting webserver on port 8095
2023-06-12 11:44:55 INFO  music_assistant.streams  -- Started stream controller (using ffmpeg version 4.3.6 with libsoxr support)
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded player provider SONOS
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded plugin provider Websocket API
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded metadata provider fanart.tv Metadata provider
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded music provider URL
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded player provider UPnP/DLNA Player provider
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded metadata provider MusicBrainz Metadata provider
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded metadata provider TheAudioDB Metadata provider
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded music provider Tune-In Radio
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded music provider Filesystem (local disk)
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded player provider Chromecast
2023-06-12 11:44:56 INFO  music_assistant.providers.slimproto  -- Started SLIMProto server on port 3483
2023-06-12 11:44:56 INFO  music_assistant.providers.slimproto.cli  -- Registering jsonrpc endpoints on the webserver
2023-06-12 11:44:56 INFO  music_assistant.providers.slimproto.cli  -- Starting (telnet) CLI on port 9090
2023-06-12 11:44:56 INFO  music_assistant  -- Loaded player provider Slimproto
authorized
2023-06-12 11:44:57 INFO  music_assistant  -- Loaded player provider Airplay
2023-06-12 11:44:57 INFO  music_assistant.players  -- Player registered: de2f1686-a113-1ff3-fe41-4d9e9c628580/Living Room speaker
2023-06-12 11:44:57 INFO  music_assistant.players  -- Player registered: 1f2020f3-5c2e-36d3-a4d7-15ed8eeac949/Chromecast Audio
2023-06-12 11:44:57 INFO  music_assistant.providers.spotify  -- Successfully logged in to Spotify as 11131773761
2023-06-12 11:44:57 INFO  music_assistant  -- Loaded music provider Spotify
2023-06-12 11:44:58 WARNING asyncio  -- Executing <Task finished name='Task-2' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> result=None> took 0.809 seconds
2023-06-12 11:44:58 INFO  music_assistant.players  -- Player registered: 08bff3b9-399f-4718-d3bc-85e2abb406bb/LG TV
2023-06-12 11:44:58 INFO  music_assistant.providers.slimproto.cli  -- Client connected on Telnet CLI
2023-06-12 11:44:58 INFO  music_assistant.players  -- Player registered: 94:b5:55:38:2f:d0/unknown device: 94:b5:55:38:2f:d0
2023-06-12 11:44:58 WARNING asyncio  -- Executing <Task finished name='Task-148' coro=<PlayerQueuesController.on_player_register() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py:497> result=None created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:284> took 0.171 seconds
2023-06-12 11:45:13 INFO  music_assistant.streams  -- Start Queue Flow stream for Queue squeezelite-382fd0
2023-06-12 11:45:23 WARNING asyncio  -- Executing <Task pending name='Task-280' coro=<MetaDataController.start_scan.<locals>.scan_artist_metadata() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py:89> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:291] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:282> took 0.103 seconds
2023-06-12 11:45:27 ERROR asyncio  -- Task exception was never retrieved
future: <Task finished name='Task-126' coro=<MusicController._start_provider_sync.<locals>.run_sync() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py:540> exception=MediaNotFoundError('Album not found in database: 18') created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:284>
source_traceback: Object created at (most recent call last):
  File "/usr/local/bin/mass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/music_assistant/__main__.py", line 108, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 273, in run
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 433, in load_provider
    await self.load_provider(prov_conf)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 383, in load_provider
    await self.music.start_sync(providers=[provider.instance_id])
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 98, in start_sync
    self._start_provider_sync(provider.instance_id, media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 547, in _start_provider_sync
    task = self.mass.create_task(run_sync())
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/server.py", line 284, in create_task
    task = self.loop.create_task(target)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/music.py", line 544, in run_sync
    await provider.sync_library(media_types)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/models/music_provider.py", line 425, in sync_library
    await controller.set_db_library(db_id, False)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 415, in set_db_library
    db_item = await self.get_db_item(db_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/base.py", line 322, in get_db_item
    raise MediaNotFoundError(f"Album not found in database: {db_id}")
music_assistant.common.models.errors.MediaNotFoundError: Album not found in database: 18
2023-06-12 11:45:28 WARNING asyncio  -- Executing <Task pending name='Task-309' coro=<MetaDataController.start_scan.<locals>.scan_artist_metadata() running at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py:89> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.11/asyncio/base_events.py:427> cb=[MusicAssistant.create_task.<locals>.task_done_callback() at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:291] created at /usr/local/lib/python3.11/site-packages/music_assistant/server/server.py:282> took 0.105 seconds
authorized
2023-06-12 12:36:33 INFO  music_assistant.providers.spotify  -- Successfully logged in to Spotify as 11131773761
2023-06-12 12:51:42 INFO  music_assistant.players  -- Player registered: aa:aa:46:a4:f0:f0/ESP32-AirPlay-382fd0
authorized
2023-06-12 13:28:12 INFO  music_assistant.providers.spotify  -- Successfully logged in to Spotify as 11131773761`

**Comment by OzGav** [comment]
A few bits didn't get formatted. Can you fix that up?

**Comment by userMak** [comment]
All my automations are working fine except this one.
The automation was working perfectly until last Friday and I haven't "touch" it
in the developers tool I see the following. I am not sure if it is ok that "unknown device"

![image](https://github.com/music-assistant/hass-music-assistant/assets/55662933/ebb21039-271f-4ba7-945a-97a2fc9e2f23)

**Reply by OzGav** [reply]
Can you see above there are sections that aren't formatted correctly. Can you fix that otherwise it is too hard to read...

**Comment by userMak** [comment]
I am trying to add it properly but I can't...
please give me a minute

**Reply by OzGav** [reply]
You have formatted half correctly. Just highlight the rest and press the <> button

**Comment by userMak** [comment]
can you try this?

https://pastebin.com/kv8pruU7

**Reply by agdamsbo** [reply]
```
- id: Mute Player2
  alias: Mute Player2
  trigger:
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: idle
      to: offhook
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      to: ringing
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: offhook
      to: idle
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: ringing
      to: idle
  condition: 
      - condition: state
        entity_id: sensor.makis_home
        state: 'home'
  action:
      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'playing'
          sequence:
            - service: media_player.media_pause
              entity_id: media_player.squeezelite_382fd0
      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'paused'
          sequence:
            - service: media_player.media_play
              entity_id: media_player.squeezelite_382fd0
      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'idle'
          sequence:
            - service: media_player.media_play
              entity_id: media_player.squeezelite_382fd0
```

Put "```" on its own line before and after to print as code 👍

**Reply by OzGav** [reply]
OK so thanks @agdamsbo ! So what does the HA automation trace show is happening. Either one of those four phone state changes aren't occuring or makis_home is not "home". I am asking these things because in your intial post you say the triggers are not working which means this is not an MA issue?

**Reply by userMak** [reply]
> OK so thanks @agdamsbo ! So what does the HA automation trace show is happening. Either one of those four phone state changes aren't occuring or makis_home is not "home". I am asking these things because you rintial post you say the triigers are not working which means this is anot an MA issue?

That is not the problem. The phone for example right now is idle
![image](https://github.com/music-assistant/hass-music-assistant/assets/55662933/e235c3ce-2651-49c4-b222-845eb38e713f)

the player is on status playing
![image](https://github.com/music-assistant/hass-music-assistant/assets/55662933/fc74196f-fb75-4e94-af22-94bc6661fb1c)

the sensor makis is home
![image](https://github.com/music-assistant/hass-music-assistant/assets/55662933/f73f68ee-e64d-45f5-8f37-0f3753867855)

I get a call.. the phone is ringing
![image](https://github.com/music-assistant/hass-music-assistant/assets/55662933/5ef18973-4dd9-4384-ba38-b0af7dc7dbf6)

nothing happens

In the automation logs (now I saw this option) I get the following
although it says paused nothing is happening.. 


![image](https://github.com/music-assistant/hass-music-assistant/assets/55662933/8d08f420-6a94-4b19-bf0a-e3ec6121985d)

**Reply by OzGav** [reply]
Not sure if it is a bug or not as you are using the HA service call with a MA player... Use the mass.queue_command instead. See the FAQ for the syntax: https://github.com/orgs/music-assistant/discussions/710

**Reply by OzGav** [reply]
Actually isn't that trace showing that "No Action Taken"?

Edit: You can look at the STEP DETAILS tab to see the actual values of the sensors and what they changed from and to

**Reply by OzGav** [reply]
Edit: Actually I see there are various options with choose syntax...

**Reply by userMak** [reply]
I really can not understand where the problem is.

if I keep only the following part of the automation is working with both services  (mass.queue + media_player,media_pause
it pauses the MA

```
  action:
      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'playing'
          sequence:
          
#            - service: mass.queue_command
#              data:
#                enqueue_mode: play
#                command: pause
#                player_id: media_player.squeezelite_382fd0
                
            - service: media_player.media_pause
              entity_id: media_player.squeezelite_382fd0

```
when I add the following, (in order to resume playing) it doesn't even pause the MA
and I am sure it was working ok for the previous 2 weeks
all the conditions are met but nothing happens.

```
      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'paused'
          sequence:
            - service: media_player.media_play
              entity_id: media_player.squeezelite_382fd0
```

**Reply by userMak** [reply]
sorry this is my mistake.. (I don't know how it happened though)

it needs only one choose: in the autaomation.yaml
sorry and thank you for your time..

I really don't know how the code messed up.

**Comment by userMak** [comment]
```
- id: Mute Player
  alias: Mute Player
  trigger:
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: idle
      to: offhook

    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      to: ringing

    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: offhook
      to: idle
      
    - platform: state
      entity_id: sensor.makis_smartphone_phone_state
      from: ringing
      to: idle
  
  condition: 
      - condition: state
        entity_id: sensor.makis_home
        state: 'home'

  action:
      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'playing'
          sequence:
            - service: media_player.media_pause
              entity_id: media_player.squeezelite_382fd0

      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'paused'
          sequence:
            - service: media_player.media_play
              entity_id: media_player.squeezelite_382fd0

      - choose:
        - conditions:
          - condition: state
            entity_id: media_player.squeezelite_382fd0
            state: 'idle'
          sequence:
            - service: media_player.media_play
              entity_id: **media_player.squeezelite_382fd0
```
