### DISCUSSION TITLE
Direct link for the music assistant radio page?

### DISCUSSION THREAD

**Discussion by mefistofelis** [music-assistant/support#1488] [Q&A] [answered]
Is there any way that i can make a button in home assistant, which when clicked navigates directy to the radio page of music assistant?

**Comment by krisnoble** [comment]
Sure, here's the YAML for a [button card](https://www.home-assistant.io/dashboards/button/) that you can then add to a `grid` or however you want to set it up:
```
type: button
tap_action:
  action: url
  url_path: http://<MASS_ADDRESS>:8095/#/radios
name: Radio
icon: mdi:access-point
```
Essentially just using the [`tap_action`](https://www.home-assistant.io/dashboards/actions/#tap-action) rather than the default action you get when using an entity directly.
