### DISCUSSION TITLE
MQTT ID assignment and play if NFC Tag is scanned or via MQTT triggered

### DISCUSSION THREAD

**Discussion by marc4s** [music-assistant/support#1498] [Feature requests and ideas]
For the Toniebox for example there is a private Cloudproject called toniecloud which implements an MQTT Client sending the NFC UID via MQTT to HA. Would be cool if MusicAssistant could assign NFC IDs to music/albums which would be then played if the NFC Tag is added.
Implementing such a feature would not be limited to Toniebox/Teddycloud. it would things made just easier implementing a NFC reader to trigger music / videos via HA.

**Comment by OzGav** [comment]
Maybe I don’t understand but can’t you just use the mqtt message to trigger a script?

**Reply by marc4s** [reply]
yes. but the assignement is much to complicate and you would have a lot of scripts. it would just easier if there could be linked a MQTT Topic in MusicAssistant and then Assign UIDs to Albums . much more comfortable. and implementation should not be to much effort
I hope

**Reply by OzGav** [reply]
Will have to see how many upvotes you get for this idea to see where it fits in the priorities list. Thanks!

**Comment by krisnoble** [comment]
Could you do a single automation  like this? Key concept is editing the trigger ID, which is hidden behind  the three dots in the HA UI.

IDs would be the album/artist/playlist name or [media URI](https://github.com/orgs/music-assistant/discussions/710)

```
alias: NFC music
description: ""
trigger:
  - platform: tag
    tag_id: <tag_id>
    id: example album 
  - platform: mqtt
    topic: example/music
    payload: <tag_id>
    id: example album 2

condition: []
action:
  - service: media_player.play_media
    data:
      media_content_type: music
      media_content_id: "{{ trigger.id }}"
    target:
      entity_id: media_player.example_player
mode: single
```
