### DISCUSSION TITLE
Music Assistant with Spotify and scripts H.A.

### DISCUSSION THREAD

**Discussion by Asdrubale1234** [music-assistant/support#1553] [Q&A] [answered]
I would like to listen to a playlist randomly but when I enable this option, music assistant sends all the playlists randomly and not just the one I chose, how can I solve this?

**Comment by OzGav** [comment]
Can you show your script

**Reply by Asdrubale1234** [reply]
Yes 
```
alias: Playlist Selene
sequence:
  - service: media_player.media_play
    data: {}
    target:
      entity_id: media_player.homepod_soggiorno_2
  - service: media_player.play_media
    target:
      entity_id: media_player.homepod_soggiorno_2
    data:
      media_content_id: library://playlist/1
      media_content_type: playlist
    metadata:
      title: Selene
      thumbnail: null
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: mass
          media_content_id: playlists
        - media_content_type: music
          media_content_id: library://playlist/1
  - service: media_player.shuffle_set
    data:
      shuffle: true
    target:
      entity_id: media_player.homepod_soggiorno_2
mode: single
icon: mdi:music
```

**Reply by OzGav** [reply]
I have formatted your reply so we can read it.

Please refer to the FAQ which shows that you need to just use the playlist name as the `media_content_id`. Additionally you should set the shuffle mode first. Finally, I don’t know what that first service call is for.

**Reply by Asdrubale1234** [reply]
so if my playlist is called Selene I only put this name? without various codes? 

Could you give me an example please?

**Reply by OzGav** [reply]
Correct. There is an example in the FAQs

**Reply by Asdrubale1234** [reply]
Sorry but not work, where am I wrong? Can you please write me a command line for the script I'm trying to create? does not work

Entity_id is entity create with Music assistant 


```
alias: Playlist Luca
sequence:
  - service: media_player.shuffle_set
    data:
      shuffle: true
    target:
      entity_id: media_player.homepod_soggiorno_2
  - service: media_player.play_media
    data:
      media_content_type: music
      media_content_id: Luca
    target:
      entity_id: media_player.homepod_soggiorno_2
```

**Reply by OzGav** [reply]
When you say it doesn't work please explain eactaly what happens. Do you have errors in the HA log or MA log?

**Reply by Asdrubale1234** [reply]
No error displayed, the script doesn’t work this way, I’m not listening in shuffle mode, but I’m listening to all playlists in shuffle. It shuffles all playlists, not just the one I really want.

**Reply by OzGav** [reply]
Maybe you don’t understand how this works. Each player has a queue. You add music in the form of tracks or playlists to the queue. The queue can have shuffle enabled or not. 
The script you have above will first set the queue to shuffle mode. This only applies to music that is subsequently added to the queue. If there are tracks already in the queue they will remain there and their order will not change.
The second part of your script will add the playlist (I’m assuming that is what “Luca” is) to the end of the queue and those tracks will be shuffled when they are added.
Based on what you have above maybe you want to clear the queue first?

**Reply by Asdrubale1234** [reply]
I want the shuffle mode to be only on a specific playlist ‘Luca,’ as I have set? Thanks

**Reply by OzGav** [reply]
That is what that script will do. You are not explaining clearly what is not working.

**Reply by OzGav** [reply]
Also please confirm which version of the integration you have installed and while you are there which version of the MA server

**Reply by OzGav** [reply, marked as answer]
I’m going to guess your queue needs to be cleared first so try his

```
alias: Playlist Luca
sequence:
  - service: mass.queue_command
    data:
      command: clear
      player_id: media_player.homepod_soggiorno_2
  - service: media_player.shuffle_set
    data:
      shuffle: true
    target:
      entity_id: media_player.homepod_soggiorno_2
  - service: media_player.play_media
    data:
      media_content_type: music
      media_content_id: Luca
    target:
      entity_id: media_player.homepod_soggiorno_2
```
