### DISCUSSION TITLE
Play Random Album from Specific Genre?

### DISCUSSION THREAD

**Discussion by ministryofsillywalks** [music-assistant/support#1637] [Q&A] [answered]
This is a pretty specific setup, but it's a pretty integral part of our daily life, so here goes:
I am currently using LMS and have a CLI script that plays a random Album from a certain genre in LMS library.
I use this, as my little daughter has a zigbee button in her room which she can press, which then plays a random Audio Book Album from a predefined Genre. Once that book is done the service calls the next random album from the genre etc.
Is there currently any way to achieve this in MA?

**Comment by OzGav** [comment]
I expect you would be limited by what you can do with HA scripts. For example https://community.home-assistant.io/t/trying-to-run-a-random-script/226402

but not sure how you can keep track of what has already been played…?

**Comment by ministryofsillywalks** [comment]
The new features just introduced look great 
https://github.com/music-assistant/server/pull/1228
"Random album from library" playlist now exists.
Is there any built-in way to play "random album from genre" now?

**Reply by marcelveldt** [reply]
Not yet, we will offer more builtin playlists as well as make Genres more prominent after the 2.0 release.

**Reply by ministryofsillywalks** [reply]
Looking forward to this feature.
Only thing still keeping me with Lms, as ma otherwise has completely replaced lms.

**Reply by ministryofsillywalks** [reply]
Is there a way using MASS Play Media when requesting an Album from a certain artist to not always play the first result?
If it could randomly pick a result, this could already accomplish what I'm trying to achieve.
Currently when asking MA to play an album from a certain artist it always plays the same album (I'm guessing the first result)

**Comment by ministryofsillywalks** [comment, marked as answer]
until this is natively implemented I hacked together a script to achieve what I wanted.
This script does a mass search for "ARTISTNAME" returns 9 results (can increase the number) then plays a random URI from the list.
Works great! Thanks for making this so flexible!

```
alias: Random Album
sequence:
  - service: mass.search
    data:
      limit: 9
      name: ARTISTNAME
      artist: ARTISTNAME
      media_type:
        - album
    response_variable: results
  - service: mass.play_media
    metadata: {}
    data:
      media_id: "{{ results.albums[range(1, 10) | random].uri }}"
    target:
      device_id: XYZ
mode: single

```

**Reply by OzGav** [reply]
Nice! I might add this to the how do I section!

edit: should the range be 0 to 8?

**Reply by ministryofsillywalks** [reply]
Good catch. I would probably have never noticed, that the first array entry was never played ;)
I stole the random range from another automation which I had, which needed to start at 1.

**Reply by JDogg016** [reply]
So relying on this to relate a call service node in node red to play a random playlist.

My json data for the service call mass 'play_media' is as follows:

{
   "media_id": "{{ payload.playlists[array(1, 10) | random].uri }}"
}

I receive the following error:

HomeAssistantError: MediaNotFoundError: Could not resolve ['{{ payload.playlists[array(1, 10) | random].uri }}'] to playable media item

I use payload as the variable in mine instead of 'results' because the prior call service to search outputs the results to msg.payload.  Also I use array because the results show in an array.

Any suggestions?

**Reply by OzGav** [reply]
~I suggest you post the full yaml and format it correctly as you see done by the OP three posts above yours.~ Actually I see you are using node red. Not sure if you will get any reply as not many people use that but see how you go.

**Reply by kreativmonkey** [reply]
I had a view issues with this solution:

1. the search result with only 10 albums are highly simular to each other, it's happend a lot of time that i got the same album twice...
2. unlike the search request the results from youtube music are not releated to the search request. I got albums with variouse artists instead of the searched artist.

so i modified your script to:

```yaml
alias: Random Album
sequence:
  - data:
      limit: 50
      media_type:
        - album
      artist: ARTISTNAME
      name: ARTISTNAME
    response_variable: results
    action: mass.search
  - action: input_text.set_value
    target:
      entity_id: input_text.playback_album
    data:
      value: |
        {% set album = namespace(value=None) %}
        {% for _ in range(results.albums | length) %}
          {% set random_album = results.albums[range(1,50) | random] %}
          {% if random_album.provider == 'spotify' %}
            {% set album.value = random_album.uri %}
            {% break %}
          {% endif %}
        {% endfor %}
        {{ album.value if album.value else '' }}
  - metadata: {}
    data:
      media_id: "{{ states('input_text.playback_album') }}"
    action: mass.play_media
    target:
      entity_id: media_player.buro
    enabled: true
mode: single
icon: mdi:account-music
```

and i set the value to a input_text helper to store the last album that was played. this is used in an automation where the last album will be started if the player is not playing anything, or randomely pick a new album if the player plays a currently a album.

**Comment by napalmcsr** [comment]
I am trying to get X number of random tracks across my library.  I am trying to see if that is possible out of this implementation.  I am not seeing a way yet.  Any advice?

**Reply by OzGav** [reply]
There is the 500 random tracks playlist which is auto generated by MA. Note that it is subject to an issue report at the moment though.

**Reply by napalmcsr** [reply]
yeah, I am trying to replicate that functionality due to it having an issue..  I can be patient :)

**Reply by marcelveldt** [reply]
it is fixed in the 2.2 release

**Reply by napalmcsr** [reply]
Nice! Thanks!

**Comment by OzGav** [comment]
With the integration update to 2024.11.0 a new action is available which should satisfy this request.

```
sequence:
  action: music_assistant.get_library
  data:
    media_type: track
    search: ARTISTNAME
    limit: 1
    order_by: random
  response_variable: random_track
  action: mass.play_media
  data:
    media_id: "{{ random_track.[‘items’][0].uri }}"
    media_type: track
    enqueue: play
    radio_mode: true
  target:
    entity_id: media_player.ma_kitchen_speaker
```

If you want a queue of tracks then:

```
    sequence:
      - service: music_assistant.get_library
        data:
          media_type: track
          search: ARTISTNAME
          limit: 10
          order_by: random
        response_variable: random_tracks
      - repeat:
          count: "{{ random_tracks['items'] | length }}"
          sequence:
            - action: mass.play_media
              data:
                media_id: "{{ random_tracks.[‘items’][repeat.index - 1].uri }}"
                media_type: track
                enqueue: add
              target:
                entity_id: media_player.ma_kitchen_speaker
```

**Reply by amoranvalero** [reply]
@OzGav I have tested themass.get_library action in HA and for tracks and the response query for tracks is always empty. See attached picture. My intention is get random tracks for an artist.

![Screenshot_2024-11-08-17-14-57-044_io homeassistant companion android-edit](https://github.com/user-attachments/assets/fb058420-2e3d-465d-a216-27bb2dae8104)


The rest of get_library actions (over albums, artists, playlist ... works but erratically, for example two consecutive polling to albums leads to a result of empty response). To complete information my arrangement I only have a music source in MA which is a subsonic server.

![Screenshot_2024-11-08-17-23-40-779_io homeassistant companion android](https://github.com/user-attachments/assets/9ca555d3-47f3-4560-9e51-2c96204e54a0)

![Screenshot_2024-11-08-17-22-09-042_io homeassistant companion android](https://github.com/user-attachments/assets/f5113e39-216a-42af-b5a5-05a5b0dbbdd7)


Am I doing terribly wrong? Or is there any limitation?

Thanks and regards.

**Reply by OzGav** [reply]
No I think this is a bug. @marcelveldt is this randomising the tracks then grabbing the limit and then doing the search instead of doing the search, randomising the results and then applying the limit?

edit: Also it looks like the search is across the whole JSON. I wonder if it should be looking only in the album:name or artist:name key for album and artist media types and only the high level name key for other types?

**Reply by OzGav** [reply]
@amoranvalero We haven't forgotten about this. Do you see the same behaviour with the core integration and the `music_assistant.get_library` action?

**Reply by OzGav** [reply]
The random search should be fixed in 2.4.0rc7 or later

**Reply by kreativmonkey** [reply]
That isn't working for me. As far as i understand, the library is only something that i've sotred/created. For example, if i search a random song from an artist not in my bibliothek but in spotify for example, the result is empty. Only if i add an song from that artist to any library on spotify that i own, then i can play it with the .get_library functionality. 

Some of us are playing stories like audiobooks and don't want to hear every evening the same one. The idea of getting random album is, to not manually search for a new storie and play it. The problem with my solution above is, that the search function is also limited to 50 results and they are mostly the same results on the same request... so you only can randomly choose between 50 results and not from all albums of that artist. The `get_library` function sounds good but isn't resolving that problem :-(

**Reply by OzGav** [reply]
Sounds like you want the `music.assistant.search` action then

edit: and I don’t know where you are getting the limit of 50 from. The limit can go up to 500 with the slider.

**Reply by kreativmonkey** [reply]
off course it can, but I tested it out and I did get error when I go higher then 50...

![Screenshot_2025-02-24-14-43-25-48_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/5d6453ce-5ce0-4627-87d7-93375b2bde2d)


![Screenshot_2025-02-24-14-43-38-97_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/e26027c3-1ce0-4dc7-a7a2-ee9c74d707e5)

when I'm at home, I can check the logs for more details.

**Reply by OzGav** [reply]
Its OK I can recreate it. Looks like it might be a Spotify limitation. We are looking at what can be done as each provider has a different limit

**Reply by OzGav** [reply]
It is a Spotify limitation but it can be worked around. We will add an item to fix this on the backlog but it wont make the 2.4 release

**Reply by OzGav** [reply]
Change of plan this should be fixed in the 2.4.0 release! edit: Confirmed fixed.

**Reply by kreativmonkey** [reply]
Thank you and sorry for missing to report this limitation! I planned to spend more time to find the problem behind this limit to get a detailed report but currently my time is so rear that i need to focus on the not so funny parts!

**Comment by rofo69** [comment]
I have a strange issue with the getlibrary call.

I took the example script from here:- https://www.music-assistant.io/faq/get_library/

And noticed that if I set a limit of more than 6, the (count: "{{ random_tracks | length + 1}}" is only ever 6, so only 6 tracks get added to the playlist.
Trying exactly the same call in dev tools appears to output the correct number of records.

**Reply by OzGav** [reply]
Not sure exactly what the problem is with the current code but just change the count line to `count: 10` or whatever number you have set your limit as

**Reply by OzGav** [reply]
Yes sorry that was a typo. The correct line should be `{{ random_tracks['items'] | length }}`

**Comment by upamanyudas** [comment]
Is there any update on implementing genre support? Would be a very useful feature.

**Comment by mr-bembel** [comment]
Hello, and thank you for your work!

Anyway I try to implement the scripts, I end up with "Error rendering data template: UndefinedError: 'dict object' has no attribute 'tracks"

Any clue?

**Reply by OzGav** [reply]
It might be due to a bug in the get_library action. Use the dev tools to call the action and see if you get any results.

**Reply by mr-bembel** [reply]
Sorry, I forgot to mention I'm on 2.4.4.
The first part of the script returns me a random playlist correctly when executed independently. But the second part doesn't seem to do it...

```
 sequence:
      - service: music_assistant.get_library
        data:
          limit: 10
          media_type: track
          config_entry_id: 01JG94QS3XXXXXXX615Y5KQ3YA
          order_by: random
        response_variable: random_tracks
      - repeat:
          count: "{{ random_tracks['items'] | length }}"
          sequence:
            - action: music_assistant.play_media
              data:
                media_id: "{{ random_tracks['tracks'][repeat.index - 1].uri }}"
                media_type: track
                enqueue: add
              target:
                entity_id: media_player.musiccast_cuisine_2
```

Then I think it's OK with music_assistant.get_library.

**Reply by OzGav** [reply]
Yes sorry this is using some of the old action code.

try changing the media_id to 

{{ random_tracks['items'][repeat.index - 1].uri }}

**Reply by mr-bembel** [reply]
Don't be sorry, thank you very much for your help!!!

It leads to: "Could not resolve [] to playable media item"

**Reply by OzGav** [reply]
Not sure what to tell you as this works for me

```
script:
  test_queue_command:
    mode: single
    sequence:
      - service: music_assistant.get_library
        data:
          config_entry_id: 01JMYCMQJ55CR9E7YZW3VKEA4F
          limit: 10
          media_type: track
          order_by: random
        response_variable: random_tracks
      - repeat:
          count: "{{ random_tracks['items'] | length }}"
          sequence:
            - action: music_assistant.play_media
              data:
                media_id: "{{ random_tracks['items'][repeat.index - 1].uri }}"
                media_type: track
                enqueue: add
              target:
                entity_id: media_player.ma_kitchen_speaker_provct
```

If it doesn't work for you then start by using the dev tools to make sure the get_library action is returning 10 items. If that is working then you can use the COPY TO CLIPBOARD (TEMPLATE) button and paste that into the dev tools template tab. Change action_response to random_tracks and then you can test `{{ random_tracks['items'] | length }}` and `{{ random_tracks['items'][repeat.index - 1].uri }}` but you will need to replace `repeat.index - 1` with a number from 0 to 9.
