### DISCUSSION TITLE
Play single song from youtube music with home assistant?

### DISCUSSION THREAD

**Discussion by ignacio82** [music-assistant/support#1721] [Q&A] [answered]
I have music assistant working with youtube music and I can play song wihtout any problems using the UI. I'm now trying to play a single song on a loop using a home assistant service call. This is one of my many attempts:

```
service: mass.queue_command
data:
  enqueue_mode: play
  uri: v=NJKXhFNxWD4&list=RDAMVMNJKXhFNxWD4
  repeat_mode: one
  player_id: media_player.danielle_s_bedroom_2
  command: play
```

I also tried ` uri: "You Are My Sunshine"` but that didn't work either. Could you point me in the right direction? Thanks!
