### DISCUSSION TITLE
Automation with local files or playlists

### DISCUSSION THREAD

**Discussion by semaf** [music-assistant/support#1725] [Q&A] [answered]
Hey,

Couldnt find exactly some information what the URI for local files.

```
action:
    - service: mass.play_media
      target:
        entity_id: media_player.group_1
      data:
        media_id: media-source://media/file.mp3
        media_type: track
```

**Comment by OzGav** [comment]
Read the FAQ

**Reply by semaf** [reply]
Did it
https://github.com/orgs/music-assistant/discussions/710

**Reply by OzGav** [reply]
Then whats the problem?

**Reply by semaf** [reply]
Asked above: Couldnt find exactly some information what the URI for local files. Results is "Unknown error"

**Reply by semaf** [reply]
Same goes to playlist
```
action:
    - service: mass.play_media
      target:
        entity_id: media_player.group_1
      data:
        media_content_id: WakeUp
        media_content_type: music
```

Error
`extra keys not allowed @ data['media_content_id']. Got None extra keys not allowed @ data['media_content_type']. Got None required key not provided @ data['media_id']. Got None`

**Reply by semaf** [reply]
For anyone with similar issue. I have a track called WakeUp.mp3 and playlist WakeUp. The media_id: WakeUp just played with the media_type: track. Seems that it read local file names in the folder /media

```
  - service: mass.play_media
    target:
      entity_id: media_player.group_1
    data:
      media_id: WakeUp
      media_type: track
```

**Reply by OzGav** [reply, marked as answer]
Sorry I had to go out. Yes if you look at the examples at the bottom of the FAQ for how to use the play_media service you will see you can specify a track name via uri like this `Billy Joel - A Matter of Trust`or if you have a play with the service in the developer tools you will see you can also do this

```
service: mass.play_media
target:
  entity_id:
    - media_player.squeezeplay_80_1f_02_ab_1b_53
  device_id: []
  area_id: []
data:
  media_type: track
  enqueue: replace
  media_id: piano man
  artist: Billy Joel
```

I have updated the FAQ text to be clearer and to match the examples at the bottom
