### DISCUSSION TITLE
Loop/repeat function

### DISCUSSION THREAD

**Discussion by nadzvee** [music-assistant/support#1969] [Q&A] [answered]
Okay guys, so I'm having an issue with the music assistant add on from hacs. Basically I would like to create an automation to play a lullaby from YouTube music and cast it to the bedroom nest Hub. Now I have managed to get this working but I am unable to repeat/loop the track. I can do it manually from the music assistant UI, but no way of setting this up when playing the script in the automation. 

Thanks in advance

Here is my automation yaml below

*******

service: mass.play_media
data:
  media_id: Hush Little Baby
  media_type: track
  album: Lullaby Baby
enabled: true
target:
  device_id: cvxtstfhhdyfghft...

*******

**Comment by OzGav** [comment]
You can turn in the repeat mode using a service call https://www.home-assistant.io/integrations/media_player/

p.s. please format your YAML by using this button <>

**Comment by nadzvee** [comment]
Sorry about the formatting

But this is my whole automation yaml. I've tried using the media_play.repeat_set service but with no luck. Thanks

`alias: HushBaby
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.hushbaby
condition: []
action:
  - service: mass.play_media
    data:
      media_id: Hush Little Baby
      media_type: track
      album: Lullaby Baby
    enabled: true
    target:
      device_id: c10d5781bdf0c82887625a2ea937b47d
  - service: media_player.repeat_set
    data:
      repeat: one
    target:
      device_id: c10d5781bdf0c82887625a2ea937b47d
    enabled: true
mode: single
`

**Reply by OzGav** [reply]
Please highlight all of the yaml then press the <> button

**Comment by nadzvee** [comment]
Sorry again. Attempt 3

```
alias: HushBaby
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.hushbaby
condition: []
action:
  - service: mass.play_media
    data:
      media_id: Hush Little Baby
      media_type: track
      album: Lullaby Baby
    enabled: true
    target:
      device_id: c10d5781bdf0c82887625a2ea937b47d
  - service: media_player.repeat_set
    data:
      repeat: one
    target:
      device_id: c10d5781bdf0c82887625a2ea937b47d
    enabled: true
mode: single
```

**Reply by OzGav** [reply]
I don’t think you are calling the service correctly 

```
  - service: media_player.repeat_set
    data:
      repeat: one
      entity_id: media_player.yourMediaPlayer
```

I don’t know about that `enabled` key you are using, where is that from? Try using the entitiy_id instead of device_id

**Reply by nadzvee** [reply]
Tried calling it like that got an error. 

Amended the script as follows but still no luck

```
alias: HushBaby
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.hushbaby
condition: []
action:
  - service: mass.play_media
    data:
      media_id: Hush Little Baby
      media_type: track
      album: Lullaby Baby
    enabled: true
    target:
      device_id: c10d5781bdf0c82887625a2ea937b47d
  - service: media_player.repeat_set
    data:
      repeat: one
    enabled: true
    target:
      entity_id: media_player.nadzvee_bedroom_nest_hub
mode: single
```
