### DISCUSSION TITLE
Create a home assistant service to mark a song as favorite

### DISCUSSION THREAD

**Discussion by eric1905** [music-assistant/support#1984] [Feature requests and ideas]
I am listening a lot to music assistant radio where I hear a lot of songs I don't know but which I like. So I want to add them to my favorites.
Currently I need to take my smartphone, open music assistant, klick on the current running song, klick again on the current running song and then I am able to mark this song as a favorite.

I would love to be able to use a mass service for this feature. So I can use a button trigger to call the service and mark it as favorite. Or to create a card in my Lovelace UI.

Maybe there should be a parameter to check if it is already in favorite if the favorite should be toggled or if it check if it already a favorite so nothing will happen.

**Comment by eric1905** [comment]
It would be also great if there is one service to check if it is already a favorite

**Comment by lumper5** [comment]
Having favorites so implemented would be very helpful for creating dynamic playlists, too.

**Comment by JulioVillamizar** [comment]
+1

**Comment by OzGav** [comment]
A dedicated HA action will be added soon but you can also do this:

A REST API is available in MA that we are yet to fully document. However, in regards to being able to favourite and unfavourite in HA you can do the following. It is assuming you wish to favourite (or unfavourite) the song currently playing on `media_player.ma_picoreplayer`

```
rest_command:
  ma_add_favourite:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/favorites/add_item",
        "args": {
          "item": "{{ states.media_player.ma_picoreplayer.attributes.media_content_id }}"
        }
      }
    content_type:  'application/json; charset=utf-8'
    
  ma_remove_favourite:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/favorites/remove_item",
        "args": {
          "media_type": "track",
          "library_item_id": "{{ states.media_player.ma_picoreplayer.attributes.media_content_id.split("track/")[1] }}"
        }
      }
    content_type:  'application/json; charset=utf-8'
```

You are then able to call these commands by triggering on a button state change (for example) and then simply use:

```
  actions:
    - action: rest_command.ma_add_favourite
```

**Reply by msknight** [reply]
Unfortunately I couldn't get the restapi to work. Despite adding the "api:" to the configuration.yaml I was obviously missing something and I couldn't work out what.

I'll just wait for the official implementation.

**Comment by andyhoarty** [comment]
OK I got this to work.

I added the following to  configuration.yaml

rest_command:
  ma_add_favorite:
    url: "http://<HA IP Address>:8095/api"
    method: POST
    headers:
      accept: "application/json"
    content_type: "application/json"
    payload: >
      {
        "message_id": "1",
        "command": "music/favorites/add_item",
        "args": {
          "item": "{{ state_attr('media_player.office_speaker_2', 'media_content_id') }}"
        }
      }

  ma_remove_favorite:
    url: "http://<HA IP Address>:8095/api"
    method: POST
    headers:
      accept: "application/json"
    content_type: "application/json"
    payload: >
      {
        "message_id": "2",
        "command": "music/favorites/remove_item",
        "args": {
          "media_type": "track",
          "library_item_id": "{{ state_attr('media_player.office_speaker_2', 'media_content_id').split('track/')[1] }}"
        }
      }
      
**You will need the AppDaemon Integration**

In appDaemon Python packages add 'websockets'

You can add the following python code to the appDaemon folder under apps - I used Studio Code Server. (You will have to change the media player ids).

[ma_favorite_status.txt](https://github.com/user-attachments/files/21142514/ma_favorite_status.txt)

Finally, add the following to scripts.yaml.

add_to_favorites:
  sequence:
  - action: rest_command.ma_add_favorite
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - event: ma_refresh_favorite
  mode: single
  alias: Add to Favorites
  description: ''
remove_from_favorites:
  sequence:
  - action: rest_command.ma_remove_favorite
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - event: ma_refresh_favorite
  mode: single
  alias: Remove from Favorites
  description: ''
  
  I then created a button using custom-button-card this is the yaml
  
  type: custom:button-card
        entity: input_boolean.track_is_favorite
        icon: mdi:heart
        name: Favorite
        show_name: false
        tap_action:
          action: call-service
          service: >
            [[[ return entity.state === 'on' ? 'script.remove_from_favorites' :
            'script.add_to_favorites'; ]]]
        styles:
          icon:
            - color: >
                [[[ return entity.state === 'on' ? 'rgba(255, 0, 0, 0.7)' :
                'rgba(255,255,255,0.3)'; ]]]
          card:
            - background-color: transparent !imporatnt
            - box-shadow: none
        card_mod:
          style: |
            ha-card {
              background: transparent !important;
              color: white;
              border-radius: 10px;
              border: 6px outset gray;
            }
            ha-state-icon {
              --icon-symbol-size: 50px;
            }
            
Now I have a button where the heart is red if the song playing is marked as favourite or grey if not. When you click the button depending on the current state it will either add or remove from favourites and the heart will change colour.

Hope this helps.

**Reply by OzGav** [reply]
In the lastest HA version there is a dedicated button entity to mark the currently playing song as a favourite.

**Reply by pedolsky** [reply]
> In the lastest HA version there is a dedicated button entity to mark the currently playing song as a favourite.

May I ask if there are any restrictions? 
I've reported an issue but maybe Core is the wrong category (or it isn’t an issue at all and I've misunderstood the documentation).

https://github.com/home-assistant/core/issues/148318

**Reply by OzGav** [reply]
I’m away at the moment so can’t test again but last time I used it, it worked fine. Try some other stations.

**Reply by andyhoarty** [reply]
Unfortunately the dedicated button will only add to favourites my result allows you to favourite or unfavourite based on the current state

**Reply by OzGav** [reply]
Sure. Just letting you know that it exists.

**Reply by trianglesis** [reply]
> In the lastest HA version there is a dedicated button entity to mark the currently playing song as a favourite.

I didn't find how to call it from an automation.
Where is this button?

**Reply by OzGav** [reply]
Just look in the MA integration at one of the devices
<img width="342" height="265" alt="image" src="https://github.com/user-attachments/assets/df5e0a8b-6159-4ce6-862c-ff7ccec3030a" />

**Comment by andyhoarty** [comment]
The issue I had when I started using Music Assistant was unbeknown to me I had thousands of favourite tracks.

I have the following script which removes 250 favourites at a time. I did try 500 but the script failed due to the size of the response.

```
alias: Clear Favorites
mode: single
sequence:
  - action: system_log.clear
    metadata: {}
    data: {}
  - data:
      favorite: true
      limit: 250
      offset: 0
      album_artists_only: false
      config_entry_id: **<MUSIC ASSISTANT config_entry_id>**
      media_type: track
    response_variable: favorite_tracks_response
    action: music_assistant.get_library
  - variables:
      items: >-
        {{ favorite_tracks_response['items'] if favorite_tracks_response is
        defined else [] }}
      items_str: "{{ items | tojson }}"
      uris: "{{ items_str | regex_findall('library://track/(\\d+)') }}"
  - action: system_log.write
    data:
      level: critical
      message: |
        Extracted URIs: {{ uris }}
  - repeat:
      sequence:
        - variables:
            trackid: "{{ repeat.item }}"
        - action: system_log.write
          metadata: {}
          data:
            level: critical
            message: "\"Logging track ID: {{ trackid }}\""
        - action: rest_command.ma_remove_favorite_dynamic
          metadata: {}
          data:
            library_item_id: "{{ repeat.item }}"
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 300
      for_each: "{{ uris }}"
  - action: persistent_notification.create
    metadata: {}
    data:
      message: "\"Removed {{ uris | count }} tracks from favorites.\""
      title: Favorites Removed
      notification_id: "1000"
```
You will need to add your  config_entry_id:

You will also need the following Rest Command in your configuration.yaml

```
rest_command:
  
  ma_remove_favorite_dynamic:
    url: "http://<HA IP>:8095/api"
    method: POST
    headers:
      accept: "application/json"
    content_type: "application/json"
    payload: >
      {
        "message_id": "remove-fav-{{ library_item_id }}",
        "command": "music/favorites/remove_item",
        "args": {
          "media_type": "track",
          "library_item_id": "{{ library_item_id }}"
        }
      }
```
