### DISCUSSION TITLE
How to configure custom sentences with Music Assisant?

### DISCUSSION THREAD

**Discussion by MilanAra88** [music-assistant/support#2065] [Q&A] [answered]
Hi there, 

Im a bit of a noob, so apologies in advance :) 

I am trying to get my HA voice assist working with MA. I know there is now a method working with CHAT GP but i would like to just se the local call using the internal HA assist and then to call the MA service based on any artist or song that i verbalise. 

Does anyone have a walkthrough for this? Im struggling to decipher how to do this using sentences automation with wildcards for the artist and tracks and then passing those to the MA service. 

Many thanks :) 

-----

Using the UI to configure the automation - i get an error as the service cant pass on the wildcard

<img width="2081" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/43094647/7d9fc032-68a4-4f5e-913c-4901c12d4206">

![image](https://github.com/music-assistant/hass-music-assistant/assets/43094647/21b9cd78-9386-4cb6-bcb9-bf4cf97a12ed)

-------

bit of trial and error i managed to get this to work:

in config.yaml i added

```
intent_script:
  Media:  # Intent type
    speech:
      text: Playing "{{artist}}"
    action:
      service: mass.play_media
      target:
        device_id: c75ae91c846b1b11e291ddf13ffbec38
        entity_id: media_player.volumio_2
      data:
        media_type: artist
        enqueue: play
        media_id: "{{artist}}"
```

in a config/costom_sentences/en/media.yaml i added

```
intents:
  Media:
    data:
      - sentences:
          - "Play {artist}"
lists:
  artist:
    wildcard: true
```

:) apologies - noob
