### DISCUSSION TITLE
Filter explicit content

### DISCUSSION THREAD

**Discussion by dannytrigo** [music-assistant/support#2079] [Feature requests and ideas]
It may not be possible from all sources, but it would be nice to be able to filter out any songs marked as having explicit content, similar to YouTube musics restricted mode.

**Comment by OzGav** [comment]
This has been aded to the backlog for a future release. No ETA can be given

**Comment by ChristopherBull** [comment]
Sharing context for my +1:
Living in a family household with young children (who like to command the voice assistants). Not being able to make it family safe (without painstakingly, manually curating play lists for all family members) is very limiting. I eagerly await any progress towards this.

**Comment by nimbling** [comment]
From a moral point of view: Isn't this a waste of resources to implement at this level?

All the streaming platforms themselves can be configured to censor out objectionable things, so why not have people configure this there?

-and it that fails, perhaps have people talk to their offspring?

**Reply by ChristopherBull** [reply]
Because profiles are not fully supported in music assistant, so we can't configure external services per user.

Also, "perhaps have people talk to their offspring" does not consider wider context of use (I'll ignore the subtext about parenting). Teenagers can be talked to. Younger children (say, 3) typically are not the best at rational conversations and have the autonomy to ask voice assistants to play video/music when parents are not around.

Maybe someone may want to play some music with guests around their house and want to optionally skip the explicit songs that evening. 

Much of tech these days is designed with a single user in mind. Which is not the same context as home technology.

**Comment by skyw33** [comment]
I recognize that this is in the backlog, but I'm looking for workarounds.  If explicit=yes/no existed in the attributes of the music assistant media player, then it would allow users to implement a custom solution.  I'm not seeing anywhere in home assistant nor in the ytmusic api here: https://ytmusicapi.readthedocs.io/en/stable/

Has anyone found if this information is included in song information?

**Reply by OzGav** [reply]
I notice it in the results from the new `get_library` action.

**Reply by skyw33** [reply]
Thanks.  Is that function for local music only?  I can't seem to get it to work for ytmusic.  A little more research into ytmusicapi and I found that  they added explicit queries to getalbum but I have no idea how to access that.

https://github.com/sigma67/ytmusicapi/issues/99

https://github.com/sigma67/ytmusicapi/commit/cb1f58d696dc10ca4efc1bb74f7c4cfd2db7eb9c#diff-5d788a0bfa55447ce77081a8b233e6cb23f4359a46809b0640ba0d64edccf1a9R469

**Reply by OzGav** [reply]
The items do need to be in your library. Might need @MarvinSchenkel to add it if it isn’t already?

**Reply by OzGav** [reply]
Here is a solution. You can put this straight into a file as a [package](https://www.home-assistant.io/docs/configuration/packages/)

You will need to adjust with your player entity name. The way it works is that it monitors the media_position attribute of the player. This will change when a new track is loaded. This change will cause the automation to fire which calls the script. The script uses the `get_queue` action to get information about the track, the explicit tag is checked and the track skipped if it's true. Clearly this depends on the explicit tag being set by the provider.

```
template:
  - sensor:
        unique_id: mc_media_position
        state: >
          {{ state_attr(states.media_player.ma_picoreplayer.state, 'media_position') }}

automation:
  - id: check_for_explicit
    mode: queued
    alias: "Check for track with explicit lyrics"
    trigger:
      - platform: state
        entity_id: sensor.media_card_media_position
    action:
      - service: script.turn_on
        data:
          entity_id: script.skip_explicit_track

script:
  - skip_explicit_track:
    mode: queued
    alias: "Skip explicit track"
    sequence:
      - action: mass.get_queue
        continue_on_error: true
        data:
          entity_id:  media_player.ma_picoreplayer
        response_variable: queue_info
      - if:
          - condition: template
            value_template: >
                      {% if queue_info['media_player.ma_picoreplayer'].current_item.media_item.metadata.explicit is defined 
                         and queue_info['media_player.ma_picoreplayer'].current_item.media_item.metadata.explicit is not none -%}
                        {{ queue_info['media_player.ma_picoreplayer'].current_item.media_item.metadata.explicit | lower }}
                      {% endif %}
        then:
          - action: media_player.media_next_track
            target:
              entity_id: media_player.ma_picoreplayer	
```

**Reply by skyw33** [reply]
This is great!  Thank you @OzGav 

I use ytmusic and I used "media_content_id" instead of "media_position".  Here are my files for reference:

EDIT: Actually, "media_position_updated_at" seems to work best.

automation.yaml:

```
alias: Check for track with explicit lyrics
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.template_mc_media_position
conditions: []
actions:
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.skip_explicit_track
mode: single
```


script:

```
mode: queued
alias: Skip explicit track
sequence:
  - action: mass.get_queue
    continue_on_error: true
    data:
      entity_id: media_player.master_bed
    response_variable: queue_info
  - if:
      - condition: template
        value_template: >
          {% if
          queue_info['media_player.master_bed'].current_item.media_item.metadata.explicit
          is defined 
             and queue_info['media_player.master_bed'].current_item.media_item.metadata.explicit is not none -%}
            {{ queue_info['media_player.master_bed'].current_item.media_item.metadata.explicit | lower }}
          {% endif %}
    then:
      - action: media_player.media_next_track
        target:
          entity_id: media_player.master_bed
        data: {}
description: ""
```


config.yaml

```
template:
  - sensor:
      - name: Master Bed Media Position
        unique_id: mc_media_position
        state: >
          {{ state_attr('media_player.master_bed', 'media_content_id') }}

```
