### DISCUSSION TITLE
Music Assistant integration with Google Assistant

### DISCUSSION THREAD

**Discussion by jokerigno** [music-assistant/support#2091] [Q&A] [answered]
Hi, 

I just installed MA and searched here and in the web to see if someone already asked it with no success so I open a new discussion.

We have several google home mini (1st gen) around the use and use mainly voice to start/change/stop music. 

As far as I understood MA uses its own media_player so this means that there's no "integration" between MA and other services right?

I mean if I start playing music using my Google Assistant media_player.device is showing attributes while media_player.devicemusicassistant don't and if I click next song in media_player.devicemusicassistant it does not reproduce next song in queue bust start with latest song listened in MA.

Same happens for announcements. If device used is media_player.devicemusicassistant  ok otherwise restart of the playing does not happens.

I'm making statements I know but just to understand if my usage is correct.

BEcause if so I understand that I have to choose to go full deep the local voice to have full compatibility right?

**Comment by OzGav** [comment]
If you install the MA integration then HA is aware of the MA players and you could send the Spotify tracks to those players. However, there is no point as you don’t get any of the MA features (and as you saw sometimes there is unexpected behaviour) so you may as well just send to the HA media players.

**Comment by jokerigno** [comment]
> If you install the MA integration then HA is aware of the MA players and you could send the Spotify tracks to those players. 

How using voice? 

Because I can do it via web browser (nice UI btw) but how can I say "hey google, play my music from spotify in the kitchen" and then "use" media_player created using MA?

ATM if I say  "hey google, play my music from spotify in the kitchen" in MA I see that device is used by "external source" (no attributes shown)
![immagine](https://github.com/music-assistant/hass-music-assistant/assets/23552762/0727f15e-9b92-42ce-9652-12ebe6e7978d)

If now I call tts service

```
service: tts.speak
target:
  entity_id: tts.google_translate_say
data:
  cache: true
  media_player_entity_id: media_player.cucina (this is the default google cast device )
  message: test

```

music is stopped and no message reproduced.

If I call this

```
service: tts.speak
target:
  entity_id: tts.google_translate_say
data:
  cache: true
  media_player_entity_id: media_player.cucina_ma (this is the device created by MA)
  message: test
```

music is stopped, announcements is reproduced but then music is not restarted.
