### DISCUSSION TITLE
Custom Assistant Intents

### DISCUSSION THREAD

**Discussion by OzGav** [music-assistant/support#2176] [Show and tell]
Note that this discussion will be updated (including the attached files) as HA core updates occur. (Updated for HA 2026.6.0 All Volume, Mute, Pause, Resume, Previous and Next intents removed. Improvements have been made to attempt to mimic HA's capability to identify the correct player when targetting an area)

HA supports the commands of NEXT, PREVIOUS, PAUSE, UNPAUSE, MUTE and VOLUME when targeted at a specific player or to an area. The PLAY command must be supported by the user a [blueprint is available in a dedicated repository](https://github.com/music-assistant/voice-support). For the remaining [service calls](https://www.home-assistant.io/integrations/media_player/) (including targetting areas) you can use custom sentences. Note that targetting an area which has multiple players may result in unpredictable behaviour although for Clear Queue and Stop the player that is in the state of `playing` will be targeted.  

Firstly add this file to \\\YOUR_HA_IP\config\custom_sentences\en
[media.yaml](https://github.com/user-attachments/files/30727410/media.yaml)

Of course you can change this file to reflect your language and change the `en` in the file path accordingly. Please share any translations below.

Next you need to add to your `configuration.yaml` file the following. Note I have the unique characters `ma_` in my `entity_id` which is used to select the correct player when targetting an area. You could also check for players which have the `mass_player_attribute`. If you don't want to add those characters you can either use a different set of characters and adjust the templates accordingly or remove all of the area based intents and not use that functionality.

```
intent_script:
  ShuffleSet:
    action:
      service: "media_player.shuffle_set"
      data:
        entity_id: "{{ media_player }}"
        shuffle: "{{ shuffle_mode }}"
    speech:
      text: "Queue shuffle mode set"

  ShuffleSetArea:
    action:
      service: "media_player.shuffle_set"
      data:
        entity_id: "{{ expand(states.media_player) | selectattr('entity_id', 'in', area_entities(area)) | select('search', 'ma_') |map(attribute='entity_id') | join }}"
        shuffle: "{{ shuffle_mode }}"
    speech:
      text: "Queue shuffle mode set"

  RepeatSet:
    action:
      service: "media_player.repeat_set"
      data:
        entity_id: "{{ media_player }}"
        repeat: "{{ repeat_mode }}"
    speech:
      text: "Queue repeat mode set"

  RepeatSetArea:
    action:
      service: "media_player.repeat_set"
      data:
        entity_id: "{{ expand(states.media_player) | selectattr('entity_id', 'in', area_entities(area)) | select('search', 'ma_') |map(attribute='entity_id') | join }}"
        repeat: "{{ repeat_mode }}"
    speech:
      text: "Queue repeat mode set"

  ClearQueueArea:
    action:
      service: "media_player.clear_playlist"
      data:
        entity_id: "{{ expand(states.media_player) | selectattr('entity_id', 'in', area_entities(area)) | select('search', 'ma_') | selectattr('state', 'eq', 'playing') | map(attribute='entity_id') | join }}"
    speech:
      text: "{{ expand(states.media_player) | selectattr('entity_id', 'in', area_entities('study')) | select('search', 'ma_') |map(attribute='attributes.friendly_name') | join }} Queue cleared"

  ClearQueue:
    action:
      service: "media_player.clear_playlist"
      data:
        entity_id: "{{ media_player }}"
    speech:
      text: "Queue cleared"

  PlayerStop:
    action:
      service: "media_player.media_stop"
      data:
        entity_id: "{{ media_player }}"
    speech:
      text: "Stopped"

  PlayerStopArea:
    action:
      service: "media_player.media_stop"
      data:
        entity_id: "{{ expand(states.media_player) | selectattr('entity_id', 'in', area_entities(area)) | select('search', 'ma_') | selectattr('state', 'eq', 'playing') | map(attribute='entity_id') | join }}"
    speech:
      text: "Stopped"

  SelectSource:
    action:
      service: "media_player.select_source"
      data:
        entity_id: "{{ media_player }}"
        source: "{{ desired_source }}"
    speech:
      text: "{{ media_player }} source set to {{ desired_source }}"
      
  PlayerJoin:
    action:
      service: "media_player.join"
      target:
        entity_id: "{{ media_player_group }}"
      data:
        group_members: "{{ media_player }}"
    speech:
      text: "{{ states.media_player | selectattr('entity_id','eq',media_player) | map(attribute='attributes.friendly_name') | list | join }}  joined to {{ states.media_player | selectattr('entity_id','eq',media_player_group) | map(attribute='attributes.friendly_name') | list | join }} "

  PlayerUnjoin:
    action:
      service: "media_player.unjoin"
      target:
        entity_id: "{{ media_player }}"
    speech:
      text: "{{ states.media_player | selectattr('entity_id','eq',media_player) | map(attribute='attributes.friendly_name') | list | join }} removed from group"
```
