### DISCUSSION TITLE
Cannot set PUBLISHED IP ADDRESS

### DISCUSSION THREAD

**Discussion by siwinter** [music-assistant/support#2280] [Q&A] [answered]
I have installed MASS as a Docker container on a raspi, which has two network interfaces, the normal eth0 and a wireguard endpoint wg0.
After starting, MASS uses the IP address of wg0, but this is not accessible for other nodes in the local network. Instead, MASS should use the "normal IP address" (eth0).
In the log file I see IP address of wg0 as part of the media_content_id sent in the play_media service to the media players.

I have read the documentation ([troubleshooting-page](https://music-assistant.io/faq/troubleshooting/)) , but I don't understand exactly what I am supposed to do.

On my settings page, which can be accessed via the gear-icon at the top right of the home page, there are only settings for provider data (music, player, metadata, plugins). Cannot see any "core settings".

Starting the docker container with a environment variable "PUBLISHED_IP_ADDRESS=<eth0 ip address>"does not help either.
This is my docker file:
``` 
services:
  music-assistant:
    container_name: music-assistant-stable-test
    image: "ghcr.io/music-assistant/server:stable"
    volumes:
      - /home/docker/mass_test:/data
      - /home/docker/data:/media
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - LOG_LEVEL=debug
      - PUBLISHED_IP_ADDRESS=192.168.10.10
```

What am I doing wrong?
As a workaround, I start the MASS container first and only then set up the VPN tunnel. Then it works.
