### DISCUSSION TITLE
Randomize the search result before returning result in `mass.search` service

### DISCUSSION THREAD

**Discussion by dsync89** [music-assistant/support#2401] [Feature requests and ideas]
Currently, the `mass.search` service always returns a fixed list of items for the same query (e.g., same name and media_type), no matter how many times the search is repeated. It would be beneficial to randomize the items internally before returning the results. At present, the `limit` field in `mass.search` merely selects the top n_limit tracks. For instance, if the search yields 1000 items and the limit is set to 500, it will always return the same 500 tracks, leaving the remaining 500 tracks never chosen for the queue.

As a temporary workaround, I perform a search for a large number of items, randomize the results, and then select only a subset. You can see the script I use here: [GitHub Discussion #2400](https://github.com/orgs/music-assistant/discussions/2400). However, this doesn't fully resolve the issue, as the service still returns the same number of tracks as defined by the limit field. At least it provides the illusion of fresh tracks by selecting a different subset each time.

**Comment by OzGav** [comment]
With integration 2024.11.0 there is a new service `get_library`. With this you should be able to achieve your request. For example:

```
script:
  test_get_library_and_queue:
    mode: single
    sequence:
      - service: music_assistant.get_library
        data:
          limit: 2
          media_type: track
          order_by: random
        response_variable: random_tracks
      - repeat:
          count: {{ random_tracks['items'] | length }}
          sequence:
            - action: music_assistant.play_media
              data:
                media_id: "{{ random_tracks.tracks[repeat.index - 1].uri }}"
                media_type: track
                enqueue: add
              target:
                entity_id: media_player.ma_kitchen_speaker
```

edit: Updated for the core integration
