### DISCUSSION TITLE
Refresh MA playlist with script

### DISCUSSION THREAD

**Discussion by mooseBringer** [music-assistant/support#2403] [Q&A] [answered]
Is it possible to trigger a refresh of the random playlists (random artist from library/random album) from a script/automation? 

I have programmed a shelly button in my kitchen to start the random artist on my kitchen chromecast audio. Works like a charm, double click it and it starts a spotify pop list for my wife. Tripple click it and it starts random artist from library for me. The thing is that I always not satisfied with the first pick of artist.

Therefore I want to clear the cue and refresh the playlist then repopulate with the next random artist. I have managed it to work exept it doesen't change artist until either the time triggers it or I manually reset it in the webview.

Also I really like MA, great work everyone involved!

**Comment by OzGav** [comment]
Not at the moment but you could do something like this https://music-assistant.io/faq/how-to/#play-a-random-item

**Reply by mooseBringer** [reply]
Thanks! Is there a way to fetch a random artist name from the library to use as a variable to put in there?

**Reply by OzGav** [reply]
No. You could do this

```
service: mass.search
  data:
    limit: 5
    media_type: 
      - artist
    name: >
       {{ “ABCDEFGHIJKLMNOPQRSTUVWXYZ” | random }}
```

but being able to limit the search to the library is currently on the to do list.

**Reply by mooseBringer** [reply]
Thanks for the help, I've found a somewhat diffrent approach but can't get the correct url. I have made a almost functioning script that fetches an artist name from a input_source but it seems that the album url that is genereated is in the wrong format. I don't know what I'm doing wrong.

This is what the urls looks like:
spotify://album/21BxTgtthTPefP1e7gXVtV
tidal--RNvku5U7://album/22560688

The one I manually fetched from MA UI look like this and works: https://open.spotify.com/playlist/37i9dQZF1DWTMYgB8TqtmR

The script so far:
```
alias: MA_RandomAlbum
sequence:
  - service: input_text.set_value
    metadata: {}
    data_template:
      entity_id: input_text.ma_kok_artist
      value: "{{ state_attr('input_select.ma_kok_artister', 'options') | random }}"
  - service: mass.search
    metadata: {}
    data:
      limit: 9
      name: input_text.ma_kok_artist
      media_type:
        - album
    response_variable: ma_searchResults
  - service: mass.play_media
    metadata: {}
    data:
      enqueue: replace_next
      media_id: "{{ ma_searchResults.albums[range(0, 8) | random ].uri }}"
    target:
      entity_id: media_player.kok_2
mode: single
icon: mdi:playlist-music
```

**Reply by OzGav** [reply]
Firstly please format any yaml you post so it is readable using the <> icon. I have done that for you.

Why are you trying to generate the URI when you can just pass the album, track, artist or playlist name? EDIT: OK I see that is what the example has. Try with just `.name` instead of `.uri`

**Reply by mooseBringer** [reply, marked as answer]
Thanks! 
The `.name` did it and I had the wrong syntax for calling helpers. Now I set up a input_select to randomly fetch my manually added favorites from and store in a helper (then I can also edit it from UI) and then do a mass search for random album. Works great. Also I did one more script for artist radio.

Random artist from input select and mass album search:
```
alias: MA_GetRandomAlbum
sequence:
  - service: input_text.set_value
    data_template:
      entity_id: input_text.ma_kok_artist
      value: "{{ state_attr('input_select.ma_kok_artister', 'options') | random }}"
  - service: mass.search
    data:
      limit: 20
      name: "{{ states.input_text.ma_kok_artist.state}}"
      media_type:
        - album
      artist: "{{ states.input_text.ma_kok_artist.state}}"
    response_variable: ma_searchResults
  - service: input_text.set_value
    data_template:
      entity_id: input_text.ma_kok_album
      value: "{{ ma_searchResults.albums[range(0, 8) | random ].name }}"
mode: restart
icon: mdi:playlist-music
````

Then play:
```
alias: MA_PlayRandomAlbum
sequence:
  - service: mass.play_media
    data:
      media_id: "{{ states.input_text.ma_kok_album.state}}"
      media_type: album
      artist: "{{ states.input_text.ma_kok_artist.state}}"
    target:
      entity_id: media_player.kok_2
    enabled: true
mode: restart
icon: mdi:playlist-music
```

Artist radio:
```
alias:` MA_PlayGeneratedArtistRadio
sequence:
  - service: mass.play_media
    data:
      media_id: "{{ states.input_text.ma_kok_artist.state}}"
      media_type: artist
      artist: "{{ states.input_text.ma_kok_artist.state}}"
      radio_mode: true
    target:
      entity_id: media_player.kok_2
    enabled: true
mode: restart
icon: mdi:playlist-music

```
**EDIT! (Got an easier script in the other thread)** And when I listen to an "not added" artist I stole a script to add it from media player artist and add to the list:
```
alias: ma_addArtistToRandomizer
service: input_select.set_options
  metadata: {}
  data:
    options: "{{ state_attr('input_select.ma_kok_artister', 'options') + [state_attr('media_player.kok_2','media_artist')]}}" 
  target:
    entity_id: input_select.ma_kok_artister
mode: restart
```
OG: [Stolen from](https://community.home-assistant.io/t/add-remove-an-option-in-input-select-with-an-action/375978/7?u=timpa )

Sorry for the wall of text, I'm just happy with it all 😅
Thanks again!

**Comment by CaseyRo** [comment]
I have a similar request to update the playlist, I'm using https://basyl.stream/ - excellent spotify playlists, but they are 'running with the day' so to say, so I need to refresh the playlist every time before starting a new play.

Adding a refresh service call would be amazing, I can also imagine people using collaborative playlists would like that too, or other 'real time' playlists.

**Comment by FredHags** [comment]
I have the same need for Navidrome Smart/dynamic playlists.
For example:
A dynamic playlist where I have 5 podcast which hasn't been played and was added to Navidrome within the last 7 days.
The playlist doesn't update until I manually refresh it in MA.

**Reply by de666** [reply]
Same for me with navidrome smart playlist which are not refreshed automatically or cannot be refreshed programmatically from HA

**Comment by OzGav** [comment]
While it will take some time to properly document it MA has an extensive API. This can be used to refresh the playlist. Here is an example:

```
rest_command:
  ma_refresh_playlist:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/playlists/playlist_tracks",
        "args": {
          "item_id": "1234",
          "provider_instance_id_or_domain": "library",
          "force_refresh": true
        }
      }
    content_type:  'application/json; charset=utf-8'
```

You may need to adjust the URL and item_id. If you have port 8095 exposed via the MA webserver settings then the above will work. If not then try http://d5369777-music-assistant:8095/api

To get the item_id use `music_assistant.get_library` to search for the playlist and you can find the info there as shown in the following example image 

![image](https://github.com/user-attachments/assets/3193d11d-9646-42e1-9403-5dccb4b8a4bf)

**Reply by mooseBringer** [reply]
I have some issues getting it to work, I get the following error:
```
content: |
  <html><head><title>500 Internal Server Error</title></head><body>
  <h1>500 Internal Server Error</h1>
  Server got itself in trouble
  </body></html>
status: 500
```

Didn't get as a detailed answer for get_library it looks like this
```
items:
  - media_type: playlist
    uri: library://playlist/43
    name: 500 Random tracks (from library)
    version: ""
    image: http://192.168.0.10:8095/imageproxy?path=logo.png&provider=builtin&size=0
```

I guess 43 should be my id like this?
```
ma_refresh_playlist_500:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/playlists/playlist_tracks",
        "args": {
          "item_id": "43",
          "provider_instance_or_domain": "builtin",
          "force_refresh": true
          }
      }
```

**Reply by marcelveldt** [reply]
for "provider_instance_or_domain" you need to fill in "library" if you are use a library id as "item_id"

**Reply by OzGav** [reply]
Thanks. Updated in my original post.

**Reply by mooseBringer** [reply]
Still can't get it to work 🤔 Probably I'm not formatting it right but I'm also curious about why I don't get the item_id in the response from ```music_assistant.get_library``` as @OzGav is displaying in the example

```
content: |
  <html><head><title>500 Internal Server Error</title></head><body>
  <h1>500 Internal Server Error</h1>
  Server got itself in trouble
  </body></html>
status: 500
```
```
items:
  - media_type: playlist
    uri: library://playlist/5
    name: 500 Random tracks (from library)
    version: ""
    image: http://192.168.0.10:8095/imageproxy?path=logo.png&provider=builtin&size=0
  - media_type: playlist
    uri: library://playlist/2
    name: All favorited tracks
    version: ""
    image: http://192.168.0.10:8095/imageproxy?path=logo.png&provider=builtin&size=0
  
```
```
Logger: homeassistant.components.rest_command
Källa: components/rest_command/__init__.py:154
integration: RESTful Command (dokumentation, ärenden)
Inträffade först: 13:27:48 (1 händelser)
Senast loggade: 13:27:48

Error. Url: http://192.168.0.10:8095/api. Status code 500. Payload: b'{ "message_id": "1", "command": "music/playlists/playlist_tracks", "args": { "item_id": "43", "provider_instance_or_domain": "library", "force_refresh": true } }'
```

**Reply by OzGav** [reply]
Yes sorry typo. I have corrected my post `provider_instance_or_domain` should be `provider_instance_id_or_domain`

**Reply by Andy071993** [reply]
@OzGav 
First of all: Thank you for providing the script for us.

Is it possible to adjust the script, that it will refresh multiple playlists at once?
I tried it with "item_id": "43, 57, ..." but this is not working.

For a single playlist it is working perfectly (for example: "item_id": "43)!

**Reply by OzGav** [reply]
No sorry the argument expects a single id.

**Reply by Andy071993** [reply]
@OzGav 
I think I found a solution for playlist refresh with multiple playlists:

I moved my rest_commands in the rests.yaml with the following command in configuration.yaml
`rest_command: !include rests.yaml`

Inside the rests.yaml I used your code and changed the item_id to a variable "{{ playlistnumber }}"
```
#Music Assistant Refresh Playlist
  ma_refresh_playlist:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/playlists/playlist_tracks",
        "args": {
          "item_id": "{{ playlistnumber }}",
          "provider_instance_id_or_domain": "library",
          "force_refresh": true
        }
      }
    content_type:  'application/json; charset=utf-8'
```

Than I added the following automation script, where you can add as many playlists as you want (in my case it triggers every night at 5am):
```
alias: Music Assistant Refresh Playlists
description: ""
triggers:
  - trigger: time
    at: "05:00:00"
conditions: []
actions:
  - variables:
      playlists:
        - "35"
        - "11"
  - repeat:
      count: "{{ playlists | count }}"
      sequence:
        - action: rest_command.ma_refresh_playlist
          data:
            playlistnumber: "{{ playlists[repeat.index - 1] }}"
mode: single
```

I hope it is useful. 🙂
