### DISCUSSION TITLE
Play random radio station from pre-defined list of radio stations from Home Assistant

### DISCUSSION THREAD

**Discussion by fluxor99232** [music-assistant/support#2419] [Feature requests and ideas]
Part of my morning routine for many years has been to trigger a random radio station from a set of a dozen or so international radio stations I like to listen to occasionally. Is there an elegant way to do this with Music Assistant (and triggered by Home Assistant)?

Imperfect solutions I've found so far:

1. Save all the Music Assistant media IDs of the created radio stations as a helper entity Home Assistant and let the latter pick a random one and use it to start playback of that station (a bit cumbersome to identify the IDs and also keep them up to date in case I edit the list)
2. Let Home Assistant search radio stations in Music Assistant using a sufficiently large set of numbers as search terms (say 1 to 100) in, add all the search results to the queue, set playback to random and then send a skip command. (my current solution, but feels a bit hacky and doesn't allow me to ever enable the RadioBrowser provider, because it will then also add lots of radio stations matching the search terms from there to the queue).

Other ideas:

1. Create a playlist with the set of stations I want to use (either with manually created stations or selected stations from the RadioBrowser provider) and then just start playback of that playlist and set the order to random (this would need a new feature, I think, since radio stations currently can't be added to playlists as it seems).

Any other ideas?

**Comment by OzGav** [comment]
2. It is on the to do list to be able to limit the search to only what is in the library. No ETA for that at the moment though.
3. We used to be able to create a playlist with radio stations and I’m not sure why that disappeared. I’ll find out.

**Reply by fluxor99232** [reply]
Sounds great! Thank you so much!

**Comment by Paul-Vdp** [comment]
Looking for a more or less similar solution I first found under 'Go to next/previous radio station via a script' in the doc's FAQ section : 'Create a playlist with multiple radio stations and start playing it'. Sounded good - but could for the life of me not find out how or where this playlist could be created :-(
Looking further, I hit upon the current discussion - learning that the possibility to create such playlist just got lost or ditched somewhere ???

**Reply by OzGav** [reply]
Yes radio stations in playlists is still being discussed.

**Reply by reidjr2** [reply]
Does that mean the answer to the FAQ is wrong as its not possible ?

**Reply by OzGav** [reply]
It used to be possible but not currently. This is what is being discussed

**Reply by Paul-Vdp** [reply]
Then I hope the discussion is about the best way to re-introduce this (sorely missed) feature, and not about the decision to actually re-introduce it - or rather forget about it ....

**Comment by infoguard** [comment]
I use the seconds portion of the timestamp from the automation trigger as a random number generator. Then, I use this generated number to look up a station from a predefined list.

**Reply by infoguard** [reply]
just to be clear, my trigger is a button press and not a preset time (otherwise it would not be a very useful way to implement this)

**Reply by fluxor99232** [reply]
Clever idea! It’s the „predefined list“ part that I found harder to find a satisfying solution for, though. Would much prefer to store and maintain the list in Music Assistant (eg as a playlist as discussed above) opposed to a more cumbersome to maintain list of IDs in Home Assistant.

**Reply by OzGav** [reply]
Being able to add stations to a playlist has been added to the backlog. No ETA can be given,

**Comment by OzGav** [comment]
Integration 2024.11.0 has a new action `get_library`. You could use the following to get a random radio station and then play it. In order to have a subset of the radio stations you could favourite some of them and then use the favourite filter which is an option in the action

```
action: mass.get_library
data:
  media_type: radio
  limit: 1
  order_by: random
response_variable: radio_station
```

**Reply by fluxor99232** [reply]
Sounds fantastic! Will try!

**Reply by DonCarloZz** [reply]
hey, sorry for the beginner question. Where can I set the device in the GUI where the action should be started?

**Reply by OzGav** [reply]
You don’t in that code snippet. Here is a complete example

```
script:
  sequence:
    - action: mass.get_library
      data:
        media_type: radio
        limit: 1
        order_by: random
      response_variable: radio_station
    - action: mass.play_media
      data:
        media_id: "{{ radio_station.radios[0].uri }}"
        media_type: radio
        enqueue: play
        target:
          entity_id: media_player.ma_kitchen_speaker
```

**Reply by Sparkinman** [reply]
I was just looking for a solution to this, and stumbled across this thread.
The above code snippet errors out with all calls starting with mass.xxxx
Looking at the current building blocks, I can recreate the above with the correct calls, but for some reason the radio function doesn't work (tracks or artists however do), can anyone confirm the same?
It seems to error out with either Radio, or radios not defined, here is my code (I X out some of the radio ID's)

```
sequence:
  - action: music_assistant.get_library
    data:
      media_type: radio
      limit: 1
      order_by: random
      config_entry_id: 01JJSHYNTEX1XAXXXXXXXXXXXX
    response_variable: radio_station
  - action: music_assistant.play_media
    metadata: {}
    data:
      media_id: "{{ radio_station.radios[0].uri }}"
      media_type: radio
      enqueue: replace
    target:
      device_id: dfc57bceb9fe4ca41XXXXXXXXXXXX
alias: Random Music Station
description: ""
```

**Reply by OzGav** [reply]
Yes because the json structure changed in the core integration. Try this `media_id: "{{ radio_station.items[0].uri }}"`

**Reply by Sparkinman** [reply]
I get this in response:
Failed to perform the action script/random_radio_station. Error rendering data template: UndefinedError: builtin_function_or_method object has no element.


Next step in debugging was to check the variable had any data, so I displayed a persistent notification, which returned the following:

{'items': [{'media_type': <MediaType.RADIO: 'radio'>, 'uri': 'library://radio/9', 'name': 'Lithium', 'version': '', 'image': '[http://pri.art.prod.streaming.siriusxm.com/images/chan/85/1675f1-3155-fe4a-871d-b344efc868bb.png'}]](http://pri.art.prod.streaming.siriusxm.com/images/chan/85/1675f1-3155-fe4a-871d-b344efc868bb.png'%7D%5D), 'limit': 1, 'offset': 0, 'order_by': 'random', 'media_type': <MediaType.RADIO: 'radio'>}
It does change stations and metat data on each launch, some data is being returned, but something about the media_id seems to throw the above error.
Sorry if I'm making this more compl;icated than it needs to be!

**Reply by OzGav** [reply]
Try
`media_id: "{{ radio_station['items'][0].uri }}"`

**Reply by Sparkinman** [reply]
I get the following:
Failed to perform the action script/random_radio_station. Validation error: Entry not found

**Reply by OzGav** [reply]
Look at the script trace to see if you can work out why. I do note that you have `radio_mode: true` which is not valid in this case.

**Reply by Sparkinman** [reply]
Your last comment worked!
**The key was using:
media_id: "{{ radio_station['items'][0].uri }}"**

When I tried it the first time and it didn't work, I then followed your suggestion of running the trace, it was getting stuck on step one...well my idiot self had left the blanked out (XXXX)'s in the music asistant ID and in the player ID.
After resetting those, it works perfectly!
Thank you for taking the time to help me!!

**Comment by User3n** [comment]
At last got it going thanks, but  favorite: true  is not working and I have favorite radio station in Music Assistant .
favorite: true give object has no element 0

**Reply by OzGav** [reply]
I can't recreate that problem but there is an inconsistency with the way the favourite selection is working I think so I have asked Marcel about it.

**Reply by OzGav** [reply]
@User3n Actually the option is working as designed. Please test this again.

**Reply by User3n** [reply]
Ok test in dev tools

``` 
action: music_assistant.get_library
data:
  media_type: radio
  limit: 1
  order_by: random
  config_entry_id: 01JEBPPMD55PAXZTNKAH7D22JV


items:
  - media_type: radio
    uri: library://radio/4
    name: "- 0 N - 80s on Radio"
    version: ""
    image: https://www.0nradio.com/logos/0n-80s_600x600.jpg
limit: 1
offset: 0
order_by: random
media_type: radio
 ```
And with only favorites true

``` 
 action: music_assistant.get_library
data:
  media_type: radio
  limit: 1
  order_by: random
  config_entry_id: 01JEBPPMD55PAXZTNKAH7D22JV
  favorite: true


items: []
limit: 1
offset: 0
order_by: random
media_type: radio
 ```
