### DISCUSSION TITLE
Queue multiple TTS messages so they play in sequence

### DISCUSSION THREAD

**Discussion by nabahr** [music-assistant/support#2564] [Q&A] [answered]
### What version of Music Assistant has the issue?

2.1.0b7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Any TTS message sent to a speaker while it is currently playing a TTS message is ignored/doesn't play. I would expect that either the new TTS is queued and played next, or maybe even cut off the first message and start playing the second message right away. Queueing and playing both would be my preference.

### How to reproduce

Service call:
```
service: tts.speak
target:
  entity_id: tts.home_assistant_cloud
data:
  media_player_entity_id: media_player.dining_room
  message: I am testing multiple TTS messages
```

Call the service once and the message plays fine, call the service again while the first TTS is still playing and nothing happens. The first TTS will continue playing and the second just disappears.

### Music Providers

N/A

### Player Providers

I have used Chromecast, snapcast, and slimproto. They all have the same issue.

### Full log output

[log.log](https://github.com/user-attachments/files/15929279/log.log)

### Additional information

In the log, I just restarted the server and sent 4 TTS messages back to back to the dining room speaker.

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
Issues are for problems with existing functionality. Why do you think this should work?

**Comment by nabahr** [comment]
I understand this straddles between an issue and a new feature but in the end, I considered that since the second TTS message just disappears, it pushed me more towards it being an issue.

**Comment by OzGav** [comment]
As I understand it HA does not support this either. I will move it to a feature request,

**Comment by jazzyisj** [comment, marked as answer]
This is dead nuts simple to do from HA.

Create a script in HA that you will call whenever you want to send a tts message.
Make sure the script mode is queued.

```
script:
  tts_message:
    alias: "TTS Message"
    description: "Play TTS announcement message."
    mode: queued
    fields:
      message:
        description: "TTS Message to play."
        example: "This is a message."
      media_player:
        description: "Media player to play TTS message on."
        example: "media_player.broadcast_speakers"
    sequence:
      - sequence:
          - action: tts.speak
            data:
              cache: true
              media_player_entity_id: "{{ media_player }}"
              message: "{{ message }}"
            target:
              entity_id: tts.home_assistant_cloud
```

Now, just call this script instead wherever you  would call tts.speak (or whatever tts servicer you use).

```
- action: script.tts_message
  data:
    message: "This is a tts message called from a script"
    media_player: media_player.dining_room_hub_2
```
You now have queued TTS messages.  Easy peasy, nice and sleasy!

@nabahr I edited the action media player to reflect that it should be a music assistant player you specify here.  ("_2")
