### DISCUSSION TITLE
Lower volume when wake word detected (pre mass.play_announcement)

### DISCUSSION THREAD

**Discussion by MrWyss** [music-assistant/support#2713] [Q&A] [answered]
The idea is when a wake word on e.g. an ESPHome device is detected, a service call can be fired. e.g.

```yaml
service: mass.play_announcement
data:
  listening: true
  listening_timeout: 10s #optional or duration
  use_pre_announce: false #optional or true
  announce_volume: 52 #optional or value
  #url: 
target:
  entity_id: media_player.xxxxx
```
This would lower the volume to the specified announcement volume (or to the announcement volume config) while the voice assistant is listening and processing. After the announcement is played, another service call or the timeout expires, the volume will resume to its previous level.

This way is more courteous and reduces the likelihood of the voice assistant mistakenly picking up speech from the media player.
