### DISCUSSION TITLE
Yandex music support

### DISCUSSION THREAD

**Discussion by Furrypaw** [music-assistant/support#2742] [Feature requests and ideas]
If possible add support for [Yandex music](https://music.yandex.ru/home).

**Comment by mrZeffka** [comment]
There is such integration. https://github.com/alryaz/hass-yandex-music-browser
There is such integration.

**Reply by pash111uhh1** [reply]
this provider does not appear to be working anymore, at least i couldn't get it set up myself

**Reply by AlexDeadly** [reply]
There is the fork that works fine for now.
https://github.com/alexanderznamensky/hass-yandex-music-browser
At least it works with HA core 2025.5.2.
But I don't get how to play entire folder or playlist of Yandex but not single track.

For example, when I play single track there is call_service event:

```
event_type: call_service
data:
  domain: media_player
  service: play_media
  service_data:
    entity_id: media_player.denon_avr_x1000_airplay
    media_content_id: track:98123699
    media_content_type: yandex
origin: LOCAL
```
Where "media_player.denon_avr_x1000_airplay" is player configured to stream from MA through AirPlay.
