### DISCUSSION TITLE
Play Speaker Preset from Home Assistant

### DISCUSSION THREAD

**Discussion by janstadt** [music-assistant/support#2922] [Q&A] [answered]
Is there a way to directly play a preset assigned to a specific speaker from HA? The reason im asking is i've noticed that my playlists keep changing id's. I dont know if i am rebuilding my db unknowingly or what, but i have buttons assigned to a specific playlist in HA for my kids favorite artists and every so often it'll all of the sudden it'll start playing something completely random and not the specific artist. I figured if i had a preset assigned that maybe it would just work better or something. I tried doing text specific playlists in the MASS Service but that isnt consistent. Trying to work around the potential bug here with testing presets, but i do believe there is a bug with the unique id's going on. Have there been any thought into implementing a GUID based id that wont change vs numeric ids?

Below is my service call:
```
buttons:
  - type: service
    name: Disney
    id: mass.play_media
    data:
      entity_id: media_player.gretas_room
      media_type: playlist
      media_id: 199
```
This was working just fine a week ago and now the playlist id has changed to 258:
<img width="647" alt="image" src="https://github.com/user-attachments/assets/dc157db9-c2c5-4e72-be4d-ca8ae4a7feae">
