### DISCUSSION TITLE
Add "Never played tracks" built-in playlist!?

### DISCUSSION THREAD

**Discussion by mrgrlscz** [music-assistant/support#2964] [Feature requests and ideas]
Hey, whenever you have a large music library, you often end up listening to the same songs, more or less. It would be cool to have an automatic playlist that picks the songs you haven't listened to yet.

**Comment by marcelveldt** [comment]
If you pick any of the builtin random playlists, they are automatically sorted by playcount next to random. So unplayed tracks will always be first

**Reply by OzGav** [reply]
Integration version 2024.11.0 has a new action `get_library`.

You could use this to build your own random playlist by doing something like the following to get the track names and then iterate over the response variable and add them to a queue:

```
script:
  test_queue_command:
    mode: single
    sequence:
      - service: music_assistant.get_library
        data:
          limit: 10
          media_type: track
          order_by: random_count
        response_variable: random_tracks
      - repeat:
          count: "{{ random_tracks['items'] | length }}"
          sequence:
            - action: music_assistant.play_media
              data:
                media_id: "{{ random_tracks.tracks[repeat.index - 1].uri }}"
                media_type: track
                enqueue: add
              target:
                entity_id: media_player.ma_kitchen_speaker
```

edit: Updated for the core integration
