### DISCUSSION TITLE
Allow volume to be set in mass.play_media call.

### DISCUSSION THREAD

**Discussion by jazzyisj** [music-assistant/support#2988] [Feature requests and ideas]
It would be great if we  had the ability to set the desired volume when playing media from HA using the mass.play_media service so we can play the media and set the volume with the same command.

Example service call:
```
action: mass.play_media
target:
  entity_id: media_player.office_hub_2
data:
  media_id: Epic Classic Rock
  volume: 20
```

**Comment by OzGav** [comment]
You just use the volume set action for that https://www.home-assistant.io/integrations/media_player/

**Reply by jazzyisj** [reply]
Of course, but that requires a separate service call.  One could say the same thing for mass.play_announcement.  

It would actually be great to have same kind of capability for shuffle and repeat as well to avoid separate service calls for those too.
If those parameters could be set in the mass.play_media call, then one could do this:

```
action: mass.play_media
target:
  entity_id: media_player.office_hub_2
data:
  media_id: Epic Classic Rock
  enqueue:: replace
  shuffle: true
  repeat: true
  volume: 20
```

Instead of this:

```
script:
  play_mass_media:
    sequence:
      - action: media_player.shuffle_set
        target:
          entity_id: media_player.office_hub_2
        data:
          shuffle: true

      - action: media_player.repeat_set
        target:
          entity_id: media_player.office_hub_2
        data:
          repeat: true

      - action: media_player.volume_set
        target:
          entity_id: media_player.office_hub_2
        data:
          volume_level: 50

        - action: mass.play_media
          target:
            entity_id: media_player.office_hub_2
          data:
            media_id: Epic Classic Rock
            enqueue: replace
          continue_on_error: true
```
