### DISCUSSION TITLE
Allow programmatic access to favourited library media items from Home Assistant

### DISCUSSION THREAD

**Discussion by jazzyisj** [music-assistant/support#2989] [Feature requests and ideas]
The Music Assistant UI is great, but for me the one thing that is currently lacking with Music Assistant is the ability to actually **automate** playing various media selections efficiently, which for me is kind of the whole point of Home Assistant. I've always had the ability to walk up to a radio, turn it on, and select the station I want to hear.  

What I didn't have before HA is the media I want to hear that just automatically just starts playing when I want it to - for example whenever I arrive home. (With the exception of the old timey clock radio alarm in the morning I suppose).  These days, when media starts playing in my home it just happens automatically most of the time.  However, I would like to be able to (and allow others to ) change what media plays at these times on a fairly regular basis easily and without a hassle.

To accomplish this, in my HA config I have created a system of "media presets" (wake up, morning, sleep, arrive home, music for different scenes etc.) each with their own set of entities and a lovelace card to store the media selections and settings for the preset.

The main stumbling block to doing this efficiently is the inability to programmatically access the library data in MASS from HA. As a stop gap measure I have manually replicated the artist/album/track/playlist/radio items I would like use for my presets with templates.  This is rather cumbersome process and must be manually done whenever the underlying data changes (such as adding or deleting a playlist ).

What would be very useful would be the capability to programmatically access the items that have been marked as favourites in the different media categories so these select templates could be automatically populated and kept in sync with the MASS library.   I have suggested populating with just the favourite items instead of all library items as I think for many people selects containing the entire library contain a overwhelming quantity of entries. By using library favourites, the user can easily limit and control what items are available in HA media list selections.

This could be accomplished a couple of ways, with 1 probably being the easiest to implement and 2 being the easiest option for the end user.

1. Allowing access to the MASS library through a REST API to retrieve this data with a REST sensor in HA which can be used to automatically populate the media list templates.  I tried doing this with SQL sensors but ran into issues with the database being locked.

2. Have MASS integration actually create the select entities containing the favourite media list items which would be updated as determined by MASS (e.g. whenever the mass library syncs, update the selects as well).  This would eliminate the requirement for the end user to create their own select templates.  The data in these entities would of course already be available in HA if the user happens to require it for further use eliminating the need for a separate API calls.

select.mass_artist
select.mass_album
select.mass_track
select.mass_playlist
select.mass_radio_station
*select.mass_media_players

*In addition to the library lists, a select provided by MASS integration that contains a list of the MASS media players would also be very useful as it would eliminate the necessity of the mass media player group and associated automation contained in this package and could be kept in sync by MASS instead of the automation.

And this is how this all can be used - a lovelace card that can select, store, and play selected media in the Home Assistant UI.  In my own config, I have several similar cards for each preset which can be played either automatically or manually by clicking the button on the card.  I can change the selections and settings for these presets on a whim from the Home Assistant UI.  It would just be nice for it all to keep itself in sync with Music Assistant so I don't have to do it manually.

I have created a couple gists with all of the YAML for the lovelace card and package that will create all the entities required for it.
https://github.com/orgs/music-assistant/discussions/2990

![mass_play_media_card](https://github.com/user-attachments/assets/7a356e24-d49e-44ba-bb3d-b18d48b5d476)

BTW - I've noticed a few requests on here that are similar or related that may be at least partially resolved with this feature request. 

Here's a couple of them.
https://github.com/orgs/music-assistant/discussions/415
https://github.com/orgs/music-assistant/discussions/834
https://github.com/orgs/music-assistant/discussions/1863

**Comment by OzGav** [comment]
Recently an option to limit `mass.search` to only return in library items was added. An option to limit to favourites only is also on the backlog

**Reply by OzGav** [reply]
@jazzyisj Have a look at the new `get_library` action in 2.4.0b4. You can now get a list of all favourited items with a variety of filters.

**Reply by jazzyisj** [reply]
Ok this is pretty awesome!  This does EXACTLY what I need and so much more!

I think I've found a little bug though.  

When favorite: true is enabled the name parameter returns as expected.  
When it is false, a different unexpected but valid and extended value is returned.

This is one example of a handful I came across.

`favorite = true`

```
  - item_id: "8"
    provider: library
    name: Cool 100.7
    version: ""
    sort_name: cool 100.7
    uri: library://radio/8
    ...
```

`favorite = false`

```
  - item_id: "14"
    provider: library
    name: CKUE-FM2 "Cool 100.7" Windsor, ON
    version: ""
    sort_name: ckue-fm2 "cool 100.7" windsor, on
    uri: library://radio/14
    ...
```

Anywho as of now, when favorite = true, this YAML works perfectly to populate a template select with radio station names. 

```
template:
  - trigger:
      - trigger: homeassistant
        event: start

      - trigger: event
        event_type: event_template_reloaded

      - trigger: state
        entity_id: input_text.media_radio_play
        to:
    action:
      - action: mass.get_library
        data:
          favorite: true
          media_type: radio
        response_variable: radios

      - variables:
          stations: "{{ radios['radios'] }}"
    select:
      - name: "Media Radio Play"
        unique_id: media_radio_play
        state: "{{ states('input_text.media_radio_play') }}"
        select_option:
          - condition: template
            value_template: "{{ option != none }}"

          - action: input_text.set_value
            target:
              entity_id: input_text.media_radio_play
            data:
              value: "{{ option }}"
        options: >
          {% set station_list = namespace(names=[]) %}
          {% for station in stations %}
            {% set station_list.names = station_list.names + [station.name] %}
          {% endfor %}
          {{ station_list.names }}
```
<img width="787" alt="image" src="https://github.com/user-attachments/assets/c732dda7-5a5b-466e-aa61-5d32f22169a9">
