### DISCUSSION TITLE
Announcements / then Resuming Music Playing not happening.

### DISCUSSION THREAD

**Discussion by MarkHofmann11** [music-assistant/support#3014] [Q&A] [answered]
Hoping someone can help figure out what I need to do for this to work properly.  It was working at one point and stopped for unknown reasons.  I play a 12/hr whitenoise MP3 at night and can get "Open/Close Door" annoucements (also MP3s) and want the whitenoise to resume following the annoucement.  Here is what I have - but the whitenoise doesn't resume - have to manually hit play again in HA.

```
- id: Whitenoise
  alias: Whitenoise
  triggers:
  - entity_id:
    - switch.whitenoise
    from: 'off'
    to: 'on'
    trigger: state
  actions:
  - action: media_player.volume_set
    data:
      volume_level: 0.01
    target:
      entity_id: media_player.master_bedroom_mini_2
  - delay:
      seconds: 3
  - action: mass.play_media
    metadata: {}
    data:
      media_id: White_Noise_10hrs
      media_type: track
      enqueue: play
    target:
      entity_id: media_player.master_bedroom_mini_2
  - delay:
      seconds: 7
  - action: media_player.volume_set
    data:
      volume_level: 0.25
    target:
      entity_id: media_player.master_bedroom_mini_2
  initial_state: 'on'
  mode: single
```

```
- id: Doors_and_Windows_Opened
  alias: Doors and Windows Opened
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.garage_entry_door
    - binary_sensor.kitchen_sliding_door
    - binary_sensor.foyer_window
    - binary_sensor.basement_sliding_door
    - binary_sensor.garage_door_1
    - binary_sensor.garage_door_2
    - binary_sensor.garage_service_door
    from: 'off'
    to: 'on'
  action:
  - wait_template: '{{ is_state(''input_boolean.door_window_playing'', ''off'') }}'
    timeout: 00:00:04
    continue_on_timeout: true
  - entity_id:
    - input_boolean.door_window_playing
    action: input_boolean.turn_on
  - action: switch.turn_on
    entity_id:
    - switch.beep_beep
    - switch.beep_beep_2
  - action: mass.play_announcement
    metadata: {}
    data:
      url: http://192.168.0.14:8123/local/{{trigger.entity_id}}_is_open.mp3
    target:
      entity_id:
      - media_player.foyer_mini_2
      - media_player.family_room_mini_2
      - media_player.master_bedroom_mini_2
      - media_player.basement_mini_2
      - media_player.marks_office_hub_2
  - entity_id:
    - input_boolean.door_window_playing
    action: input_boolean.turn_off
  initial_state: 'on'
  mode: queued
- id: Doors_and_Windows_Closed
  alias: Doors and Windows Closed
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.garage_entry_door
    - binary_sensor.kitchen_sliding_door
    - binary_sensor.foyer_window
    - binary_sensor.basement_sliding_door
    - binary_sensor.garage_door_1
    - binary_sensor.garage_door_2
    - binary_sensor.garage_service_door
    from: 'on'
    to: 'off'
  action:
  - wait_template: '{{ is_state(''input_boolean.door_window_playing'', ''off'') }}'
    timeout: 00:00:04
    continue_on_timeout: true
  - entity_id:
    - input_boolean.door_window_playing
    action: input_boolean.turn_on
  - action: switch.turn_on
    entity_id:
    - switch.beep_beep
    - switch.beep_beep_2
  - action: mass.play_announcement
    metadata: {}
    data:
      url: http://192.168.0.14:8123/local/{{trigger.entity_id}}_is_closed.mp3
    target:
      entity_id:
      - media_player.foyer_mini_2
      - media_player.family_room_mini_2
      - media_player.master_bedroom_mini_2
      - media_player.basement_mini_2
      - media_player.marks_office_hub_2
  - entity_id:
    - input_boolean.door_window_playing
    action: input_boolean.turn_off
  initial_state: 'on'
  mode: queued
```

Hoping someone has some ideas as to why when the announcement automations play, the whitenoise doesn't resume playing automatically.  Using using Google Mini speakers via cast.  

Thanks!
