### DISCUSSION TITLE
Volume Fade (like transition for lights)

### DISCUSSION THREAD

**Discussion by ZeFish** [music-assistant/support#3021] [Feature requests and ideas]
I don't think it's currently possible and it would be really sweet to add.
I would use it everywhere right before calling "off" or "stop" on my media players.

**Comment by thisistotallyshaun** [comment]
I came here to add this.

Currently I do extended fade-outs via a script in Home Assistant, but this is clumsy has a bunch of drawbacks - it changes the actual volume on a device, and also devices like WiiMs only actually go to 5% volume then drop suddenly to zero so it's no a clean fade, particularly when you're doing a long one.

Ideally you'd be able to set a decent length - like up to a minute, even. And also set an envelope shape between linear, log, and sine. Especially sine.

**Comment by simbalasim** [comment]
+1 for native fade action.

I have exactly the same problem, using a script and WiiM, often doesn't work very well.

**Comment by fmsmuc** [comment]
would be nice if it would be implemented. Especially if you join a speaker to a group a API call would be great

**Comment by carlhye** [comment]
Hi @ZeFish 

Carl from the MA team here - can you describe the feature request in more detail?

**Comment by ZeFish** [comment]
Hi! It's just a "little" quality of life feature. When you stop a stream instead of a hard stop maybe juste add a little fade-out (can be like 300 or 500 milliseconds) and then stop the feed.

It's one of those little tiny feature that add a premium feeling to the experience.

The difference between home made and high end.

**Comment by thisistotallyshaun** [comment]
I'm keen for something more flexible than that - I want to be able to control fades & crossfades via Home Assistant automations and scripts.

i.e. tell a particular MA player to fade out for X seconds. Or tell it to start playing a new playlist, but crossfade from whatever's currently playing for X seconds.

Ideally with a specified curve, like sine. The [Audacity docs](https://manual.audacityteam.org/man/fade_and_crossfade.html) have good examples of different curves.

All of the above will be very helpful for sleep-based automation - i.e. taking background noise or music away slowly over time so it doesn't suddenly stop and interrupt sleep, or bringing it in slowly over a long period as a gentle method of waking someone up.

**Comment by Test-subj** [comment]
I have no idea how to modify the lower level code to make it built in or I'd submit a PR, but I've got it working in esphome at least. I have volume sliders for the Music and Announcement mixers that allow a configurable fade time. 

Here's the YAML:

```
number:
  - platform: template
    name: "Music Volume"
    id: music_duck
    min_value: 0
    max_value: 1
    step: 0.01
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          id(media_vol) = (1.0f - x) * 30.0f;    # change if you need more than 30db reduction 
  - platform: template
    name: "Announcement Volume"
    id: announce_duck
    min_value: 0
    max_value: 1
    step: 0.01
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          id(announce_vol) = (1.0f - x) * 30.0f;    # change if you need more than 30db reduction 

  - platform: template
    name: "Media Fade (ms)"
    id: media_fade
    min_value: 0
    max_value: 2000
    step: 100
    restore_value: yes
    optimistic: true
  - platform: template
    name: "Announcement Fade (ms)"
    id: announce_fade
    min_value: 0
    max_value: 2000
    step: 100
    restore_value: yes
    optimistic: true

globals:
  - id: media_vol
    restore_value: yes
    type: float
  - id: announce_vol
    restore_value: yes
    type: float

interval:
  - interval: 100ms
    then:
      - mixer_speaker.apply_ducking:
          id: media_mixing_input
          decibel_reduction: !lambda "return id(media_vol);"
          duration: !lambda "return id(media_fade).state;"
      - mixer_speaker.apply_ducking:
          id: announcement_mixer_input
          decibel_reduction: !lambda "return id(announce_vol);"
          duration: !lambda "return id(announce_fade).state;"
```
