### DISCUSSION TITLE
How does the server work with its call back? Running in kubernetes/k3s

### DISCUSSION THREAD

**Discussion by jurgenweber** [music-assistant/support#3103] [Q&A] [answered]
I have a question about the server, in the doco here; https://music-assistant.io/installation/ under 'server notes';

The server itself hosts a very simple webserver to stream audio to devices. This webinterface must be accessible via HTTP (no HTTPS) by IP-address from local players. See the server's logging at startup to see if the server has correctly auto-detected the local IP.

I find it weird that 'the players' would phone home, but Ok. Here is my problem (well, I am not sure it is a problem but lets see). I am running the server in kubernetes, I run k3s at home. I found this chart; https://artifacthub.io/packages/helm/lmatfy/music-assistant-server all good.

here is a snippet of my values configuration, for some context;
```
# -- Enable devices to be discoverable
hostNetwork: true

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    enabled: true
    primary: true
    type: LoadBalancer
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.1.5
    externalTrafficPolicy: Cluster
    loadBalancerIP: 192.168.1.5
    ports:
      http:
        port: 8095
 ```
 
Now the hostNetwork gives the pod the IP address of the node in which the pod is running on, in theory this IP could change, so I have kube-vip running on my cluster and I allocated to the service/pod a static IP, the thing is... the mass server does not know about this IP, it still starts the server up on the node ip, in this case 192.168.1.27:

```
music-assistant-server-86f47bc4cb-f8p78 music-assistant-server 2024-10-28 13:08:22.288 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.1.27:8097
music-assistant-server-86f47bc4cb-f8p78 music-assistant-server 2024-10-28 13:08:22.296 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.1.27:8095
```
So the question is..... does it matter if that IP changes (192.168.1.27)? If so, how can i tell the server what IP to use? 

Last question, which one of those ports does it try to connect to? 8097 or 8095?
