### DISCUSSION TITLE
Automation to add to playlist

### DISCUSSION THREAD

**Discussion by zaidorx** [music-assistant/support#3147] [Feature requests and ideas]
I have been trying to find a way to easily  add current playing song to a playlist and can't find an easy way. My intention is to work with my local music library (Filesystem provider) and add the current playing song to a predefined playlist.
Using the mass.search actions I can get a lot of information, but the uri points to something like this: library://track/29643 which did not work when I tried it on the playlist. What I am looking for is the relative path to the current playing song with respect to the root folder of the library.
My idea is to use the [File Integration](https://www.home-assistant.io/integrations/file/) to create an automation to add current playing song to a predefined playlist, which is also a m3u file in the local file system.

**Comment by OzGav** [comment]
I think you are thinking too narrowly for what MA does. It combined streaming providers as well as local files. So there are no "relative paths", there are uri to the items.

Probably the closest thing being looked at currently is being able to add an item to your favourites. You would then be able to use the built-in ALL FAVOURITES playlist

**Comment by zaidorx** [comment]
@OzGav Thank for the response. I believe that I understand the concept of MA, at least at a basic level. I think it's an awesome piece of technology and have a great appreciation for all the people involve in this project.
Think I might've not explained properly my request.
Using the developers tools in Home Assistant and making a search using the "Music Assistant: Search Music Assistant" action with the following parameter:
```
action: mass.search
data:
  name: "Sonata No. 8 in C minor, Op. 13 \"Pathétique\": I. Grave – Allegro di molto e con brio"
  media_type: track  
  limit: 2
  library_only: false
```
I get this response: (shortened to the relevant parts)
```
artists: []
albums: []
tracks:
  - item_id: "20480"
    provider: library
   name: >-
      Sonata No. 8 in C minor, Op. 13 "Pathétique": I. Grave – Allegro di molto
      e con brio
    version: ""
    sort_name: >-
      sonata no. 8 in c minor, op. 13 "pathétique": i. grave – allegro di molto
      e con brio
    uri: library://track/20480
     ...   
    artists:
      - item_id: 827
      ...        
    album:
      item_id: 3748
      provider: library
      name: Beethoven's Greatest Hits, Volume 1
      ...
      image:
        type: thumb
        path: >-
          Ludwig_van_Beethoven/Beethoven's_Greatest_Hits,_Volume_1/08_String_Quartet_No._14_in_C-sharp_minor,_Op._131.png
        provider: filesystem_local--ZQDEo6wk
        remotely_accessible: false
    ...
  - item_id: Oi6XzxiHak4
    provider: ytmusic
    name: >-
      Beethoven: Piano Sonata No. 8 in C Minor, Op. 13 "Pathétique": I. Grave -
      Allegro di molto e con brio
    version: ""
    ...
    artists:
      - item_id: UCDU1kkuZqoSHYp3Lv5qx77Q
        provider: ytmusic--vi7h4aWP
       ...
    album:
      item_id: MPREb_El0Gs3PspyC
      provider: ytmusic--vi7h4aWP
      name: "Beethoven: Piano Sonatas Nos. 5-7, Op. 10 Nos. 1-3 & No.8, Op.13"
      version: ""
      sort_name: "beethoven: piano sonatas nos. 5-7, op. 10 nos. 1-3 & no.8, op.13"
      uri: ytmusic--vi7h4aWP://album/MPREb_El0Gs3PspyC
      external_ids: []
      media_type: album
      available: true
      image: null
    disc_number: 0
    track_number: 0
playlists: []
radio: []
```

if you look at the results of the search, there is one from provider : library and another from provider: ytmusic. In the album section of each one there is an "image" property. In the case of the "provider: library" is has the value of the relative path to the album image and in the case of the provider: ytmusic that very same value is "null". So my question is, Could it be possible to have a property in the track section that tell us where the uri is pointing to? Or the path of the track if the provider is library, similar to the image of the album, and null if it is other provider?

**Reply by OzGav** [reply]
The URI is a database entry it isn't pointing to anywhere. Within the database the information about the actual location of the source is retained. You can see this if you SHOW INFO on a track and look down in the PROVIDER DETAILS.

In answer to your final question the answer is yes it would be possible. This would be a feature request. I can transfer this discussion to that category if you like. Note that feature requests are generally prioritised on the basis of votes. You would also need to make clarify what you actually want here. What is the purpose of obtaining the actual path? Note that playlists on each different provider are stored differently.

**Comment by zaidorx** [comment]
please do.
I just want to be able to use an automation, that could be triggered by any possible way, to add the current playing song in a specific player provider, to a preselected m3u playlist that is store along the music files that I have on my local storage, with the added benefit that said playlist could be used by other software.

**Comment by OzGav** [comment]
With MA 2.4 comes an API that can be used for this. Get the value for `uris` from the `media_content_id` attribute of the player. 

The `db_playlist_id` you will need to get by calling `music_assistant.get_library` with the `media_type` set to playlist and noting the number at the end of the URI for the playlist you want to use.

In your automation you will call as an action the rest_command. You can use a template in the uri field for example 
`{{ state_attr(states.media_player.awesome_speaker.state, 'media_content_id') }}`

```
rest_command:
  ma_add_playlist_tracks:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/playlists/add_playlist_tracks",
        "args": {
          "db_playlist_id": "26",
          "uris": ["library://track/3951"]
        }
      }
    content_type:  'application/json; charset=utf-8'
```

**Reply by zaidorx** [reply]
Thank you very much for the update. I have been following the development and noticed this a few days ago. I have already implemented my automation and was able to achieve what I was looking for. It is working fine so far. 
It is really awesome to have these interactions with the development teams. Thank you again. Really appreciate it.

**Reply by RJrodrigo** [reply]
the action music_assistant.get_library is not returning the db_playlist_id

![image](https://github.com/user-attachments/assets/00e70465-9060-42c2-905a-91e901c58ea1)

**Reply by RJrodrigo** [reply]
nvm..
the db_playlist_id is **4**, right?
library://playlist/**4**

**Reply by RJrodrigo** [reply]
A bit off-topic, but does music assistance sync work bidirectionally? If I add a song in MA, does it also get added to Spotify, and other music providers?
Thanks in advance

(use case: working on assist intent for adding currently playing track to playlist by voice)

**Reply by OzGav** [reply]
Review the docs for each provider. Since you asked about Spotify, yes if it is a playlist stored on Spotify then any changes made in Spotify or MA will be synced in both directions,

**Reply by RJrodrigo** [reply]
Getting a 404 when calling the API

```yaml
rest_command:
  ma_add_to_playlist:
    url: "http://homeassistant.local:8123/api"
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/playlists/add_playlist_tracks",
        "args": {
          "db_playlist_id": {{ playlist_id }},
          "uris": [ {{ track_url }} ]
        }
      }
    content_type:  'application/json; charset=utf-8'
```
![image](https://github.com/user-attachments/assets/170f17d8-8103-4d05-8c7d-a48031bcc7b1)

**Reply by RJrodrigo** [reply]
Same result with dev tools

![image](https://github.com/user-attachments/assets/cfc6d3b5-0953-4ad7-85f5-397faac67177)

![image](https://github.com/user-attachments/assets/41773928-0e1c-4206-9be8-8f75b74d4fa5)

**Reply by OzGav** [reply]
Wrong port for a start it should be 8095. You have to enable access to that in the settings.

**Comment by RJrodrigo** [comment]
working example :blush: 

### Action
```yaml
  ma_add_to_playlist:
    url: "http://homeassistant.local:8095/api"
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "music/playlists/add_playlist_tracks",
        "args": {
          "db_playlist_id": "{{ playlist_id }}",
          "uris": [ "{{ track_url }}" ]
        }
      }
    content_type:  'application/json; charset=utf-8'
```

### Automation
```yaml
alias: Add To Playlist
description: ""
triggers:
  - trigger: conversation
    command:
      - Mark {playlist_id}
conditions:
  - condition: device
    device_id: 382288c47f6746fe7e37ee3b6409f162
    domain: media_player
    entity_id: 404911e56fc7c1b74cd4c0ca1883a3b2
    type: is_playing
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.studio_music_player
        attribute: media_content_id
        state: ""
actions:
  - variables:
      search_term: "{{ trigger.details.playlist_id.value }}"
  - action: music_assistant.get_library
    metadata: {}
    data:
      limit: 10
      offset: 0
      config_entry_id: 01JQSC52KYFGHD4B6A6H3AF971
      media_type: playlist
      search: Track {{ search_term }}
    response_variable: response
  - action: rest_command.ma_add_to_playlist
    response_variable: rest_response
    data:
      playlist_id: "{{ response['items'][0].uri.split('/')[-1] }}"
      track_url: "{{ state_attr('media_player.studio_music_player', 'media_content_id') }}"
mode: single
```
