### DISCUSSION TITLE
Max volume limit

### DISCUSSION THREAD

**Discussion by golonac** [music-assistant/support#3288] [Feature requests and ideas]
Hi! I'm using Music Assistant in Home Assistant to stream music to a receiver (Onkyo, DLNA). The MA volume slider controls the receiver's volume setting directly, but setting it below 30 is inaudible, and above 60 is dangerously loud. I've had users accidentally change the volume way too high with the slider, as they are accustomed to 0=not audible, 1=barely audible, 100=loud but not deadly. I didn't find any way to change the limits in MA or HA - HA Onkyo DLNA integration lets me set a maximum volume but the setting is not used by MA, and MA's volume normalization can be used to restrict the max volume, but then the receiver needs to be turned very high to hear anything, which is again dangerous when switching to another source. Apologies if this exists or doesn't belong in MA & thanks for the great app!

In summary: a per-output setting that changes what volumes 0 and 100 map to in the volume slider.

**Comment by Swedlund** [comment]
We need this! Same situation here!

**Comment by rjgrandy** [comment]
+1 for this feature, would love to set a max and min level to be able to use the whole volume range

**Comment by nebriv** [comment]
Also would love this feature!

**Comment by oleost** [comment]
Having same issue with a Samsung soundbar, volume is incredible loud on «low values» on bar. Needs to be able to set maximum output

**Comment by LauriKem** [comment]
This would be amazing - trying to adjust a single player volume on a mobile screen results in easy accidental maxing of a player volume and almost broken eardrums. With this I could also attempt to equalize volumes of different players by bringing the loud ones down.

**Reply by OzGav** [reply]
Accidentally changing the volume has been fixed in 2.7.0 beta 4

**Comment by keesfluitman** [comment]
Just happened to my son as well.

**Comment by ZDBioHazard** [comment]
I have the same issue with my Denon AVR via AirPlay where <5% is inaudible and >30% is "get a new HOA rule named after you", making adjusting the volume quite precarious.

After I nearly vaporized the living room while trying to adjust the stereo volume, I set up the following automation in HA to limit the volume if it gets set too loud:

```yaml
alias: Stereo Volume Limiter
mode: single
triggers:
  - alias: When stereo volume goes over the limit
    trigger: template
    value_template: |-
      {{ ((state_attr("media_player.denon_avr", "volume_level") | default(None)) or 1.0) >
         (states("input_number.stereo_volume_max") | float / 100.0) }}'
actions:
  - alias: Limit the stereo volume
    action: media_player.volume_set
    target:
      entity_id: media_player.denon_avr
    data:
      volume_level: |-
        {{ min(
          (state_attr("media_player.denon_avr", "volume_level") | default(None)) or 1.0,
          (states('input_number.stereo_volume_max') | float / 100.0)
        ) }}
```

This automation _usually_ kicks in and lowers the volume quickly enough to simply give everyone nearby a good scare at most.

It's not a great solution, but hopefully it can help protect people's ears, equipment, and relationships with their neighbors until a proper solution can hopefully be developed.
