### DISCUSSION TITLE
Automatic Editing of MASS Playlists to Automatically Include New Songs

### DISCUSSION THREAD

**Discussion by homeauto-git** [music-assistant/support#3308] [Show and tell]
This guide outlines how to use Music Assistant and Home Assistant to edit a playlist. Using a custom Python script executed via a Shell Command for automatic inclusion of new songs. 

## Link to Yt-dlp Addon

- [ ] Work in Progress

## Prerequisites

- **Shell Command** and **folder watcher** integration enabled
- Basic knowledge of YAML and Home Assistant configuration files

---

## Step 1: Create a Playlist in Music Assistant

1. **Open Music Assistant**:
   - Navigate to the Music Assistant integration in your Home Assistant dashboard.

2. **Add Tracks to Playlist**:
   - Search for tracks or browse your library, then add them to a new or existing playlist.

3. **Save Your Playlist**:
   - Give your playlist a name, such as `My Favorite Tracks`.

   The playlist is now available in Music Assistant's library.

---

### 2.1 Enable Shell Command in Home Assistant

1. Open your `configuration.yaml` file.
2. Add the following under `shell_command`:

   ```yaml
   shell_command:
     create_playlist: "python3 /config/scripts/create_playlist.py {{ audio_folder }} {{ m3u_file }}"
   ```
3. Restart Home Assistant to apply the changes.

### 2.2 Add the Python Script

1. Create a folder named `scripts` in the `/config` directory of your Home Assistant setup.
2. Create a file named `create_playlist.py` in the `/config/scripts/` folder.
3. Paste the following Python code into the file:

   ```python
   import os
   import sys

   # Paths from arguments
   audio_folder = sys.argv[1]
   m3u_file = sys.argv[2]

   if not os.path.exists(audio_folder):
       print(f"Error: Folder '{audio_folder}' does not exist.")
       sys.exit(1)

   # Create the M3U file
   with open(m3u_file, "w", encoding="utf-8") as file:
       file.write("#EXTM3U\n\n")
       for filename in sorted(os.listdir(audio_folder)):
           if filename.lower().endswith((".mp3", ".wav", ".flac", ".aac", ".ogg")):
               relative_path = os.path.relpath(
                   os.path.join(audio_folder, filename),
                   os.path.dirname(m3u_file),
               )
               file.write(f"#EXTINF:0,{os.path.splitext(filename)[0]}\n")
               file.write(f"{relative_path}\n\n")

   print(f"Playlist saved to {m3u_file}")
   ```

### 2.3 Configure Media Folder

Ensure your audio files are located in a media folder accessible by Home Assistant, e.g., `/media/audio`. Update the paths in the Shell Command service accordingly.

---

## Step 3: Call the Shell Command

1. Go to **Developer Tools > Services** in Home Assistant.
2. Select `shell_command.create_playlist`.
3. **Call Service**.

   ```yaml
   action: shell_command.create_playlist
   data:
     audio_folder: /media/audio
     m3u_file: /media/like.m3u
   ```

The script will generate an M3U file in the specified location. You can confirm the operation by checking the `/media/like.m3u` file.

---

### 4.1 Enable Folder Watcher Integration

1. Add the following to your `Integrations Menu` to set up Folder Watcher:
  
https://www.home-assistant.io/integrations/folder_watcher
  
2. Add the folder that you want to watch for changes, e.g., `/media/audio`.
 
### 4.2 Create an Automation to Trigger the Shell Command

1. Go to **Settings > Automations & Scenes** and create a new automation.
2. Use the following YAML configuration:

   ```yaml
   alias: Update Playlist on File Addition
   description: >-
     Automatically update the playlist when a new file is added to the audio
     folder.
   triggers:
     - trigger: state
       entity_id:
         - event.folder_watcher_media_audio
   conditions: []
   actions:
     - data:
         audio_folder: /media/audio
         m3u_file: /media/like.m3u
       action: shell_command.create_playlist
   mode: single
   ```

4. Save the automation and enable it.

### 4.3 Test the Automation

1. Add a new audio file to the `/media/audio` folder.
2. Check the `/media/like.m3u` file to verify that the playlist has been updated.

---

## Additional Notes

- **Trigger Limitations**: The Folder Watcher integration triggers on file creation events, which means it should handle all new files, but ensure the folder path is correctly set.
- **Debugging**: If the automation doesn’t work, check the logs to see if the Folder Watcher event fired and whether the Shell Command ran successfully.
- I am new to programming and I came up with this idea when I tried manually editing the `.m3u` file and it worked. I wanted to keep it exactly how Music Assistant made it but I do not know a command to get out the length of the audio file in seconds like it does but setting to `0` seems to work
Feel free to share, customize, and expand this guide! 🚀

---

**Disclaimer**

This guide is provided for informational purposes only. Use it responsibly and ensure compliance with all applicable copyright laws. You are solely responsible for ensuring that any audio files used with this system are legally obtained and that you have the rights to download, store, and play them. The author of this guide is not responsible for any misuse or legal issues arising from its implementation.
