### DISCUSSION TITLE
Start playback at the current volume level

### DISCUSSION THREAD

**Discussion by frank2604** [music-assistant/support#3322] [Q&A] [answered]
What do I want to do?

When a motion sensor detects that I have entered a room, it should start playback. **The volume should fade in.**

Implementation (automation):

```
          - action: media_player.turn_on
            target:
              device_id: fb033115c60f4c3f15175423cde16462
            data: {}
          - action: media_player.volume_set
            target:
              device_id: fb033115c60f4c3f15175423cde16462
            data:
              volume_level: 0.01
          - action: music_assistant.play_media
            target:
              device_id: fb033115c60f4c3f15175423cde16462
            data:
              media_id: Chilltrax
              media_type: radio
          - delay:
              hours: 0
              minutes: 0
              seconds: 3
              milliseconds: 0
          - alias: Lautstärke schrittweise erhöhen
            repeat:
              sequence:
                - target:
                    entity_id: media_player.badezimmer_music_assistant_lautsprecher
                  data:
                    volume_level: "{{ (repeat.index * 0.01) }}"
                  action: media_player.volume_set
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              until:
                - condition: template
                  value_template: >-
                    {{ (repeat.index * 0.01) >=
                    (states('input_number.badezimmer_musiccast_lautstarke_standard')
                    | float / 100) }}
```

Problem:

The 'play_media' action always starts with the volume used before the last stop and ignores the volume previously set for this player.

Current workaround:

Before stopping playback and turning off the player, I set the volume to 0.01. Then the next playback starts at 0.01 again. However, this also means that if you start playback manually via MA, the volume on this player is also set to 0.01.

Solution:

It would be great if playback started at the volume level that was last set in the player.
