### DISCUSSION TITLE
German translation for MA custom voice assistant

### DISCUSSION THREAD

**Discussion by jonathanarchergithub** [music-assistant/support#3326] [Show and tell]
Hi, for all interested, I'd like to share my translation of the standard sentence template file for MA specific conversation agent:

```
language: "de"
intents:
  MassPlayMediaOnMediaPlayer:
    data:

      # TARGET AN AREA
      - sentences:
          - "spiele {query};(in | im | bei) [der ]<area> [((im)|(mit)) {radio_mode}] [ ab]"

      # TARGET A NAME
      - sentences:
          - "spiele {query};<on> [der | dem ] [Gerät] {name} [((im)|(mit)) {radio_mode}] [ ab]"
        expansion_rules:
          "on": "(auf|mit|mittels)"
        requires_context:
          domain: "media_player"

      # TARGET AN AREA AND A NAME
      - sentences:
          - "spiele {query};(in | im | bei) [der | dem  ]<area> <on> [der | dem ] [Gerät] {name} [((im)|(mit)) {radio_mode}] [ ab]"
        expansion_rules:
           "on": "(auf|mit|mittels)"
        requires_context:
          domain: "media_player"
          
lists:
  query:
    wildcard: true
  radio_mode:
    values:
      - "radio mode"

```

I just dropped the option "Listen to", since it would comlicate things (grammatically) and doesn't seem obvious as a command anyway.
