### DISCUSSION TITLE
"artist" vs "albumartist" file tags

### DISCUSSION THREAD

**Discussion by YackyYam** [music-assistant/support#3357] [Q&A] [answered]
I've been getting my HA server configured more how I like it and I installed Music Assistant.  (Love this addon) My question is when I pointed MA at my music library MA found everything but it is using the "artist" tag rather than the "albumartist" tag.  Been using [beets](https://beets.io/) to clean up the tags of my file and because MA uses the "artist" tag the list of artists when you click on the artists tab is polluted with the artists and "artists + colab".   For example....each entry that is not just "Aim" is it's own artist.  Aim feat. AG, Aim feat. QBall & Curt Cazal, Aim feat. Kate Rogers.  Wouldn't it be better if MA pulled the artist name from the albumartist field?  Would make imported collections cleaner and people would be able to keep the track artists.   Wondering what other people think. 

Edit: This would also fix issues with albums with Various Artists.  The albumartist would be "Various Artists" then each track would have the ACTUAL name of the artist of that track.  

Edit 2: Moby is another one with issues.  See second code block for example of the tags output from beets. 

```
album: Cold Water Music
albumartist: Aim
artist: Aim
id: 123
---
album: Cold Water Music
albumartist: Aim
artist: Aim
id: 125
---
album: Cold Water Music
albumartist: Aim
artist: Aim
id: 126
---
album: Cold Water Music
albumartist: Aim
artist: Aim
id: 127
---
album: Cold Water Music
albumartist: Aim
artist: Aim feat. AG
id: 124
---
album: Cold Water Music
albumartist: Aim
artist: Aim feat. QBall & Curt Cazal
id: 119
---
album: Cold Water Music
albumartist: Aim
artist: Aim feat. Kate Rogers
id: 120
---
album: Cold Water Music
albumartist: Aim
artist: Aim feat. YZ
id: 122
---
album: Cold Water Music
albumartist: Aim
artist: Aim feat. YZ
id: 128
```

```
/mnt/vault/Music/Moby/always centered at night/06 precious mind.flac
acoustid_fingerprint: 
         acoustid_id: 
               album: always centered at night
         albumartist: Moby
  albumartist_credit: Moby
    albumartist_sort: Moby
       albumdisambig: 
         albumstatus: Official
           albumtype: a
          albumtypes: a; l; b; u; m
            arranger: 
                 art: True
              artist: Moby & India Carney
       artist_credit: Moby & India Carney
         artist_sort: Moby & Carney, India
                asin: 
            bitdepth: 16
             bitrate: 935530
        bitrate_mode: 
                 bpm: 0
         catalognums: 
            channels: 2
            comments: 
                comp: False
            composer: 
       composer_sort: 
             country: DZ
                date: 2024-06-14
                 day: 14
                disc: 1
           disctitle: 
           disctotal: 1
             encoder: 
        encoder_info: 
    encoder_settings: 
              format: FLAC
               genre: Pop
              genres: Pop
            grouping: 
                isrc: GB3AD2400011
               label: always centered at night
            language: eng
           languages: eng
              length: 294.6573469387755
            lyricist: 
              lyrics: 
    mb_albumartistid: 8970d868-0723-483b-a75b-51088913d3d4
   mb_albumartistids: 8970d868-0723-483b-a75b-51088913d3d4
          mb_albumid: 2508e62a-8ae2-47ff-a944-9ca7ffee0b4b
         mb_artistid: 8970d868-0723-483b-a75b-51088913d3d4
        mb_artistids: 8970d868-0723-483b-a75b-51088913d3d4
   mb_releasegroupid: 441f6c07-3baf-438f-9c26-015e587cfc85
   mb_releasetrackid: f8771b7b-25cd-43a4-a180-d96d5037759e
          mb_trackid: 039d1c18-30e2-4d2f-b659-7509f8809230
           mb_workid: cb13106c-0a55-4e05-8acc-032b6cb32b7e
               media: Digital Media
               month: 6
       original_date: 2024-06-14
        original_day: 14
      original_month: 6
       original_year: 2024
          samplerate: 44100
              script: Latn
               title: precious mind
               track: 6
          tracktotal: 13
                year: 2024
```
