### DISCUSSION TITLE
White noise / Green noise / Ocean sounds / Ambient loop tracks

### DISCUSSION THREAD

**Discussion by bagobones** [music-assistant/support#3361] [Q&A]
Maybe as a local library function or some sort of flag it would be nice to have a way to specific a track as a loop that once started just keeps playing.

In particular I am looking to replace native functions you find on devices like the google mini where you just say "Play white noise" and away it goes all night.

Given the existing work on the play intents I think this would work well in Music assistant. Could also be useful for certain types of music as well for parties etc to have a looping playlist of some form.

If there is a way to specify looping a track with intents I am not aware of that might just work as well if I could bind a specific track and looping to the command.

**Comment by OzGav** [comment]
Use the track repeat function?

**Reply by bagobones** [reply]
> Use the track repeat function?

How would I be able to use that with a home assistant intent? IE I want "PLAY white noise" to play the whitenoise.mp3 on loop or a track in plex on loop?

**Reply by OzGav** [reply]
You need an intent to set the repeat mode as well as the play command. This is covered in the docs

**Reply by bagobones** [reply]
So I need to call get library and use the repeat item under sequence?

https://music-assistant.io/faq/how-to/?h=repeat#play-a-random-item

**Reply by OzGav** [reply]
No you already know the track title so you don’t need get library. Look at the first item in the page you linked

**Reply by bagobones** [reply]
> No you already know the track title so you don’t need get library. Look at the first item in the page you linked

The word repeat does not appear anywhere else on that page.. what exactly are you talking about? Just wrapping the music assistant play action in the home assistant automation repeat function?

**Reply by OzGav** [reply]
Your question is about voice intents. The first entry on that page is about voice intents.

**Reply by bagobones** [reply]
> You need an intent to set the repeat mode as well as the play command. This is covered in the docs

The Repeat part is the part I am having issues with..

So do I need to call Play, then "media_player.repeat_set" in a sequence?

Feels like if the play service had a enqueue option of "loop" this would be as simple as a small modification to the existing custom sentences for the provided HACS play intent.

**Reply by bagobones** [reply]
So part way there after figuring out that HA has a media_player.repeat_set and that intent scripts allow sequence blocks


Now I just need to fix the area / entity targeting instead of hard coding it.

```
##intent_script:
  MassPlayWhiteNoise:  # Intent type
    action:
      sequence:
        - action: mass.play_media
          data:
            media_id: White Noise 01
            media_type: track
            enqueue: replace
          target:
            entity_id: media_player.office_speaker
        - action: media_player.repeat_set
          data:
            repeat: all
          target:
            entity_id: media_player.office_speaker
    speech:
      text: "Sweet dreams"
```

```
language: "en"
intents:
  MassPlayWhiteNoise:
    data:

      # TARGET AN AREA
      - sentences:
          - "<play> White Noise in [the ]<area> [((with)|(using)) {radio_mode}]"
        expansion_rules:
          play: "((play)|(listen to))"
          track: "[the ](track|song)"
          radio_station: "[the ]((radio station)|(radio)|(station))"

      # TARGET A NAME
      - sentences:
          - "<play> White Noise <on> [the ]{name} [<player_devices>] [((with)|(using)) {radio_mode}]"
        expansion_rules:
          play: "((play)|(listen to))"
          player_devices: "((speaker)|([media] player))"
          "on": "(on|using)"
          radio_station: "[the ]((radio station)|(radio)|(station))"
        requires_context:
          domain: "media_player"

      # TARGET AN AREA AND A NAME
      - sentences:
          - "<play> White Noise in [the ]<area> <on> [the ]{name} [<player_devices>][((with)|(using)) {radio_mode}]"
        expansion_rules:
          play: "((play)|(listen to))"
          player_devices: "((speaker)|([media] player))"
          "on": "(on|using)"
          playlist: "[the ]playlist"
          radio_station: "[the ]((radio station)|(radio)|(station))"

      # CONTEXT AWARNESS
      - sentences:
          - "<play> White Noise [((with)|(using)) {radio_mode}]"
        expansion_rules:
          play: "((play)|(listen to))"
          playlist: "[the ]playlist"
          radio_station: "[the ]((radio station)|(radio)|(station))"
        requires_context:
          area:
            slot: true
lists:
  artist:
    wildcard: true
  album:
    wildcard: true
  track:
    wildcard: true
  playlist:
    wildcard: true
  radio:
    wildcard: true
  radio_mode:
    values:
      - "radio mode"
```
