### DISCUSSION TITLE
Randomise playlist via button

### DISCUSSION THREAD

**Discussion by msknight** [music-assistant/support#3375] [Q&A] [answered]
I'm getting there, just one final hurdle to get over... randomisation of the playlist.

I've tried a few options like order-by in the data: but obviously that's not the way to do it.

I've been reading some code here - https://music-assistant.io/faq/how-to/#add-items-to-the-queue-via-a-script-or-automation but I've been having a hard time getting that into a tap_action and also converting the "queue of tracks" to a playlist. I guess I just haven't got the hang of the syntax yet... and it is so unforgiving on spaces.

Grateful for advice please. 

Code so far...

```
show_name: true
show_icon: true
type: button
tap_action:
  action: perform-action
  perform_action: music_assistant.play_media
  target:
    device_id: 28997742cf314ff142f7af99b3c68430
  data:
    media_type: playlist
    media_id: Michelle
entity: input_button.music_button
grid_options:
  columns: 3
  rows: 2
name: My AK-70 List
icon: mdi:record-circle
```

**Comment by OzGav** [comment]
I’m not sure what you want to do. If you want to play a playlist in a random order then enable shuffle on the queue before adding the playlist. 

If you want to choose a random playlist then look just below the section of the docs you linked to above.

**Reply by msknight** [reply]
I did try shuffle under the data: but it said...
Failed to perform the action music_assistant/play_media. extra keys not allowed @ data['shuffle']

```
  target:
    device_id: 28997742cf314ff142f7af99b3c68430
  data:
    shuffle: true
    media_type: playlist
    media_id: Michelle
    order_by: random
```
