### DISCUSSION TITLE
Dynamically choose player for announcements

### DISCUSSION THREAD

**Discussion by Shogun1978** [music-assistant/support#3427] [Feature requests and ideas]
Hello everybody,
currently I am using the MusicServer4Home server (https://music-server.net/). I am planing to move to music assistant. Right now, I have two issues/use cases I can't realize with music assistant:

1. When I pause a track, do fast forward/backward via the time bar or play an announcement, the music track starts from the beginning.
2. I want to play announcements based on the occupied rooms.

In my home I have presence detectors for every room. In the ceilings, there are speakers that are controlled bei Home Assistant (currently MusicServer4Home which is running a LMS beyond). In the "Music Assistant: Play announcement" action, I can select the rooms, but this can't be done dynamically. Is there way to realize this?

In the MusicServer4Home, all players have a number and you can trigger the announcement based on the numbers. I build a template sensor the rooms/zones:

```
{{ ['1',
  iif(is_state('binary_sensor.buro_og_anwesenheit', 'on'), ',2', ''),
  iif(is_state('binary_sensor.bar_anwesenheit', 'on'), ',3', '')
  ] | join}}
```

Room 1 will play always (livingroom), office and bar just if occupied. The announcement will be played by a rest command:

```
doorbell:
  url: "http://10.10.11.230/event/event.php?type=ring&cat=bell&file={{ringtone}}&zone={{internal}}&zone_ext={{external}}&vol={{volume}}&autoplay=1&overlay=1&overlay_drop={{volume}}"
```

I will give volume of the announcement, ringtone, zones (which are the occupied rooms) as variables to the rest command. Volume and ringtone can be passed to the "play announcement" of the music assistant instance. But players can't - at least I didn't get it working.

Might be a good thing if you can add something similar to music assistant.

Regards,
Harald

**Comment by OzGav** [comment]
Your point 1 is an open issue https://github.com/music-assistant/support/issues/3274

For everything else they are generally questions for HA but I will check if there is any limitation with templating in the MA actions

**Reply by Shogun1978** [reply]
Thanks for taking a look! I tried to send the players as variable to the action:

```
action: music_assistant.play_announcement
data:
  url: http://someremotesite.com/doorbell.mp3
target:
  entity_id: {{ playerids }}
```

But it didn't work, so I was not really sure, if this is caused by MA or HA ;) It might be an issue, as the entity_id seems to require a list with - in front of each player. Maybe a general "announcement" flag might also be an option. Just as an idea.

**Reply by OzGav** [reply]
Have you tried with quotes around the template? Have you tried the situation where playerids only have a single entity_id? What errors do you have in the HA log? What does the automation trace show you?

**Reply by Shogun1978** [reply]
I tried with "" as it will not generate a valid entry at all in the UI. Here is my "room sensor" that should gather the rooms occupied (it's just a test, so only two rooms):

```
{{ ["- media_player.wohnen_2",
  iif(is_state('binary_sensor.buro_og_anwesenheit', 'on'), '- media_player.officeog', ''),
  ] | join}}
```

The sensor delivers this:

```
- media_player.wohnen_2 - media_player.officeog
```

To play the announcement, I use a button:

```
type: custom:mushroom-template-card
primary: Test announcement
secondary: ""
tap_action:
  action: perform-action
  perform_action: music_assistant.play_announcement
  target:
    entity_id: "{{ states('sensor.ma_roomsensor'}}"
  data:
    url: https://command.app.itprior.de/local/sound/waschmaschine.mp3
icon: mdi:speaker
```

Here the error message:
```
[140444544305040] Error handling message: not a valid value for dictionary value @ data['target']['entity_id']. Got "{{ states('sensor.ma_roomsensor'}}" (invalid_format) Harald from 192.168.117.188 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
```

Seems like the entities simply not generated that the play announcement action can handle it.

**Reply by OzGav** [reply]
If you look at the sensor that is not going to be valid for that key. Have a look at this https://community.home-assistant.io/t/template-using-multiple-entity-ids/161171

**Reply by Shogun1978** [reply]
I will take a look tomorrow. Maybe there is already a solution for that :)

**Reply by Shogun1978** [reply]
I managed to create a dynamic sensor and play an announce based on the occupancy of the rooms. First I build a template sensor. This is the template:

```
{{ [ "media_player.wohnen_2",
  iif(is_state('binary_sensor.buro_og_anwesenheit', 'on'), ',media_player.officeog') ] | join}}
```

Based on a binary sensor from KNX presence detectors, I build a dynamic sensor as base for the target in the announcement. Then I created an action in an automation:

```
action: music_assistant.play_announcement
data:
  url: https://mydomain.local/local/sound/sound3.mp3
  announce_volume: 50
target:
  entity_id: "{{states('sensor.ma_roomsensor')}}"
```

What doesn't work - but has nothing to do with MA - is the fact, that I can't use this sensor in a "perform_action" when I build a button. So something like this doesn't work:

```
show_name: true
show_icon: true
type: button
tap_action:
  action: perform-action
  perform_action: music_assistant.play_announcement
  target:
    entity_id: "{{states('sensor.ma_roomsensor')}}"
  data:
    url: https://mydomain.local/local/sound/sound3.mp3
    announce_volume: 50
name: Test
```

The announcement doesn't play syncronized, can I somewhere change an option to achieve this?
