### DISCUSSION TITLE
Problem parsing get_library results

### DISCUSSION THREAD

**Discussion by IdahoSnakeHouse** [music-assistant/support#3435] [Q&A] [answered]
Using the HACS integration, I was able to use the mass.get_library function to get a list of Artists and use them as the options for an Input Select control.  Since moving to the core integration, it appears that the content of the response variable is now different, as my code no longer works.  Before, I was simply doing something like this (don't remember the exact field names of the old version, but along these lines):

`"{{ search_result.artists | map(attribute='name') | list }}"`

I am able to get a response from the library such as the following:

`{'items': [{'media_type': <MediaType.ARTIST: 'artist'>, 'uri': 'library://artist/249', 'name': 'A Perfect Circle', 'version': '', 'image': '[https://i.scdn.co/image/ab6761610000e5eb41472573351dfea479a4ffba'}]](https://i.scdn.co/image/ab6761610000e5eb41472573351dfea479a4ffba'%7D%5D), 'limit': 1, 'offset': 0, 'order_by': 'name', 'media_type': <MediaType.ARTIST: 'artist'>}`

I recognize that the response now includes the results in addition to the search parameters.  I have no problem returning a single value such as the search offset, order, limit, etc. from the response.  However, I've tried all sorts of ways to get a list of Artist names (...items.name, items().name, items[].name, etc.)  Is anyone able to successfully parse the response and get a list of artists, albums, etc.?

**Comment by OzGav** [comment]
I am not sure of the problem. This is a excerpt of my get_library action

```
items:
  - media_type: artist
    uri: library://artist/1186
    name: 10 cc
    version: ""
    image: null
  - media_type: artist
    uri: library://artist/1091
    name: 2 Heads
    version: ""
    image: null
  - media_type: artist
    uri: library://artist/728
    name: 2 in a Room
    version: ""
    image: null
limit: 3
offset: 0
order_by: name
media_type: artist
```

You haven’t provided your full automation but assuming the response variable is  search_results something like this should work although I haven’t tested it.

```
{% set artists = search_results.items | map(attribute='name') | list %}
[{{ artists | join(', ') }}]
```

Which is basically the same as what you were doing?

**Reply by IdahoSnakeHouse** [reply]
Thanks for looking into this.  You are correct, I was using a very similar approach, only I was using a variables block to parse the result stepwise using a couple of variables.  To simplify, I rewrote the script and am just using a persistent notification to debug your suggestion above.

```
alias: "Jukebox: TEST"
sequence:
  - action: music_assistant.get_library
    metadata: {}
    data:
      config_entry_id: 01JEA0TA6TQ468WQYQETCTGJCF
      media_type: artist
      limit: 5
    response_variable: search_results
  - action: persistent_notification.create
    metadata: {}
    data:
      message: >
        {% set message = search_results.items | map(attribute='name') | list %}
        "[{{ message | join(', ') }}]"
icon: mdi:test-tube
```

This gives me the error message: "Failed to perform the action script/jukebox_test. Error rendering data template: TypeError: 'builtin_function_or_method' object is not iterable"

I have worked at this for hours and I keep getting the same error whenever I try to use the list filter (I can remove the join from the code and still get the same error).  I am almost certain the HASS version was providing a different response to the get_library function, as I was able to get a list of artists fairly easily.  I will admit that most of my attempts have been in the vein of using map/join as opposed to using for loops to process each field.

**Reply by OzGav** [reply, marked as answer]
Actually I have seen this before. It exceeds my knowledge to know why but items needs to be in quotes. I do this stuff in the template tester in the dev tools so you can paste the following in and then adjust for the exact output you want

```
{% set search_results = {
  "items": [
    {
      "media_type": "artist",
      "uri": "library://artist/1186",
      "name": "10 cc",
      "version": "",
      "image": null
    },
    {
      "media_type": "artist",
      "uri": "library://artist/1091",
      "name": "2 Heads",
      "version": "",
      "image": null
    },
    {
      "media_type": "artist",
      "uri": "library://artist/728",
      "name": "2 in a Room",
      "version": "",
      "image": null
    }
  ],
  "limit": 3,
  "offset": 0,
  "order_by": "name",
  "media_type": "artist"
} %}

{{ search_results["items"][0].name }}

['{{ search_results["items"] | map(attribute="name") | join("','")}}']

```

output of the above is 

```
10 cc

['10 cc','2 Heads','2 in a Room']
```

**Reply by IdahoSnakeHouse** [reply]
Thank you!  The quotes around items fixed it.  The following script succeeds in placing a list of artists into the input select.

```
alias: "Jukebox: Artist Search"
sequence:
  - alias: Search Music Assistant library for Artist
    action: music_assistant.get_library
    data:
      media_type: artist
      config_entry_id: 01JEA0TA6TQ468WQYQETCTGJCF
    response_variable: search_results
  - variables:
      var_artists: "{{ search_results['items'] | map(attribute='name') | list }}"
  - action: input_select.set_options
    data:
      options: "{{ var_artists }}"
    target:
      entity_id: input_select.mass_search_artist
    alias: Return Artist list to dropdown options
description: Searches Music Assistant library by Artist name and returns a list of albums
icon: mdi:tag-search
```
