### DISCUSSION TITLE
Continuous playing first numbers

### DISCUSSION THREAD

**Discussion by MarcelD1973** [music-assistant/support#3439] [Q&A] [answered]
Hi all,

Does anyone know what might be going wrong here?

Recently, I’ve noticed that Music Assistant starts looping after playing around 9 tracks. I have an automation set to start playing at 8:30, and it begins as expected. However, once it finishes playing the initial set of tracks, it repeats the same ones instead of continuing with the queue. This issue isn’t specific to one playlist—it happens with any playlist I use.

I can manually skip to the next track, and it will play more songs from the queue, but after a while, the issue starts again.

I’ve attached screenshots of my setup and automation for context. 

Any help or insight would be greatly appreciated!

HomeAssistant: 
Core: 2025.1.2
Supervisor 2024.12.3
Operating System 14.1
Frontend: 20250109.0

Music Assistant: latest version. 

![IMG_1158](https://github.com/user-attachments/assets/8f4de956-f00a-4cee-8d44-3e213b212540)
![IMG_1159](https://github.com/user-attachments/assets/a094f16f-d416-4675-9387-a42b4d9a6b96)
![IMG_1160](https://github.com/user-attachments/assets/e568ff6a-4dbe-4a6b-a1d8-838b67d08e03)

**Comment by OzGav** [comment]
What happens if you manually start playing a playlist?

**Comment by MarcelD1973** [comment]
Well, this is strange. In all the playlists today, both via automation and manually, it plays just fine. Even when played and queued, it displays correctly, as you can see on the attached image. 

It seems like this playlist just doesn’t want to play properly.

![IMG_1167](https://github.com/user-attachments/assets/9bad5808-f80e-40ab-9591-23c379d7bc12)

**Reply by OzGav** [reply]
Ok so if you have narrowed it down to one specific playlist then look carefully at that. What is unique about it. Are there manually uploaded tracks? What provider is it? Duplicate the playlist and remove the ninth track, does that fix it? Is there anything in the logs? Look again at your automation and all other automations you have.

**Comment by bart-jansen** [comment]
![image](https://github.com/user-attachments/assets/6f8ef676-1104-4135-83db-0ec4819957af)
Same issue here on pretty much all my (custom) Spotify playlists that don't seem to skip to the next song and continuously 'play' and get stuck on a song.

The case above is also after 9 (or I guess 10) played songs, will report back to see if it always get stuck after 10 songs.

I start my playlists through Home Assistant, using e.g. :
```yaml
action: music_assistant.play_media
data:
  media_id: "library://playlist/44"
  enqueue: replace
target:
  entity_id: media_player.woonkamergroup
```

**Reply by OzGav** [reply]
I play many Spotify playlists and don’t see this so we need you to keep testing. What you can do is select all the songs in the playlist and add them to a new playlist but use the MA built in option. Then see if the same problem occurs then.

**Comment by MarcelD1973** [comment]
Allright @OzGav I discovered that starting by hand a playlist from the MA screen, it will play all the numbers. 
when starting a playlist from an automation of homeassistant, it get stuck. Sometimes at song number nine, sometimes already at the second.

**Comment by bart-jansen** [comment]
For me it seems to be a combination of:
- using homeassistant: `music_assistant.play_media`
- spotify album/playlist
- targeting a playergroup with one or more Airplay players

To reproduce the issue, you can start this public spotify album with very short songs (10-30secs each, therefore failing fast) in home assistant:
```yaml
action: music_assistant.play_media
data:
  media_id: https://open.spotify.com/album/280p7RtY0tVouTaRlTM3CE?si=FTOvMkw3RoOtwfUi7S6Qsw
  enqueue: replace
target:
  entity_id: media_player.werkkamergroup #replace with your playgroup player
```
