### DISCUSSION TITLE
Load playlist and shuffle in script

### DISCUSSION THREAD

**Discussion by msknight** [music-assistant/support#3446] [Q&A] [answered]
I'm going slightly bonkers trying to code this but I'm trying to make a script in HA to load a playlist and shuffle it. There are plenty of examples for spotify playlists, but not local playlists.

The playlist is "Michelle" and the player is media_player.music_player_daemon.

```
sequence:
  - perform_action: music_assistant.play_media
      target:
        device_id: 28997742cf314ff142f7af99b3c68430
      data:
        media_type: playlist
        media_id: Michelle
  - entity_id: media_player.music_player_daemon
    data:
      shuffle: true
    action: media_player.shuffle_set
alias: AK70 Shuffled
description: ""
```

**Comment by msknight** [comment]
I've got the playlist sorted, I'm now having problems with the shuffle.
```
alias: AK70 Shuffled
sequence:
  - target:
      entity_id: media_player.music_player_daemon
    data:
      media_id: Michelle
      media_type: playlist
      enqueue: play
      radio_mode: true
    action: music_assistant.play_media
  - target:
      entity_id: media_player.music_player_daemon
    data:
      shuffle: true
    action: music_assistant.shuffle
```

**Comment by msknight** [comment]
I'm getting further. Shuffling appears to be happening but nothing is playing.

```
alias: AK70 Shuffled
sequence:
  - target:
      entity_id: media_player.music_player_daemon
    data:
      media_id: Michelle
      media_type: playlist
      enqueue: replace
    action: music_assistant.play_media
  - action: media_player.shuffle_set
    target:
      entity_id: media_player.music_player_daemon
    data:
      shuffle: true
```

**Comment by msknight** [comment, marked as answer]
Done it....
```
alias: AK70 Shuffled
sequence:
  - target:
      device_id: 28997742cf314ff142f7af99b3c68430
    data:
      media_id: Michelle
      media_type: playlist
    action: music_assistant.play_media
  - action: media_player.shuffle_set
    data:
      shuffle: true
    target:
      device_id: 28997742cf314ff142f7af99b3c68430
  - action: media_player.media_play
    data: {}
    target:
      device_id: 28997742cf314ff142f7af99b3c68430
```

**Reply by dep** [reply]
Bless you for this. <3

**Reply by appel** [reply]
Thanks friend, worked like a charm! Note that you can substitute `device_id` for `entity_id` and it still works:

```
alias: "[MA] Play Poolside in Plex"
sequence:
  - action: music_assistant.play_media
    target:
      entity_id: media_player.ma_downstairs
    data:
      media_id: Poolside
      media_type: playlist
      enqueue: replace
  - action: media_player.shuffle_set
    data:
      shuffle: true
    target:
      entity_id: media_player.ma_downstairs
  - action: media_player.media_play
    data: {}
    target:
      entity_id: media_player.ma_downstairs
```
