### DISCUSSION TITLE
Configurable idle timeout - fixes not being able to resume via voice command

### DISCUSSION THREAD

**Discussion by Davis8483** [music-assistant/support#3491] [Feature requests and ideas]
After 30 seconds of being paused, media players will switch to an idle state. This makes it impossible to unpause via a voice command as the player must be in a paused state to allow for the unpause intent to run. Instead, it would be nice for the timeout to be configurable. 0 for never and anything above that would be in seconds.

![image](https://github.com/user-attachments/assets/674ed5df-612f-4d7a-9dd6-a56c68efb242)

**Comment by eric10k93** [comment]
I just ran into this issue, but it doesn't appear to be JUST related to Music Assistant.  I am using Google Cast devices and they have a similar timeout.  I'm not sure just changing the timeout in MA would solve the problem.

**Reply by Davis8483** [reply]
good to know, I'll close this issue and reopen the one in core

**Comment by Davis8483** [comment]
Reopened discussion in https://github.com/home-assistant/core/issues/136135

**Comment by BjornPython** [comment]
any fix or temporary work around for this?

**Reply by Davis8483** [reply]
@BjornPython 
I was able to work around this by providing a script for the LLM to use instead

```yaml
sequence:
  - action: media_player.media_play
    metadata: {}
    data: {}
    target:
      entity_id: "{{ media_player_id }}"
fields:
  media_player_id:
    selector:
      entity: {}
    name: Media Player Id
    description: >-
      The entity id of the media player you would like to resume. Ex:
      media_player.living_room_speaker
alias: Unpause Media Player
description: >-
  Ignore the built in HassMediaUnpause intent as it is broken and use this
  script instead.

```
<sup>posted on both threads, sorry for the double reply</sup>
