### DISCUSSION TITLE
Add an option to get_library (or maybe an action "get_library_tracks"?) to get track information by providing an playlist / album id.

### DISCUSSION THREAD

**Discussion by kuchenundkakao** [music-assistant/support#3561] [Feature requests and ideas]
Hi,

the get_library action is pretty amazing, but it lacks a parameter / option to select a specific album / playlist / whatever to get its results from. 

For instance: I'm trying to set up an automation to get the tracks from within a specific album, take a random one, and play that on my speaker. Right now, i can only use the play_media action to play the complete album. That seems a bit lacking...

Or is there already a hidden option that i don't know about?

**Comment by OzGav** [comment]
There is a HA action `media_player.browse_media` that can be used here. Any Music Assistant integration provided media player entity can be used. The media_content_id can be obtained from the `music_assistant.get_library` or `music_assistant.get_queue` actions

```
action: media_player.browse_media
target:
  entity_id: media_player.airplay_pcp_group
data:
  media_content_type: music
  media_content_id: library://album/16
```

If the above is used in an automation or script the returned data can be used in a response variable and then a template used to grab a random one as follows:

```
{% set tracks = action_response["media_player.airplay_pcp_group"]["children"] | map(attribute='media_content_id') | list %}
{{ tracks | random }}
```

This will result in an output such as `library://track/99`
