### DISCUSSION TITLE
flow_mode unexpected type for Chromecast

### DISCUSSION THREAD

**Discussion by Swimmer71** [music-assistant/support#3584] [Q&A] [answered]
Hi, I don't know since when, maybe since latest update to 2.4.0.rc2 I can't change anything in the setting for the chromecast players quiting when saving always with folowing message:
![Screenshot 20250218-152252](https://github.com/user-attachments/assets/f91ad566-66cb-4cba-8291-985f6e0c95b3)

I just wanted to turn of flow_mode...but not possible. Even when I don't change anything and just click to "save" the message appears.

**Comment by OzGav** [comment, marked as answer]
Will be fixed in rc3

**Reply by marcelveldt** [reply]
correction: rc4

**Comment by Swimmer71** [comment]
Another issue inRC2:
I use chromecast entity created in MA (media_player.chromecast_dg_2).
I check the displayed cover of track on TV AND in HA app using minimediaplayer.
On TV cover changes every track change but on HA App it displays the cover from the 1st track and didn't get updated after next track.

When I use the chromecast entity for the same chromecast but from the cast integration (media_player.chromecast_dg_3), the cover is changed and displayed correctly.

**Reply by OzGav** [reply]
I can’t reproduce that using a Google Mini or a  Sony TV with RC4

**Comment by Swimmer71** [comment]
With RC4 it is different now:
Configuration of Chromecast is working now! Thanks!

issues with cover:
it works now in minimediaplayer but only with Chromecast entity created by ~~HA~~ MA, and NOT when playing a folder with e.g. "media_id: filesystem_smb--xxxxxxxx://folder/Music/Hits"

AND: Now the covers are never displayed in the Chromecast entities created by Cast or UniversalMediaPlayer Integration at all.
(Flow_mode is off)

**Reply by OzGav** [reply]
Did you mean MA in the first situation?

**Comment by Swimmer71** [comment]
Ah yes, sorry. I mean the entity created by MA (not HA)

**Comment by Swimmer71** [comment]
still problems with RC5 and RC6 is following situation:
(btw it worked (except for folders) before RC2 or so....)

Playing in MiniMediaPlayer with entity of UniversalMediaPlayer (UMP) and MA-Integration is now same behavior, but:
Playing....

Folders: no covers (I play folder with "media_id: filesystem_smb://folder/Music/Hits")
Playlist: no covers
Album: only album cover (cover.jpg) but not individual covers of tracks
Radio: shows covers correct

**Comment by Swimmer71** [comment]
Here my UMP consisting out of MA-Entity and AV receiver Onkyo:
```
`media_player:
    platform: universal
    name: Chromecast WZ + Onkyo
    unique_id: media_player.chromecast_wz_onkyo
    attributes:
      state: media_player.chromecast_wz_ma
      volume_level: media_player.tx_nr616|volume_level
      is_volume_muted: media_player.tx_nr616|is_volume_muted
      source: media_player.tx_nr616|source
      source_list: media_player.tx_nr616|source_list
    device_class: speaker
    children:
      - media_player.chromecast_wz_ma
    commands:
      turn_on:
        action: media_player.turn_on
        data:
          entity_id: media_player.chromecast_wz_ma
      turn_off:
        action: media_player.turn_off
        data:
          entity_id: media_player.chromecast_wz_ma
      volume_mute:
        action: media_player.volume_mute
        data:
          entity_id: media_player.tx_nr616
          is_volume_muted: "{{is_volume_muted}}"
      volume_up:
        action: media_player.volume_up
        data:
          entity_id: media_player.tx_nr616
      volume_down:
        action: media_player.volume_down
        data:
          entity_id: media_player.tx_nr616
      volume_set:
        action: media_player.volume_set
        data:
          entity_id: media_player.tx_nr616
          volume_level: "{{volume_level}}"
      select_source:
        action: media_player.select_source
        data:
          entity_id: media_player.tx_nr616
          source: "{{source}}"`
```


And here my MiniMediaPlayer:

```
type: custom:mini-media-player
entity: media_player.chromecast_wz_onkyo
artwork: cover
name: Chromecast WZ MA + Onkyo (UMP)
source: full
info: scroll
max_volume: 76
min_volume: 10
volume_step: 2
volume_stateless: true
toggle_power: true
hide:
  volume: false
  name: false
  power_state: false
  icon_state: false
  power: false
  volume_level: false
  play_pause: false
  source: false
  shuffle: false
  repeat: false
  runtime: false
  runtime_remaining: false
shortcuts:
  columns: 3
  hide_when_off: 0
  buttons:
    - data:
        entity_id: media_player.chromecast_wz_ma
        media_type: radio
        media_id: lounge.fm
      id: music_assistant.play_media
      type: service
      name: null
      cover: /local/bilder/loungefm.jpg
    - data:
        entity_id: media_player.chromecast_wz_ma
        media_type: radio
        media_id: arabella relax
      id: music_assistant.play_media
      type: service
      name: null
      cover: /local/bilder/arabella_relax.jpg
    - data:
        entity_id: media_player.chromecast_wz_ma
        media_type: radio
        media_id: ORF Radio Wien
      id: music_assistant.play_media
      type: service
      name: null
      cover: /local/bilder/radiowien.jpg
    - data:
        entity_id: media_player.chromecast_wz_ma
        enqueue: replace
        media_id: filesystem_smb--vJHsvz9w://folder/Hits-neu
      id: music_assistant.play_media
      type: service
      name: Folder
      icon: null
    - data:
        entity_id: media_player.chromecast_wz_ma
        media_type: playlist
        media_id: Hits
      id: music_assistant.play_media
      type: service
      name: Playlist
      icon: null
    - data:
        entity_id: media_player.chromecast_wz_ma
        media_type: album
        media_id: Dani
      id: music_assistant.play_media
      type: service
      name: Album
      icon: null

```
