### DISCUSSION TITLE
Adding one episode of a podcast to the queue

### DISCUSSION THREAD

**Discussion by tom-parkinson** [music-assistant/support#3668] [Q&A] [answered]
Thanks for a great add-on! I'm just playing around with the newly added podcast functionality (via ABS). I have what I think is a simple question - is there a way to add just the latest episode of a podcast to the queue? 
I'm currently using `music_assistant.get_library` which correctly finds the podcast I'm after. I then pass that `response_variable` to `music_assistant.play_media` using a media_id template of `"{{ latest_podcast['items'][0]['uri'] }}"`. This all works fine, but it passes the URI of the whole podcast which adds all episodes to the queue. 
Is there a way to add a single episode of a podcast? If not, could I somehow remove all items from the queue except the first?

**Comment by OzGav** [comment]
@fmunkes

**Comment by fmunkes** [comment, marked as answer]
I think this question is for the HA integration generally - and no, I think this is not possible (yet?), since we can not acquire episodes easily. I only see one, admittedly bad workaround, which is adding the full podcast, then call get_queue, extract the episode uri, and then call play_media again.

Now, in the *specific* case of abs, I came up with the following solution for myself - you will need [RESTful commands](https://www.home-assistant.io/integrations/rest_command/) enabled in HA. The idea is to access the abs api directly. For this, you need your user's token, which you can see in abs as an *admin user* for any user in settings -> users and then click on the user. This token goes in your `secret.yaml` like so:

```yaml
abs_token: Bearer <your very long abs token>
```
Bearer is important, and there is a space between token and Bearer.

Next, setup a restful command like this:
```yaml
rest_command:
  abs_get_item:
    method: GET
    headers:
      authorization: !secret abs_token
    verify_ssl: true
    url: "https://<abs.yourdomain.com>/api/items/{{ item_id }}"
```

Next, we need the provider's instance id in MA - go to MA, and enter the settings dialog of the abs provider. The url should now contain the instance id, something similar to `audiobookshelf--PozRwnYM`. Then we can use this in an HA script like that:

```yaml
play_latest_episode:
  mode: single
  variables:
    mass_player: media_player.<your_media_player>
    mass_abs_id: audiobookshelf--PozRwnYM
  sequence:
    - service: rest_command.abs_get_item
      data:
        item_id: "{{ podcast_id }}"
      response_variable: response
    - variables:
        latest_episode_id: >
          {{ ( response["content"]["media"]["episodes"] | sort(attribute="publishedAt") )[-1]["id"] }}
    - service: music_assistant.play_media
      target:
        entity_id: "{{ mass_player }}"
      data:
        media_id: "{{ mass_abs_id }}://podcast_episode/{{ podcast_id }} {{ latest_episode_id }}"
```

Finally,  you need the abs podcast id - just navigate to your abs instance, and open the specific podcast - the url should look like that `https://<abs.yourdomain.com>/audiobookshelf/item/53b5f0a1-2813-4e8d-be1d-3d2b8f2f794d`. The final part is the id. Then we can call this script like that:
```yaml
action: script.turn_on
data:
  variables:
    podcast_id: 53b5f0a1-2813-4e8d-be1d-3d2b8f2f794d
target:
  entity_id: script.play_latest_episode
```
I hope that helps.
