### DISCUSSION TITLE
RSS podcasts controls ( listening order , bulk mark played, add last # to queue)

### DISCUSSION THREAD

**Discussion by Retrospecs** [music-assistant/support#3673] [Feature requests and ideas]
I want to set the playing order for the rss feed: Play older first or play newer first.

I understand storybased podcast you might want to listen in chronological order. News or current events, you usually want to listen newest first.

I want to set up a news podcast to play automatically play when I wake up (using home assistant).  
I'm starting a MA.playmedia from HA automation using the media ID being the name of the podcast. 
The current behaviour seem to be finding the oldest unplayed episode and adding everything newer (even if already played, this might be a bug dunno).

I found a very labor intensive work-around, I can go and manually mark each episode by clicking the kebab menu on each. (500+ per feed)
I suggest the "marked played" action should be added to the multiselect checkboxes. The opposite "marked unplayed" should also be available with multiselect.

It'd be great if I could have the option to choose how many episodes to add the last, w/ filter for played/unplayed in the HA playmedia action.

**Comment by PePeLLee** [comment]
How did you manage to have latest episodes? I do get new episodes only when I go to configuration and hit refresh.

**Reply by DAONEW** [reply]
I have possibly found the dumbest solution to play the latest episodes with standard rss.
The script skips through all episodes to finally reach the newest.

With ABS the order is correct it seems, with rss its reversed as old episodes are first in the list. 

```
alias: Play Ab 17 Podcast
sequence:
  - data:
      config_entry_id: XXX
      media_type: podcast
      favorite: true
      search: ab 17
    response_variable: latest_podcast
    action: music_assistant.get_library
  - data:
      media_id: "{{ latest_podcast['items'][0]['uri'] }}"
      entity_id: media_player.lounge
    action: music_assistant.play_media
  - action: music_assistant.get_queue
    target:
      entity_id: media_player.lounge
    response_variable: queue
    data: {}
  - variables:
      queue_items: "{{ queue['media_player.lounge']['items'] }}"
  - repeat:
      count: "{{ queue_items }}"
      sequence:
        - target:
            entity_id: media_player.lounge
          action: media_player.media_next_track
          data: {}
```
