### DISCUSSION TITLE
Set the currently playing Player as default

### DISCUSSION THREAD

**Discussion by joneselliot** [music-assistant/support#3699] [Feature requests and ideas]
Hi folks. I'm the only person in my household, so I'm only ever playing from one player (or group of players) at a time. 

 I use the Home Assistant integration and when I open Music Assistant, I expect that if only one player (or group of players) is playing, that the web interface should show me that player instead of the previously selected player. 

Typically, in HASS, I'll use a Navigate action to open the MASS addin. Sometimes this opens to the last player I selected when using the MASS interface, instead of the player that is currently playing. 

My ask is that when only one player is playing, that player should be the default player that is shown in the UI, rather than whatever player was last selected. It's a pain to have to select the Players list and choose the player that's currently active (again, I only ever have one player or player group going at one time) when it seems like the more intuitive behavior is to show the only player that's playing. 

Thanks y'all, happy to answer any questions!

**Comment by OzGav** [comment]
While we wait for discussions to occur on this maybe this is of some use specifically opening the view with a specific player selected https://www.music-assistant.io/faq/how-to/#access-the-ma-views-directly-via-url

**Reply by joneselliot** [reply]
Thanks for the tip @OzGav. Just want to confirm, do these query parameters work using the Navigate action in Home Assistant? I'm not having any success appending ?player=true to my Music Assistant page url.

**Reply by OzGav** [reply]
Please show the exact URL you are using.

**Reply by joneselliot** [reply]
Sorry, was on mobile earlier. 

To clarify, this is from a Home Assistant Dashboard using the Navigate interaction. 

I've tried /d5369777_music_assistant?player=true, /d5369777_music_assistant?player=[player name, i.e. Living Room Speaker, url-encoded], etc. and the MASS web client will still sometimes show an inactive player. 

```
type: entity
show_name: false
show_state: true
show_icon: true
entity: media_player.google_speakers_2
state_content:
  - media_title
  - media_artist
show_entity_picture: true
icon: mdi:speaker-multiple
visibility:
  - condition: state
    entity: media_player.google_speakers_2
    state: playing
tap_action:
  action: navigate
  navigation_path: /d5369777_music_assistant?player=true
```
