### DISCUSSION TITLE
Routing DNS Issue with Music Assistant on Raspberry Pi 5 (Docker + Traefik + Pi-hole + Home Assistant)

### DISCUSSION THREAD

**Discussion by brochond** [music-assistant/support#3748] [Q&A] [answered]
Hello everyone,

I am running a Raspberry Pi 5 with Docker containers to manage my home automation setup. My configuration includes:
- Pi-hole: Manages internal DNS and ad-blocking (but in this case, it’s for domain name resolution).
- Traefik: Handles routing to subdomains and Docker containers.
- Home Assistant (HA): Running in host mode.
- Music Assistant (MA): Also running in host mode.

I have successfully mapped all my internal DNS entries to Pi-hole, Traefik, and Home Assistant. However, I am struggling to get Music Assistant (MA) to work with Traefik. When I try to access it, I receive a “Bad Gateway” error directly from MA container.

For Home Assistant, I had to add the following configuration to allow proper forwarding:

```yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.2    
    - 172.18.0.0/16
```

I am wondering if Music Assistant requires a similar configuration, and if so, where should I define it? Should it be set directly in the docker-compose file or somewhere else?

Any guidance would be greatly appreciated!

Thanks in advance for your help!

**Comment by brochond** [comment, marked as answer]
_I found a solution, and i can share it with you:_

To ensure proper reverse proxy behavior for Music Assistant behind Traefik, it’s essential to correctly forward client IPs and host headers. This can be achieved by defining a middleware in Traefik that explicitly sets these headers.

Traefik Configuration (middlewares section):

```yaml
  middlewares:
    forward-auth:
      headers:
        customRequestHeaders:
          X-Forwarded-For: "{clientIP}"
          X-Real-IP: "{clientIP}"
          Host: "{host}"
```

By adding this middleware, Music Assistant will correctly receive client information when routed through Traefik.
