### DISCUSSION TITLE
Return to playlist after diversion

### DISCUSSION THREAD

**Discussion by msknight** [music-assistant/support#3756] [Q&A] [answered]
I've got an automation that will flip to Radio 2 just before the news (as long as I'm in the room) and then return to playing whatever was on before it happened. Mostly, it works.

However, if I was playing a playlist then it only returns to the track that was playing and the playlist only contains the one track.

Can someone help me get my code right please?

```
alias: Radio 2 News
description: ""
triggers:
  - trigger: time
    at: "08:59:30"
conditions:
  - condition: state
    entity_id: binary_sensor.apollo_msr_2_15d6fc_radar_target
    state: "on"
actions:
  - if:
      - condition: state
        entity_id: media_player.office_music_player
        state: playing
    then:
      - action: media_player.play_media
        metadata: {}
        data:
          media_content_id: >-
            http://lstn.lv/bbcradio.m3u8?station=bbc_radio_two%22&bitrate=320000%22
          media_content_type: R
        target:
          entity_id: media_player.office_music_player
      - delay:
          hours: 0
          minutes: 4
          seconds: 0
          milliseconds: 0
      - target:
          entity_id: media_player.office_music_player
        data:
          media_content_id: "{{ player_media_content_id }}"
          media_content_type: music
        action: media_player.play_media
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ player_Source != None }}"
            sequence:
              - target:
                  entity_id: media_player.office_music_player
                data:
                  source: "{{ player_Source }}"
                action: media_player.select_source
      - data: {}
        action: media_player.media_play
        target:
          entity_id: media_player.office_music_player
    else:
      - action: media_player.play_media
        metadata: {}
        data:
          media_content_id: >-
            http://lstn.lv/bbcradio.m3u8?station=bbc_radio_two%22&bitrate=320000%22
          media_content_type: R
        target:
          entity_id: media_player.office_music_player
      - delay:
          hours: 0
          minutes: 4
          seconds: 0
          milliseconds: 0
      - action: media_player.media_stop
        metadata: {}
        data: {}
        target:
          entity_id: media_player.office_music_player
mode: single
variables:
  player_Source: "{{ state_attr('media_player.office_music_player','media_channel') }}"
  player_media_content_id: "{{ state_attr('media_player.office_music_player','media_content_id') }}"
  player_State: "{{ states('media_player.office_music_player') }}"
```

**Comment by OzGav** [comment, marked as answer]
I like the idea but all that `{{ state_attr('media_player.office_music_player','media_content_id') }}` will contain will be the track that was playing at the time. It does not contain the whole queue. That information will be lost. You would have to grab all of the queue before changing to the radio station and store that. Look here https://github.com/orgs/music-assistant/discussions/1240#discussioncomment-12396494 for how you could achieve that. Then you will have to use the `music_assistant.play_media` action to start the playback as that can accept multiple URIs. (edit: Note that the API call shown pulls in the whole queue including played items so you would have to use `music_assistant.get_queue `first to establish what number in the queue you are up to and then use that as the offset)

In all cases the track that was playing will restart unless you do more cleverness to store the position(`media_position` attribute)  that the track was up to and then seek to that upon restoring

**Reply by OzGav** [reply]
Here is an example. Get the `queue_id` by using the `player_id` that you will find at the top of the player's setting page

```
input_number:
  current_index:
    name: current_index
    initial: 0
    min: 0
    max: 500
    step: 1

rest_command:
  ma_get_full_queue:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "player_queues/items",
        "args": {
          "queue_id": "4286a323-cabd-9c52-fc5e-d36164e2a2c4",
          "limit": 10,
          "offset": {{ states.input_number.current_index.state }}
        }
      }
    content_type:  'application/json; charset=utf-8'

script:
  inject_news:
    mode: restart
    alias: "Inject News into Queue"
    sequence:
      - action: media_player.media_pause
        target:
          entity_id: media_player.office_music_player
      - variables:
          media_position: "{{ state_attr('media_player.office_music_player', 'media_position') }}"
      - action: music_assistant.get_queue
        data:
          entity_id: media_player.office_music_player
        response_variable: queue_info
      - action: input_text.set_value
        data:
          entity_id: input_number.current_index
          value: |
              {{ queue_info["media_player.office_music_player"].current_index }}
      - action: rest_command.ma_get_full_queue
        response_variable: full_queue
      - variables:
          queue_uris: "[{% for item in full_queue.content %}'{{ item.media_item.uri }}'{% if not loop.last %}, {% endif %}{% endfor %}]"
      - action: media_player.play_media
        data:
          media_content_id: >-
            http://lstn.lv/bbcradio.m3u8?station=bbc_radio_two%22&bitrate=320000%22
          media_content_type: R
        target:
          entity_id: media_player.office_music_player
      - delay:
          hours: 0
          minutes: 4
          seconds: 0
          milliseconds: 0
      - action: music_assistant.play_media
        target:
          entity_id: media_player.office_music_player
        data:
          media_id: "{{ queue_uris }}"
          media_type: track
          enqueue: replace
      - action: media_player.media_seek
        data:
          entity_id:  media_player.office_music_player
          seek_position: {{ media_position }}
```

**Reply by msknight** [reply]
Thank you very much. I'll give that a crack.

**Reply by msknight** [reply]
I'm obviously not understanding how to implement this properly as the script in automation is giving "Message malformed: extra keys not allowed @ data['script']" whenever I try and save the script.

For now, I've worked around it by using two players. I pause the first, then play the second and when it's finished, un-pause the first.

The only thing I can think of is that you're intending that the whole thing is put in configuration.yaml and I can see that needed for the rest_command, but I'm trying to keep clear of the configuration.yaml and do everything in GUI, which is perhaps setting up a rod for my own back, but I determined that if I didn't, then my configuration file would get to be a nightmare very quickly.

**Reply by OzGav** [reply]
You can use a package file and just put in it what I posted above. https://www.home-assistant.io/docs/configuration/packages/

**Reply by msknight** [reply]
I'm getting - "Error loading /config/configuration.yaml: invalid key: "{'media_position': None}"
  in "/config/packages/radio2newsinject.yaml", line 72, column 0" - I can't see what it doesn't like.
I've even pasted in the code without changing anything... it doesn't like it for some reason.

**Reply by msknight** [reply]
I'm getting there... now at the point...
Error: Client error occurred when calling resource "http://localhost:8095/api"
...I think it might because I haven't set up anything for firewall/etc. for the api to be used?

**Reply by msknight** [reply]
Making progress. Found that the web was disabled by default, so I found where to enable it.
Now getting - Failed to perform the action script/inject_news_into_queue. UndefinedError: 'str object' has no attribute 'media_item'

**Reply by msknight** [reply]
OK - the failure with the invalid key was the lack of quotes. However, now that I've got that working, I'm back to the "Failed to perform the action script/inject_news. UndefinedError: 'str object' has no attribute 'media_item'" error.

**Comment by msknight** [comment]
OK - with all the code in a yaml file in packages, I get the invalid key error.
With the input number and the rest code in the package and the rest in a script automation, I get the str object error.
I think I'm reaching the end of knowing how to debug this.

**Reply by msknight** [reply]
I think it might have been lack of quotes around the set of {{ }} at the last variable.

**Comment by msknight** [comment]
This is what I now have...

```
input_number:
  current_index:
    name: office_player_current_index
    initial: 0
    min: 0
    max: 5000
    step: 1

rest_command:
  ma_get_full_queue:
    url: http://localhost:8095/api
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: >
      {
        "message_id": "1",
        "command": "player_queues/items",
        "args": {
          "queue_id": "{{ state_attr('media_player.office_music_player', 'active_queue') }}",
          "limit": 10,
          "offset": {{ states.input_number.office_player_current_index.state }}
        }
      }
    content_type:  'application/json; charset=utf-8'

script:
  inject_news:
    mode: restart
    alias: Inject News into Queue
    sequence:
      - action: media_player.media_pause
        target:
          entity_id: media_player.office_music_player
        data: {}
      - variables:
          media_position: "{{ state_attr('media_player.office_music_player', 'media_position') }}"
      - action: music_assistant.get_queue
        data:
          entity_id: media_player.office_music_player
        response_variable: queue_info
      - action: input_text.set_value
        data:
          entity_id: input_number.office_player_current_index
          value: |
            {{ queue_info["media_player.office_music_player"].current_index }}
      - action: rest_command.ma_get_full_queue
        response_variable: full_queue
        data: {}
      - variables:
          queue_uris: >-
            [{% for item in full_queue.content %}'{{ item.media_item.uri }}'{% if
            not loop.last %}, {% endif %}{% endfor %}]
      - action: media_player.play_media
        data:
          media_content_id: http://lstn.lv/bbcradio.m3u8?station=bbc_radio_two%22&bitrate=320000%22
          media_content_type: R
        target:
          entity_id: media_player.office_music_player
      - delay:
          hours: 0
          minutes: 4
          seconds: 0
          milliseconds: 0
      - action: music_assistant.play_media
        target:
          entity_id: media_player.office_music_player
        data:
          media_id: "{{ queue_uris }}"
          media_type: track
          enqueue: replace
      - action: media_player.media_seek
        data:
          entity_id: media_player.office_music_player
          seek_position: "{{ media_position }}"
```

**Reply by msknight** [reply]
Perplexity suggested the following, which has at least progressed to the step where Radio 2 is being called...
```
- variables:
    queue_uris: >-
      [{% for item in full_queue.content %}
        {% if item is mapping and item.media_item is defined and item.media_item.uri is defined %}
          '{{ item.media_item.uri }}'{% if not loop.last %}, {% endif %}
        {% endif %}
      {% endfor %}]
```

**Comment by msknight** [comment]
Nearly there. I've just got to sort out my queue_id I guess. Have I got the wrong number?

The response from the rest command is...
```
full_queue:
  content: >-
    Invalid JSON: b'{\n  "message_id": "1",\n  "command":
    "player_queues/items",\n  "args": {\n    "queue_id":
    "2c:cf:67:af:0f:0c",\n    "limit": 10,\n    "offset": \n  }\n}'
  status: 400
```
![Screenshot from 2025-03-21 21-20-54](https://github.com/user-attachments/assets/86357644-2bf2-4ce5-878e-a8a04f103344)

**Reply by msknight** [reply]
It seems that the following is not working as apparently queue_info is undefined...
```
  - action: input_text.set_value
    data:
      entity_id: input_number.office_player_current_index
      value: |
        {{ queue_info["media_player.office_music_player"].current_index }}
```

**Reply by msknight** [reply]
It appears that I didn't change the full definition of the "current_index" variable. Changed and that's working now. Still testing.

**Reply by OzGav** [reply]
Did you notice this typo by me ` action: input_text.set_value` should be `action: input_number.set_value`

**Reply by msknight** [reply]
OK - there seems to be no command to jump to a particular track in the playlist.
I tried loading a playlist of 12 items and forwarding 2 tracks, but it re-loaded all twelve tracks and started at the first track again.
Going to bed now. 
```
sequence:
  - action: media_player.media_pause
    target:
      entity_id: media_player.office_music_player
    data: {}
  - variables:
      media_position: "{{ state_attr('media_player.office_music_player', 'media_position') }}"
  - action: music_assistant.get_queue
    data:
      entity_id: media_player.office_music_player
    response_variable: queue_info
  - action: input_text.set_value
    data:
      entity_id: input_number.office_player_current_index
      value: |
        {{ queue_info["media_player.office_music_player"].current_index }}
  - action: rest_command.ma_get_full_queue
    response_variable: full_queue
    data: {}
  - variables:
      queue_uris: |-
        [{% for item in full_queue.content %}
          {% if item is mapping and item.media_item is defined and item.media_item.uri is defined %}
            '{{ item.media_item.uri }}'{% if not loop.last %}, {% endif %}
          {% endif %}
        {% endfor %}]
  - action: media_player.play_media
    data:
      media_content_id: http://lstn.lv/bbcradio.m3u8?station=bbc_radio_two%22&bitrate=320000%22
      media_content_type: R
    target:
      entity_id: media_player.office_music_player
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ queue_uris | length > 0 }}"
        sequence:
          - action: media_player.shuffle_set
            metadata: {}
            data:
              shuffle: false
            target:
              entity_id: media_player.office_music_player
          - action: music_assistant.play_media
            target:
              entity_id: media_player.office_music_player
            data:
              media_id: "{{ queue_uris }}"
              media_type: track
              enqueue: replace
          - action: media_player.media_seek
            data:
              entity_id: media_player.office_music_player
              seek_position: "{{ media_position }}"
    default:
      - action: media_player.media_stop
        target:
          entity_id: media_player.office_music_player
        data: {}
mode: restart
alias: Inject News into Queue
description: ""
```
