### DISCUSSION TITLE
mass process maxes out CPU constantly

### DISCUSSION THREAD

**Discussion by DarakDuVal** [music-assistant/support#3777] [Q&A] [answered]
Some time after running music-assistant in docker container, one CPU goes on 100% load for mass process and stays there forever

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                3078 root      20   0  403904 205920  61908 R 100.3   0.2 911:31.27 mass
```

Config is pretty default, with the only exception that I attach the host path as ro:
```
services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - /shares:/media:ro
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
```

What could be the issue here?

Thanks for any help or advice what to look out for.
