### DISCUSSION TITLE
Unique url for play queue

### DISCUSSION THREAD

**Discussion by sanderttttt** [music-assistant/support#3825] [Feature requests and ideas]
Hi,

Awesome work! I cast via catt Music Asssistant to my Google Nest Hub Max and works great. 

It would be even greater if I could also cast directly the play queue, but for that it requires unique url. Eg 192.168.x.x:8095/#/queue (so following 192.168.x.x:8095/#/albums, 192.168.x.x:8095/#/artists, as already available today). 

So desired would be like shown below:

![image](https://github.com/user-attachments/assets/0bd3f40f-de1e-45b1-b0af-17e5e9f78689)

Keen to hear if thats possible.

Regards,

**Comment by Njur** [comment]
Did you find a solution. When I cast dashboard with Music Assistant to Nest Hub Max it just gives error.

**Comment by marcelveldt** [comment]
Maybe you need to define more accurately what exactly you miss/want because I don't understand it ?
Dont use technical definitions but describe the desired outcome.

Do you want to display the MA interface on your nest hub display ?

**Reply by Njur** [reply]
Thanks and yes absolutely wants to display MA interface on Nest Hub Display. Also created a topic but no one could help.
https://github.com/orgs/music-assistant/discussions/3852

Have tried everything I could think of. Have Cast to Nest Hub blueprint and everything else work but not MA.

**Comment by sanderttttt** [comment]
@Njur - for me it works using https://github.com/jrobichaud/ha-catt-service

```
action: catt_service.cast_site
metadata: {}
data:
  device_id: 
  url: http://192.168.x.x:8095/
```

See also https://blog.fuzzymistborn.com/homeassistant-and-catt-cast-all-the-things/ to set things up in the configuration.yaml

With this working, I ideally would cast directly the play queue url, however there is no such url, so cant cast this directly...

**Reply by Njur** [reply]
I'm using this blueprint and the responstime is quick. When I try CATT is seems much slower:
```
alias: Cast til Nest Hub Max
description: ""
triggers:
  - entity_id: media_player.kokken
    for:
      hours: 0
      minutes: 0
      seconds: 5
    to: "off"
    trigger: state
  - entity_id: media_player.kokken
    for:
      hours: 0
      minutes: 0
      seconds: 5
    from: playing
    trigger: state
  - minutes: /9
    trigger: time_pattern
  - minutes: "0"
    trigger: time_pattern
actions:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: media_player.kokken
                state: "off"
              - condition: state
                entity_id: media_player.kokken
                state: paused
                for:
                  hours: 0
                  minutes: 0
                  seconds: 5
                  milliseconds: 0
        sequence:
          - data:
              is_volume_muted: true
              entity_id: media_player.kokken
            action: media_player.volume_mute
          - data:
              entity_id: media_player.kokken
            action: media_player.turn_off
          - delay:
              seconds: 5
          - data:
              entity_id: media_player.kokken
            action: media_player.turn_on
          - data:
              view_path: "0"
              dashboard_path: dashboard-mushroom
              entity_id: media_player.kokken
            action: cast.show_lovelace_view
          - data:
              view_path: "0"
              dashboard_path: dashboard-mushroom
              entity_id: media_player.kokken
            action: cast.show_lovelace_view
          - delay:
              seconds: 5
          - data:
              is_volume_muted: false
              entity_id: media_player.kokken
            action: media_player.volume_mute
mode: single
```
