### DISCUSSION TITLE
Can't play on a esphome device

### DISCUSSION THREAD

**Discussion by off112a** [music-assistant/support#3869] [Q&A] [answered]
Hi,

I can't play on my esp32-wrover with esphome. 
I have added Home assistant as a plugin provider and player provider. The esp32-wrover shows up as a player and I can select it. 
When I start playing music, it stops immediately. I have tested both with local music and spotify connect.
It works if I flash it with squeezelite-esp32, but this device has to be esphome because I control my speakers with IR with it.

I can play audio from Home Assistant to the device, but not from Music Assistant.

I have tried playing both mp3 and flac with same result. I have tried both with "bits_per_sample: 16bit" and without.

I have also a M5Stack Atom Echo that I use as Home Assistant voice assistant. I got the same problem with it when try playing music from Music Assistant.

Music assistant Server version: 2.5.1 on docker.

I use the new media player function in esphome:

```
# Aktivera I²S Audio
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO33

    
  
# PCM5102A som högtalare
speaker:
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO32
    #sample_rate: 48000
    bits_per_sample: 16bit
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input
  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input

# Media Player (för ljuduppspelning)
media_player:
  - platform: speaker
    name: "Uterum mediaspelare"
    id: speaker_media_player_id
    media_pipeline:
        speaker: media_spk_resampling_input
        num_channels: 2
    announcement_pipeline:
        speaker: announcement_spk_resampling_input
        num_channels: 1  
    on_idle:
      then:
        - button.press: powerbutton
    on_play:
      then:
        - button.press: powerbutton
        - delay: 10s
        - button.press: auxbutton 
```

Epshome log: 
```
[11:41:32][E][speaker_media_player:328]: The media pipeline's file reader encountered an error.
[11:41:33][E][speaker_media_player.pipeline:112]: Media reader encountered an error: ESP_FAIL
```
Music assistant log:

```
2025-04-13 11:41:32.889 ERROR (MainThread) [aiohttp.server] Error handling request from 192.168.1.26
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 498, in serve_queue_flow_stream
    output_format = await self.get_output_format(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 1200, in get_output_format
    player_max_bit_depth = max(supported_bit_depths)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() iterable argument is empty
```

**Comment by OzGav** [comment]
From the docs:

> ESPHome based Media Players are in general not recommended for playback of music. Short audio announcements or possibly webradio could work but it is really not suitable for playing music from MA. TIP: you may have to enable the "fixed content length" HTTP profile in the player's settings. Having said that, more powerful ESPHome based players such as the HA Voice PE work well, support FLAC and have some other optimisations.

**Reply by off112a** [reply]
Can't find this setting:

 TIP: you may have to enable the "fixed content length" HTTP profile in the player's settings.

**Reply by OzGav** [reply]
It may get filtered out depending on the device. I can see it isn't shown for my Voice PE but other HA players look like

![image](https://github.com/user-attachments/assets/75720f1c-3e0f-416d-acb6-d83a51a25ef5)

edit: I am checking on this though

**Comment by marcelveldt** [comment]
You have sample rate commented out in your code. You need that. You will need a sample rate of 44100 or 48000 for the media pipeline, anything below that is not useable for music

**Reply by off112a** [reply]
I have forgot to remove the comment. It was left over when I tried different solution to get it to work. I have it set on 48000.

**Comment by off112a** [comment]
It's strange that is working if I play a flac or mp3 song direct from Home Assistant to the esp32.

**Comment by off112a** [comment]
I updated Music Assistant to beta and now I can play on my esp32-wrover with esphome.

**Comment by off112a** [comment]
It stopped working again. I switched back to latest branch instead of beta and it works again.

**Reply by OzGav** [reply]
If this remains a problem please continue testing to try and work why it appears intermittent

**Comment by off112a** [comment, marked as answer]
It's been working for a while.

**Comment by JazekerXX** [comment]
so, does esp32-wrover with esphome work as a player in music assistance?

**Reply by OzGav** [reply]
If it can run sendspin then it should

**Reply by JazekerXX** [reply]
i don't know what a sendspin is. 

but if i go to settings/players i can see the esp device but it's a bit grayed out. and there is an hourglass which says "this player is not available (yet)" but it's like that for a week, so i don't think it will come available. you got any ideas why this is?
<img width="1371" height="60" alt="image" src="https://github.com/user-attachments/assets/72c48006-90f0-4ad9-bf6f-f7800666c327" />

i did found a way to add sendspin to esphome config by simply just adding sendspin: to the config. MA sees that it's available now but still the player is unavailable. 
<img width="1366" height="61" alt="image" src="https://github.com/user-attachments/assets/e65e33bf-c6ac-4c9d-8b80-34cf211d06fd" />

this is my esphome config now: did i miss something?

```
esphome:
  name: audio1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "**********************************************"

ota:
  - platform: esphome
    password: "*****************************************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Audio1 Fallback Hotspot"
    password: "***************************"

# Enable Web server
web_server:
  port: 80
  
captive_portal:

improv_serial:

sendspin:
  
i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO19

speaker:
  - platform: i2s_audio
    id: audio1
    dac_type: external
    i2s_dout_pin: GPIO22
    sample_rate: 48000
    bits_per_sample: 16bit
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: audio1
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input
  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input

media_player:
  - platform: speaker
    name: "Speaker Media Player"
    id: speaker_media_player_id
    media_pipeline:
        speaker: media_spk_resampling_input
        num_channels: 2
    announcement_pipeline:
        speaker: announcement_spk_resampling_input
        num_channels: 1
```
