### DISCUSSION TITLE
"Keep Alive" for google cast-based players

### DISCUSSION THREAD

**Discussion by SteveDinn** [music-assistant/support#3949] [Q&A] [answered]
When music is paused on a cast-based player, there seems to be only a certain amount of time before whatever was playing on it is abandoned and the player repoerts as 'idle'. This is normal behaviour for a cast device, but it sucks when you can see the `current item` and `next item` are still present in the attribiutes of the Home Assistant entity, but yet it can't be resumed because it's no longer paused.

It would be cool if Music Assistant could prevent this from happening, so that the player could be un-paused at the users leisure. This might involve something like providing a "keep alive" audio stream of silence during the time when the player would be paused for longer than whatever the cast timeout is. This might make the cast device look like it was still playing, but the Music Assistant version of that device could know that it was paused. The "silence" audio might even have metadata reporting that it was the Artist "Paused" from the album "Paused" :)

Or maybe Music Assistant could just ignore that the cast player has stopped being paused when Music Assistant knows it should still be paused.  Something like that.

Does that make sense?

**Comment by marcelveldt** [comment]
Why can't you resume the stream when it was stopped?

If the stream was started with MA, you can simply press play again and it will resume just fine where it stopped

**Reply by SteveDinn** [reply]
I can do this from the Music Assistant web site, you are correct. But from Home Assistant, the MA-based media_player entity goes to "idle" after the actual cast-device goes to "idle" when it times out of pausing. Then from Home Assistant, you can no longer resume playback, becuase the entity isn't in the "paused" state any more.

I know this is a bit of an edge-case, and fairly minor. But I have gotten very used to telling my conversation assistant to "resume" stuff (The AI integration with Music Assistant is fantastic), and it's off-putting when it doesn't work sometimes.

**Reply by OzGav** [reply]
You aren’t being completely clear here. I think you are only talking about voice commands? If you press the play button in HA it will resume.

**Reply by SteveDinn** [reply]
I will verify this one again to make sure I'm making sense.

**Reply by SteveDinn** [reply]
Ok. I've reproduced it.

So, yes, I can go into the Music Assistant web site and click play and it will reconnect to the cast speaker and continue from where it left off. But from Home Assistant, the speaker goes to `off` and then I can't resume from Home Assistant anymore, via voice or via clicking a button -- I didn't use voice at all this time. Here are the timelines of the devices. The latest "playing" event was when I started the speaker again from the Music Assistant web site.

First, the Music Assistant `media_player` device:
![Music Assistant Device](https://github.com/user-attachments/assets/e92378e9-3fda-4985-9311-6f7140081d0c)

And, the backing cast `media_player` device (that I don't use directly in favour of the MA device):
![Cast Device](https://github.com/user-attachments/assets/3f3b6ae9-5252-4589-a3a3-61c45b26b0d2)

**Reply by SteveDinn** [reply]
Are there any particular logs you'd like to see?

**Reply by OzGav** [reply, marked as answer]
This is not a problem that needs logs. It seems to be a HA limitation that when the player goes to the off state then the play disappear. Have you tried an automation that turns the player on whenever it goes to the off state?

**Reply by SteveDinn** [reply]
I'll be damned... That works. This is good enough for me. I should have tried that, but I thought turning the device back on would reset it to zero.

Thanks!

**Comment by SteveDinn** [comment]
If anybody finds this later, I've written a script for Conversation Agents to be able to successfully un-pause a home assistant media_player that music-assistant thinks is paused, but may have actually turned off or be in an idle state:

```
alias: Resume Playing Music Assistant Speaker
description: >-
  When the user asks to resume playing on a speaker, this script should be run
  instead of trying to resume playing by directly affecting a particular device.
mode: parallel
max: 10
fields:
  media_player_name:
    selector:
      text:
        multiple: false
        multiline: false
    description: >-
      The name of the media_player device to resume. Remove any articles like
      'the' or 'a' which might be a prefix or suffix to the name.
    name: Media Player
sequence:
  - variables:
      media_player_entity: |-
        {{ integration_entities('music_assistant') 
          | expand 
          | selectattr('name', 'search', media_player_name, ignorecase=True)
          | map(attribute='entity_id') 
          | first
          | default }}
  - alias: >-
      If we couldn't find a music-assistant player, then check for other types
      of media_player
    if:
      - condition: template
        value_template: "{{ media_player_entity | length == 0 }}"
    then:
      - variables:
          media_player_entity: |-
            {{ states.media_player
              | selectattr('attributes.friendly_name', 'search', media_player_name, ignorecase=True)
              | map(attribute='entity_id') 
              | first
              | default }}
      - alias: If we can't find *any* matching media_player entity, then stop.
        if:
          - condition: template
            value_template: "{{ media_player_entity | length == 0 }}"
        then:
          - stop: >-
              A media player matching the name of {{ media_player_name }} could
              not be found.
            response_variable: response
      - action: media_player.media_play
        metadata: {}
        data: {}
        target:
          entity_id: "{{ media_player_entity }}"
      - stop: Resuming {{ media_player_name }}
        response_variable: response
  - alias: If the player is off, then turn it on.
    if:
      - condition: template
        value_template: "{{ states(media_player_entity) in ['off'] }}"
    then:
      - action: media_player.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: "{{ media_player_entity }}"
  - alias: If the player does not have music-assistant attributes, stop.
    if:
      - condition: template
        value_template: >-
          {{ state_attr(media_player_entity, 'app_id') | lower !=
          'music_assistant' }}
    then:
      - stop: "{{ media_player_name }} does not have music assistant attributes"
        response_variable: response
  - alias: If the player is idle or paused, then press play.
    if:
      - condition: template
        value_template: "{{ states(media_player_entity) in ['paused', 'idle'] }}"
    then:
      - action: media_player.media_play
        metadata: {}
        data: {}
        target:
          entity_id: "{{ media_player_entity }}"
  - stop: Resuming music on {{ media_player_name }}
    response_variable: response
```
