### DISCUSSION TITLE
Cannot find media_content_id: How do I create an automation to start a playlist from Jellyfin source to Sonos player?

### DISCUSSION THREAD

**Discussion by johnpc** [music-assistant/support#3982] [Q&A] [answered]
Okay, so I'll preface this by apologizing for the stupid question. I am attempting to create a Home Assistant automation that triggers a Music Assistant playlist (from Jellyfin source to Sonos player if that matters)

This is what I've tried:

```
action: media_player.play_media
metadata: {}
data:
  media_content_type: playlist
  media_content_id: media-source://mass/database://playlist/1
target:
  device_id:
    - 0f584b9b9b10147224ef27e7dde35ba4
    - ea9cefee8d5e4c52401075c547f16a66
```

I think the problem is that I cannot for the life of me figure out what the `media_content_id` should be. I've tried everything including the playlist title and other wacky suggestions from chatgpt.

I get errors in the form of `Error: Unknown media source`

I am using the latest updates of everything. I have googled for some time and read docs and searched the forums but for some reason apparently I'm the only person in the world who cannot just figure this out 😅 

Any examples I can work off of or advice as to what I'm doing wrong?

**Comment by OzGav** [comment, marked as answer]
Have you read the docs? https://beta.music-assistant.io/faq/how-to/

You want the section on how to get the URI. Long story short. Just use the playlist name

**Reply by johnpc** [reply]
What eventually worked for me was this

```
action: music_assistant.play_media
metadata: {}
data:
  media_type: playlist
  media_id: library://playlist/2
target:
  entity_id: media_player.living_room_sonos
```
