### DISCUSSION TITLE
Adding media on local filesystem with docker

### DISCUSSION THREAD

**Discussion by RonnieLast** [music-assistant/support#4043] [Show and tell]
Maybe this is blindingly obvious to others, but it wasn't to me. So here goes:

If you have a docker based install of HA and MA and you wish to share your local MP3's which are already mounted in HA's media folder, then you need to do the following in your docker-compose.yaml:

Firstly in docker-compose.yaml, my HA configuration looks like this:

```
services:
  homeassistant:
    privileged: true
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ./home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id
      - ./home_assistant/media:/media
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mariadb
      - mosquitto
```
As you see, I have my /media mounted in the local filesystem and I have my MP3's copied into that folder. They are visible in HA under Media, obviously.

Then for MA you need to mount that same /media folder (./home_assistant/media in my case) as a volume into the MA docker container. I mistakenly thought that this was automated once MA's integration was installed, but it's not. 

```
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./music-assistant/data:/data/
      - ./home_assistant/media:/media
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=info
```
And just like that, my embarrassingly ancient local music collection comes alive:
![image](https://github.com/user-attachments/assets/7b7f50be-f25c-435d-9546-84ff626d6abe)

Hints, tips, comments or Duh's welcome.
