### DISCUSSION TITLE
how do you put this component into debug mode?

### DISCUSSION THREAD

**Discussion by NorthernMunkey** [music-assistant/support#613] [Q&A]
i thought it was this but it doesn't work.
logger:
   default: error 
    logs:
       homeassistant.custom_components.mass: debug

**Comment by OzGav** [comment]
Marcel warned me off this as it will likely flood your logs but I think you need this (Don't forget to use the <> in future so we can see if you identing is correct)
```
logger:
  default: error
  logs:
    custom_components.mass: debug
```

**Comment by marcelveldt** [comment]
Uhm, why do want to run the logging in debug mode ? note that you will have A LOT of logging now ;-)

**Comment by erkr** [comment]
Anyway, when debug logging is needed to diagnose an issue, there are two options:
Run time, by calling this service: 
``` 
service: logger.set_level
data:
  custom_components.mass: debug
``` 
Or update the logger section of your configuration.yaml:
``` 
logger:
  default: error
  logs:
    custom_components.mass: debug
```
