### DISCUSSION TITLE
How to play a Spotify playlist shuffled?

### DISCUSSION THREAD

**Discussion by derandiunddasbo** [music-assistant/support#725] [Q&A] [answered]
Playing a Spotify playlist in random order seems to be quite straight forward, but I didn't get this running. This service call simply doesn't do anything, neither playing anything, nor throwing any errors in the log:

```
service: mass.queue_command
data:
  command: play_media
  uri: spotify:playlist:xxx
  mode: shuffle_mode_on
target:
  entity_id:
    - media_player.mass_bath
```

When omitting the mode argument, the playlist starts to play fine. Isn't that the correct way to use the mode argument? And if not, how else do I use it?

**Comment by OzGav** [comment, marked as answer]
I am looking at how the mode command should be used but in the interim you can try this to set the shuffle mode on. Add this as a subsequent service call:
```
service: media_player.shuffle_set
target:
  entity_id: media_player.mass_bath
data:
  shuffle: true
```

Indeed you don't need to use that special MA service you can just use the normal HA media player commands as I understand it.
