### DISCUSSION TITLE
9 O'clock on a Saturday automation - A little fun thanks to Music Assistant

### DISCUSSION THREAD

**Discussion by dacmcbibs** [music-assistant/support#823] [Show and tell]
I decided to have a bit of fun with Music Assistant using the automation below.  It triggers at 8:59:29 (AM and PM) on Saturday playing Billy Joel's Piano Man with the sound muted.  This times the line "It's 9 O'Clock on a Saturday" to closely align with when its actually 9:00 (the line occurs ~30 seconds in to the song).  At that point the automation turns the volume up so that the line can be heard, and then after the speaker plays the line it stops the play back.  

I was having trouble getting things to start muted so it currently calls media_player.volume_mute and media_player.volume_set to 0 , which is probably both redundant and not necessary 

```
alias: It's 9 o'clock on a Saturday
description: "Starts Piano man with the sound off perfectly timed so that 9:00 the volume comes on singing 'its 9'oclock on a saturday', then stops"
mode: single
trigger:
  - platform: time
    at: "08:59:29"
  - platform: time
    at: "20:59:29"
condition:
  - condition: and
    conditions:
      - condition: time
        before: "00:00:00"
        weekday:
          - sat
        after: "00:00:00"
action:
  - service: media_player.volume_mute
    data:
      is_volume_muted: true
    target:
      entity_id: media_player.mass_my_speaker
  - service: media_player.volume_set
    data:
      volume_level: 0
    target:
      entity_id: media_player.mass_my_speaker
  - service: media_player.play_media
    target:
      entity_id: media_player.mass_my_speaker
    data:
      media_content_id: media-source://mass/database://track/35
      media_content_type: audio/flac
    metadata:
      title: Billy Joel - Piano Man
      thumbnail: >-
        https://images.weserv.nl/?w=200&url=https://i.ytimg.com/vi/LLbew85exp0/maxresdefault.jpg
      media_class: track
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://mass
        - media_content_type: music
          media_content_id: media-source://mass/tracks
  - wait_for_trigger:
      - platform: state
        entity_id:
          - media_player.living_room_speaker
        to: playing
    continue_on_timeout: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 31
      milliseconds: 0
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    target:
      entity_id: media_player.mass_my_speaker
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.media_pause
    data: {}
    target:
      entity_id: media_player.mass_my_speaker
```
