### DISCUSSION TITLE
Ability to stop playing after current track

### DISCUSSION THREAD

**Discussion by Aasikki** [music-assistant/support#830] [Feature requests and ideas]
This would be nice for making automations/scripts that play music for a set amount of time. You could make an automation that plays music for an hour, and instead of abruptly stopping, it would be nice if the last song fully played before stopping playback.

I tried making my automation wait for the media title to change, before turning off the media player, but I can't get it to trigger for some reason. Maybe this is currently possible with the proper trigger, but having an easy and clean way to do this with a service would be nice.

**Comment by OzGav** [comment]
Sounds like you should have the trigger as the title change and a condition of played for an hour. If you share your automation people might be able to help?

**Reply by Aasikki** [reply]
EDIT: Well uhh, I don't know what changed between me making the script couple days ago and writing this message, but I gave it yet another try after writing this message and now it works fine. Sooooo disregard what I said, leaving it up in case anyone wants to copy my script or has the same problem.

Hey, thanks for replying and sorry for not thinking of sharing my non working script here. Wasn't seeking for help with that to be honest, just sharing this in my opinion nice idea!

I made a simple scrip for this that I should be able to excecute whenever I need it in an automation. When I start the script, it waits for a change in the media title attribute and then turns off the media player. Or at least that's what I _think_ it should do. The problem is that it only triggers when I manually change the song from music assistant, for some reason it doesn't trigger when the next song plays automatically.

```
sequence:
  - wait_for_trigger:
      - platform: state
        entity_id:
          - media_player.mass_all_rooms
        attribute: media_title
    continue_on_timeout: false
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
        - media_player.mass_all_rooms
mode: single
alias: Stop after current track
```

Thanks for any help!

**Reply by OzGav** [reply]
I would approach this a different way. I would have the automation trigger on the attribute change. See here for how to do that https://community.home-assistant.io/t/using-attribute-as-trigger-for-automation/124665

**Reply by Aasikki** [reply]
Hey, see my edit I just made, my script started working for whatever reason. I like this route as I can easily add it to any automation, like now I'm using it in a cleaning timer, that plays music along with couple other things (to motivate me clean my apartment).

**Reply by TicoM1** [reply]
How do you make it to dynamically run on a chosen player/player group, though? I spent (far too mcuh time) to come up with my current intermediate solution, that gives me a selector on my dashboard to pick the player, that I want to stop after current track:

I have a template sensor helper called "sensor.mediaplayertitles" with template
`{{ states.media_player | selectattr('attributes.media_title', 'defined')
   | map(attribute='attributes.media_title') | list }}`

that lists all players, that have a media_title state attribute. 
In my script I trigger on entity change on that template sensor helper (obvious downside discussed below).
The script has a field defined to select an entity pre filtered to the media_player domain:
```
sequence:
  - wait_for_trigger:
      - entity_id:
          - sensor.mediaplayertitles
        trigger: state
    continue_on_timeout: false
  - action: media_player.media_pause
    data: {}
    target:
      entity_id: "{{ target_player }}"
mode: single
alias: Dynamic Stop after current track
description: ""
fields:
  target_player:
    selector:
      entity:
        filter:
          - domain: media_player
    name: target_player
    required: true
    default: media_player.loewe_mr5_1_3
```

Obvious downside: The selected player is currently being stoped as soon as ANY player changes it's title. The part that cost me a lot of time and where I'm stuck at is , that the trigger part of the script will not accept template entitys. **I would have loved to just use the template field "target_player" in the trigger. Reading the docs it's only allowed in the action part. So I have no idea how to further conditionally run depending on the selected target player.**
