### DISCUSSION TITLE
Start a playlist with a script

### DISCUSSION THREAD

**Discussion by heinzma** [music-assistant/support#834] [Show and tell]
As ask by @Bachigaloupe in https://github.com/music-assistant/hass-music-assistant/discussions/820#discussioncomment-3381318.

I can start playlists with a script just fine.
```
alias: TEST playlist TEST
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.mass_muse_luxe
    data:
      media_content_id: media-source://mass/database://playlist/1
      media_content_type: playlist
    metadata:
      title: test
      thumbnail: null
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://mass
        - media_content_type: music
          media_content_id: media-source://mass/playlists
        - media_content_type: audio/flac
          media_content_id: media-source://mass/database://playlist/1
mode: single
```
When using the UI, to create the script, use Action type: "Play media" and make sure to choose "Music Assistant" -> "Playlist" when picking the media. NOT "Local Media" -> "...".

You can also use Action type: "Call Service", Service: "Media player: Play media". Content ID: `media-source://mass/database://playlist/X`. X is a number 1, 2, 3, ... the number seems to corresponds to the order in which the playlists were created.

**Comment by Bachigaloupe** [comment]
@heinzma Thanks for this. This is helpful to see other examples and I see this showed up under discussions in GitHub. 

I think the most helpful is to see your script and then hope I can find my paths to the said playlist. 

The script step I looked at late yesterday asked for a URI and I assumed it was a "pathname,playlistname"

This was helpful to set me off trying things on my own. 

Very much appreciate your taking the time. 

Rich

**Comment by rjgrandy** [comment]
Is this really the easiest way to programmatically call a playlist? How is it even possible to know what playlist corresponds to which number without using the automation ui? Music Assistant has a lot of promise but the documentation is a bit lacking making it hard to figure out how to do things programmatically.

**Reply by OzGav** [reply]
Let me start by saying the tone of your last sentence isn’t great. Having said that, isn’t the answer to your question about what number to use answered in the last paragraph of the first post?

**Reply by marcelveldt** [reply]
@rjgrandy feel free to contribute to the documentation, thanks!

**Reply by rjgrandy** [reply]
I am happy to contribute to the documentation as I learn, is there a format that you are trying to use? My personal opinion feedback is that the linking to posts isn't the best method of documentation since it can be old information and from users who are also just learning. I also think I am still trying to figure out how to do things for the first time, but I can offer examples of how I use it in my setup.

@OzGav I'm sorry if I came off a bit harsh, that wasnt my intent. The first post says the number _**seems**_ to correspond to the add order. That didn't sound very definative or official. I was also trying to understand the other Metadata structure and keywords and was having difficulty understanding what all belongs there.

**Reply by OzGav** [reply]
Thanks @rjgrandy. There is quite a lot of coding work going on with associated changes so at this point linking to posts we feel is appropriate as it is the latest information available. If it becomes out of date we will remove or adjust the links. As MA is leveraging the HA capabilities (and in some cases in an advanced manner) then documentation shortfalls are possibly not due to us. In the example at the top of this discussion all of it appears to be in https://www.home-assistant.io/integrations/media_player/ (including the links to the Google Dev Documentation) or https://www.home-assistant.io/docs/blueprint/selectors/#media-selector

Having said that @marcelveldt has written a dedicated service call for MA (see below) that we are yet to properly document.

**Comment by marcelveldt** [comment]
Maybe we should better document the "mass.queue_command" service as it is way more easier to use than the builtin services. For example you can simply start a playlist by name instead dof having to lookup the id.

BTW: Next version will also accept the filepath as item_id

**Reply by OzGav** [reply]
We only have a tiny bit in the FAQ currently which steers people away from using it so that will be a change that will need some examples I would suggest.

**Reply by OzGav** [reply]
Examples for how to use `mass.queue_command` have been added to the FAQ

**Comment by Buster14** [comment]
Hi, I wasnt able to get this to work, So i created playlist and i'm able to play it through MA.
Then I created script just like instruction above like this :

```
alias: Alan_Playlist
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.ad4507f6_88ce9ee6
    data:
      media_content_id: media-source://mass/database://playlist/1
      media_content_type: playlist
    metadata:
      title: Alan
      thumbnail: null
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://mass
        - media_content_type: music
          media_content_id: media-source://mass/playlists
        - media_content_type: audio/flac
          media_content_id: media-source://mass/database://playlist/1
mode: single
```
But the script does nothing, it only says "playlist name triggered"


This is the trace :  
```

params:
  domain: media_player
  service: play_media
  service_data:
    media_content_id: media-source://media_source/local/music/Alan.m3u
    media_content_type: audio/x-mpegurl
    entity_id:
      - media_player.ad4507f6_88ce9ee6
  target:
    entity_id:
      - media_player.ad4507f6_88ce9ee6
running_script: false
limit: 10
```

**Reply by OzGav** [reply]
Maybe your playlist number is incorrect? Also you can try setting up the script through the UI and see how that goes?

**Reply by Buster14** [reply]
There is only 1 playlist, and it's playable through MA.
Another thing, the media player is my lovelace dashboard AIO, 
and I'm testing it from another machine, but that shouldn't be a problem right? 
Ok so I recreated it using UI,
it generated this yaml :
```
alias: Alan
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.ad4507f6_88ce9ee6
    data:
      media_content_id: media-source://mass/database://playlist/1
      media_content_type: playlist
    metadata:
      title: Alan
      thumbnail: null
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://mass
        - media_content_type: music
          media_content_id: media-source://mass/playlists
        - media_content_type: audio/flac
          media_content_id: media-source://mass/database://playlist/1
mode: single
```
Clear cache on AIO

Traces : 

```
Executed: September 20, 2022 at 19:02:07
Result:
params:
  domain: media_player
  service: play_media
  service_data:
    media_content_id: media-source://mass/database://playlist/1
    media_content_type: playlist
    entity_id:
      - media_player.ad4507f6_88ce9ee6
  target:
    entity_id:
      - media_player.ad4507f6_88ce9ee6
running_script: false
limit: 10

```

Still wont run though

**Reply by OzGav** [reply]
Are you saying you can play the playlist to the exact same player directly in MA that you are trying to use in the script? I notice you aren’t targeting a MA player…you don’t have to but I am wondering if this player is compatible with MA?

**Reply by Buster14** [reply]
Yes, I can play playlist through MA using that same player. It's just the script that's stuck.

**Reply by OzGav** [reply]
Might have to wait and see what @marcelveldt thinks…

**Reply by Buster14** [reply]
Update : might be a browser-mod issue, I tested several times and it's disconnected twice. I'll try testing it on DLNA speaker then

**Reply by OzGav** [reply]
The tab will likely be suspended if it is not in focus…

**Comment by gieljnssns** [comment]
Can someone help me to convert this service call to use with MA?
I use this with sonos and the sources are a mix of spotify playlists, tunein stations and sonos radio stations(will they be supported in the future?)
```
action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.keuken
      volume_level: 0.12
  - service: media_player.select_source
    data_template:
      entity_id: media_player.keuken
      source: >
        {{ [
          'Willy',
          'Arrow Classic Rock',
          'Black Label Extreme Metal Radio',
          'VRT Studio Brussel Bruut',
          'Hard Rock Hell Radio',
          'New Lords of Metal',
          'Punk Riot',
          'Brutale Belgen 🇧🇪💪🏻☠️',
          'MetalRock.FM',
          'VRT Studio Brussel Bruut',
          'Hand of Doom Radio',
          'Real Punk Radio',
          'Het betere genre',
          'Brutale Belgen 🇧🇪💪🏻☠️',
          'Het betere genre +',
          'Punk In Drublic',
          'VRT Studio Brussel Bruut',
          'Pinguin Aardschok',
          'Pinguin On The Rocks',
          'Belgische gitaren�',
          'GARAGE BANGERS!',
          "PUNK!!! Let's go!!",
          'VAN EIGEN BODEM! (Belgische Gitaren)'
        ] | random }}
```

**Reply by OzGav** [reply]
This is not my area of expertise but I would suggest creating a play list without the Sonos stations and then work on getting that playlist to play as per the top post.
See here for how to create a playlist https://github.com/music-assistant/hass-music-assistant/discussions/661

**Reply by gieljnssns** [reply]
Where can I find the `media_content_id` of playlists in my MA database?

**Reply by OzGav** [reply]
Yeah not actually sure. Trial and error for the numbers is the best I can do. @marcelveldt mentions above that we will soon provide some documentation on how to use a special MA service call where you will be able to use the playlist title.

**Reply by stu247** [reply]
For the X in `media-source://mass/database://playlist/X`, I was able to find this in the playlists table in the database file `music_assistant.db` located in the home assistant configuration directory.  There is a row in this table for each playlist.  The `item_id` column is the value for X and the `name` column is the name of the playlist.  I used `sqlitebrowser` to view the database file.

**Reply by gieljnssns** [reply]
I found a way!
In your browser go to ` http://HA-IP:8123/lib/mass/#/`, then click on the playlist or radio station and go back to the url (show whole url)
`http://HA-IP:8123/lib/mass/#/playlists/database/47`, the last number is the playlist number.
My service- call looks like this now
```
action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.mass_keuken
      volume_level: 0.12
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %}
              {% set number = numbers | random  %}
              {{ number % 2 == 0 }}
        sequence:
          - service: media_player.play_media
            data:
              media_content_id: >
                {% set playlist_numbers = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
                                            23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 
                                            39, 40, 41, 42, 43, 44, 45, 46, 47, 48 ] %}
                {% set playlist_number = playlist_numbers | random  %}

                media-source://mass/database://playlist/{{playlist_number}}
              media_content_type: playlist
              enqueue: replace
            target:
              entity_id: media_player.mass_keuken
    default:
      - service: media_player.play_media
        data:
          media_content_id: >
            {% set radio_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] %}
            {% set radio_number = radio_numbers | random  %}

            media-source://mass/database://radio/{{radio_number}}
          media_content_type: music
          enqueue: replace
        target:
          entity_id: media_player.mass_keuken
```

**Reply by OzGav** [reply]
The FAQs have been updated which show how to use `mass.queue_command` to start a playlist by name.

**Reply by Kelmino** [reply]
> I found a way! In your browser go to ` http://HA-IP:8123/lib/mass/#/`, then click on the playlist or radio station and go back to the url (show whole url) `http://HA-IP:8123/lib/mass/#/playlists/database/47`, the last number is the playlist number. My service- call looks like this now
> 
> ```
> action:
>   - service: media_player.volume_set
>     data_template:
>       entity_id: media_player.mass_keuken
>       volume_level: 0.12
>   - choose:
>       - conditions:
>           - condition: template
>             value_template: >
>               {% set numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %}
>               {% set number = numbers | random  %}
>               {{ number % 2 == 0 }}
>         sequence:
>           - service: media_player.play_media
>             data:
>               media_content_id: >
>                 {% set playlist_numbers = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
>                                             23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 
>                                             39, 40, 41, 42, 43, 44, 45, 46, 47, 48 ] %}
>                 {% set playlist_number = playlist_numbers | random  %}
> 
>                 media-source://mass/database://playlist/{{playlist_number}}
>               media_content_type: playlist
>               enqueue: replace
>             target:
>               entity_id: media_player.mass_keuken
>     default:
>       - service: media_player.play_media
>         data:
>           media_content_id: >
>             {% set radio_numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] %}
>             {% set radio_number = radio_numbers | random  %}
> 
>             media-source://mass/database://radio/{{radio_number}}
>           media_content_type: music
>           enqueue: replace
>         target:
>           entity_id: media_player.mass_keuken
> ```

When I try to copy/paste this into a script for me I get an error of "Message malformed: extra keys not allowed @ data['action']
"

I've tried replacing the Media players to match the name of mine as well.

Any idea?

**Reply by OzGav** [reply]
Probably a cut and paste error as there is something in the action section that isn’t correctly formatted. Try removing blocks (e.g. the default section) until the error goes away to isolate the issue.

**Reply by jdekoven** [reply]
Does anyone know how to play a Your Tube Playlist, especially with the mass.queue command?  What I really need is to know how to figure out the URI.  With Spotify I can just spell out the name of the playlist and it works great for example "John's Playlist".  This doesn't work for You Tube, nor does the URL.  Any ideas are appreciated.

**Reply by OzGav** [reply]
@MarvinSchenkel is it not possible to specify a YouTube playlist?

**Reply by MarvinSchenkel** [reply]
That should definitely be possible. Here's a snippet of my automation where I do exactly that:
```yaml
variables:
  just_awake_music: ["Classical Meditation", "Tranquil spa day"]
  early_morning_music: ["Chill", "Chill step", "Reflections"]
  morning_music: ["Chill step", "Ambient / Relax"]
  day_music: ["Ambient / Relax", "deepchill"]
  evening_music: ["Ambient / Relax"]
  christmas_music: ["Christmas Hits"]
  active_schedule: '{{ states("input_select.current_music_schedule") }}'
  music_to_play: >-
    {% if active_schedule == "just_awake" %}
      {{ just_awake_music }}
    {% elif active_schedule == "early_morning" %}
      {{ early_morning_music }}
    {% elif active_schedule == "morning" %}
      {{ morning_music }}
    {% elif active_schedule == "day" %}
      {{ day_music }}
    {% elif active_schedule == "evening" %}
      {{ evening_music }}
    {% endif %}
  radio_mode: >-
    {% if active_schedule == "just_awake" %}
      {{ false }}
    {% else %}
      {{ true }}
    {% endif %}
......
- service: mass.queue_command
  data:
    command: play_media
    uri: "{{ music_to_play }}"
    enqueue_mode: replace_next
    radio_mode: "{{ radio_mode }}"
  target:
    entity_id: media_player.mass_sonos_livingroom
```

**Reply by tikeyknax** [reply]
I was looking for a way to get the album numbers for many different albums from music-assistant that I need for my automation and this answer lead me on the right way. So I thought I share my work - maybe it is useful for someone else as well.

To get the required ids of my albums, I first made a copy of `music_assistant.db` and then wrote a small python script to get the needed information. The script prints the album id (item_id) with the album name, the artists and the source (spotify, file, ...). In this list, it's easy to find the right albums (or extent the python script accordingly) and it can then be used in an automation with `media-source://mass/database://album/{item_id}`. The same can easily be done for playlists instead of albums.


```
import sqlite3
import json

con = sqlite3.connect("data/music_assistant.db")
cur = con.cursor()

for row in cur.execute("SELECT item_id,name,artists,provider_ids FROM albums"):
    item_id, name, artists_txt, provider_txt = row
    artists_json = json.loads(artists_txt)
    artists = [aj["name"] for aj in artists_json]

    providers_json = json.loads(provider_txt)
    providers = [pj["prov_type"] for pj in providers_json]

    print(f"{item_id}: {name} ({artists}) -    {providers}")
```

**Comment by pungkula1337anka** [comment]
Is this still somehow possible with music assistant v2?

Thanks for your hard work guys, its much appreciated!

**Reply by OzGav** [reply]
Yes just have to wait until the HA integration is written. Will be in a few weeks

**Reply by pungkula1337anka** [reply]
Wow thats one quick response, I cant wait! you rock.

**Comment by pjdreger3** [comment]
I'm using v2023.1

I copied the script from Buster14 in the comments above and changed it for my instance. (code below).  When I run this script from an automation I  get an unknown media source error. I have only 1 playlist and the playlist and all mp3 files are in the local media folder. I can however play the playlist from the web interface on the selected device. Any help greatly appreciated. Great product

Script
```
alias: TEST playlist TEST
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.office_speaker
    data:
      media_content_id: media-source://mass/database://playlist/1
      media_content_type: playlist
    metadata:
      title: test
      thumbnail: null
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://mass
        - media_content_type: music
          media_content_id: media-source://mass/playlists
        - media_content_type: audio/flac
          media_content_id: media-source://mass/database://playlist/1
mode: single
```

this is the automation
```
alias: MusicPlayScript
description: ""
trigger:
  - platform: tag
    tag_id: 627d6968-11e2-434f-983b-433c909ba618
condition: []
action:
  - service: script.TEST_playlist_TEST
    data: {}
mode: single
```

and this is the script

```
alias: TEST_playlist_TEST
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.office_speaker
    data:
      media_content_id: media-source://mass/database://playlist/1
      media_content_type: playlist
    metadata:
      title: test
      thumbnail: null
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://mass
        - media_content_type: music
          media_content_id: media-source://mass/playlists
        - media_content_type: audio/flac
          media_content_id: media-source://mass/database://playlist/1
mode: single
```

I've also tried running the script directly without the automation and I
get a unknown media source error.


looking in the mass folder under custom components I'm not seeing anything
like mass/playlist or /mass/database

one other thing - I'm not seeing the mass.queue_command in the list of services

**Reply by OzGav** [reply]
I will post back here because it is better not to fragment these discussions. Since you are using MA V1 you can also use a built in command as follows which will allow you to just use the playlist name. The following is an automation:
```
  - id: Hannah_alarm_clock
    alias: Hannah Alarm Clock
    trigger:
      platform: time
      at: input_datetime.hannah_alarm_time
    action:
      service: mass.queue_command
      data:
        command: play_media
        uri: "HANNAH Playlist"
        enqueue_mode: play
        radio_mode: false
      target:
        entity_id: media_player.googlehome1382
```

**Reply by OzGav** [reply]
The latest version in HACS is 2023.2.1 so please check the version you advised above? If you are actually using MA V2 beta (the addon) then there is no HA integration yet and this won't work.

**Reply by pjdreger3** [reply]
I hope I'm doing this right. 

In respons to your question 

2023.4.4

Sorry for the confusion I thought you were asking about MASS

**Reply by pjdreger3** [reply]
I installed the version available from HACS

**Reply by pjdreger3** [reply]
Which is 2023.2.1

**Reply by pjdreger3** [reply]
The 2023.4.4 is my HASS version

**Reply by OzGav** [reply]
Yes I was but your issue is that MA v1 which is currently on HACS is not compatible with HA >= 2023.3.x https://github.com/music-assistant/hass-music-assistant/issues/1143

**Reply by pjdreger3** [reply]
Thanks for your patience.  I thought the version I had installed was the beta.

**Reply by OzGav** [reply]
https://github.com/music-assistant/hass-music-assistant/issues/1143#issuecomment-1467921786 how to install the beta is here

**Reply by pjdreger3** [reply]
Thanks for the pointer. Turns out I had both the HACS version and the better installed. Deleted the HACS version now I have just the beta.

**Reply by OzGav** [reply]
Great. A couple of weeks and the HA integration will be written and these automations will work again

**Comment by fliespl** [comment]
So what is currently supported way to do it in v2?

I am getting unknown media source using following in b32.

```
      - service: media_player.play_media
        target:
          entity_id: media_player.nest_salon
        data:
          media_content_id: media-source://mass/database://playlist/1
          media_content_type: playlist
          enqueue: replace
        metadata:
          title: kolysanki
          thumbnail: null
          media_class: playlist
          children_media_class: track
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://mass
            - media_content_type: music
              media_content_id: media-source://mass/playlists
            - media_content_type: audio/flac
              media_content_id: media-source://mass/database://playlist/1
```

**Reply by OzGav** [reply]
Just use the mass.queue_command service call. See the FAQs. https://github.com/orgs/music-assistant/discussions/710

**Reply by fliespl** [reply]
@OzGav there is no mass.queue_command service available in v2 for me (b32).

**Reply by MarvinSchenkel** [reply]
Make sure to install the integration via HACS and add the integration to your Home Assistant.

**Reply by fliespl** [reply]
@marcelveldt are you sure? One of the steps for update was to delete it from HACS and use only addons page... I am talking about v2 BETA.

**Reply by MarvinSchenkel** [reply]
The beta version of the HA integration for MA2 has been released. Make sure to enable 'beta releases' in HACS and select 2023.6.0.

**Reply by fliespl** [reply]
Thanks @MarvinSchenkel. I am curious - there are no mass_ speakers now. Anything changed on this subject? I can see some with _2 prefix - are those to be used for automations with MASS?

**Reply by MarvinSchenkel** [reply]
Probably yes. To view which devices are related to MA, just go to integrations and see which entities are related to MA

(Typo edited by Gav)

**Comment by PatrikPatrik2** [comment]
I have installed the latest beta through Hacs.
I want to have a script that start a playlist in Tidal:


service: mass.queue_command
data:
  command: play_media
  uri: Chill i solen
  enqueue_mode: play
  radio_mode: false
  player_id: media_player.shield_2

I get this error when I run the script:
'Music' object has no attribute 'get_playlists'

What have I made wrong?

**Reply by OzGav** [reply]
Can you please format your yaml properly using the <> button. Also please read the FAQ and try using the normal HA service calls. This might be a bug but let’s try this first

**Reply by PatrikPatrik2** [reply]
```
alias: New Script
sequence:
  - service: mass.queue_command
    data:
      command: play_media
      uri: Chill i solen
      enqueue_mode: play
      radio_mode: false
      player_id: media_player.shield_2`
```

Which resulted in:
'Music' object has no attribute 'get_playlists'

I tried this, which I hope is a normal HA service call

```
service: media_player.play_media
target:
  entity_id: media_player.shield_2
data:
  media_content_id: Chill i solen
  media_content_type: music
```
then I got the same error code:
'Music' object has no attribute 'get_playlists'

However, if I cut the power to my media player, then HA state that the script was sucessfully run.
