### DISCUSSION TITLE
Can you clear the queue when adding a new playlist?

### DISCUSSION THREAD

**Discussion by nthulke** [music-assistant/support#874] [Q&A] [answered]
Hi,
I just wanted to know if there is an ability to clear the current queue of songs playing witout opening the queue and selecting C"lear all items in queue"? 

If this can be scripted then I can add my playlist scripts to clear first before adding in a new set of tracks.

Thanks for any help on this, if I can do this I can sell this method to my better half haha!

**Comment by marcelveldt** [comment, marked as answer]
You can use the "mass.queue_command" service for that

**Comment by heinzma** [comment]
This should work:
```
alias: clear music assistant queue
sequence:
  - service: mass.queue_command
    data:
      command: clear
    target:
      entity_id: media_player.mass_muse_luxe
mode: single
```

**Reply by Mincka** [reply]
For anyone having a look at this, the correct service call is with `player_id` now:

Clear and add a playlist:
```yaml
  - service: mass.queue_command
    data:
      command: clear
      player_id: media_player.mass_muse_luxe
  - service: media_player.play_media
    target:
      entity_id: media_player.mass_muse_luxe
    data:
      media_content_id: spotify:playlist:xxxxxxxxxxxxxxx
      media_content_type: music
```
