### DISCUSSION TITLE
Switch to skip/mute tts notifications/anouncements

### DISCUSSION THREAD

**Discussion by flecmart** [music-assistant/support#952] [Feature requests and ideas]
Hi there,

first of all thank you for this great tool :-) I discovered it through the "Let's get loud stream" and I try to integrate this into my setup now because I never found a way to reliably continue my music streams after tts notifications.

I have implemented a global input_boolean that allows me to silent tts notificaions (e.g if I am not at home or I have guests that would be annoyed :D). The way I implemented it seems to interfere with the implementation of the volume increase mechanism in mass. I would like to have a switch per mass_media_player that allows me to discard incoming tts announcements. Is there allready a way of doing?

**Comment by OzGav** [comment]
I haven't heard of a way to do this but I would suggest you show how you have implemented it so far and provide some more detail about what you mean by it interefering with the "volume increase mechanism"

**Comment by flecmart** [comment]
Okay, let me try to explain... it is a bit complicated:

First of all I have setup some notifiers in homeassistant:

```yaml
notify:
  - name: all_mobile_devices
    platform: group
    services:
      - service: mobile_app_martin
      - service: mobile_app_julia_handy
  - platform: tts
    name: tts
    tts_service: tts.picotts_remote_say
    media_player: media_player.haus
```

so I can use the service call notify.tts to trigger messages being announced through certain media players

for example I use this in automations or alerts:

```yaml
alert:
  door_open:
    name: Front door open
    entity_id: binary_sensor.contact_eingang
    state: "on"
    can_acknowledge: false
    skip_first: true
    repeat: 10
    title: "Haustüre"
    message: "Haustüre ist noch offen!"
    done_message: "Haustüre ist wieder geschlossen."
    notifiers:
      - tts
      - all_mobile_devices
    data:
      channel: alert
      tag: door
```
There are situations where I want to be notified via app but not via tts announcments. I did not find a native way for the alerts to do this in home assistant (probably the easiest way would be if notifiers would just be a switch and could be disabled & enabled... while writing this I feel like this should be a feature request to home assitant core). I kind of hook in all tts events with a node-red automation and change the volumes (increase it or set it to 0 depending on an input boolean):

![image](https://user-images.githubusercontent.com/10167243/196687200-79fce416-d771-4d19-b029-281c295019db.png)

This is what I have ended up now, but it isn't ideal at all and as I said before... tts anouncements always disrupt my media streams. That is why I wanted to try music assistant in the first place. 

After two days of fiddling I figured this project is in a too early stage for me to participate in the moment... I have to take care of two kids and don't have time to fiddle around a lot currently :-) I would love to try some more music assitant in a later stage. 

Since I experimented, my rasperry pi 4 become unresponsive multiple times and I had to do a hard reset for it to come back.  I think it could be related to some long "videos" in my youtube music "Tracks I like" playlist, because I saw some ffmpeg video google related jobs in my htop shortly before it died which maxed out CPU and RAM. In youtube music you can also like video content and have it to play just the sound of it. Could it be that this kind of lets the resource usage of music assitant explode on a raspberry pi?

 I really appreciate the work you put in this project!
