### DISCUSSION TITLE
Programmically adding all items to queue (Shuffle all from script)

### DISCUSSION THREAD

**Discussion by IAmTheMilkManMyMilkIsDelicious** [music-assistant/support#994] [Q&A] [answered]
I'm looking for a way to programmatically add all local filesystem tracks to a queue then shuffle them. I know there's some discussions around adding buttons in the UI to support these features, but I want a way to do it within a hass script.

I can use the mass.queue_command to add an artist or album like this:
```
service: mass.queue_command
data:
  command: play_media
  enqueue_mode: replace
  uri: "Mozart"
target:
  entity_id: media_player.mass_my_media_player
```

I wonder if there's some way to set my uri to all tracks like with `uri: "*"` or just not specifying uri at all, but both of those options fail, anyone know of a way to do it?
