### ISSUE TITLE
Play announcement hangs until other unrelated announcements end

### ISSUE THREAD

**Issue by miguelangel-nubla** [music-assistant/support#3373]
### What version of Music Assistant has the issue?

2.3.4

### What version of the Home Assistant Integration have you got installed?

HA native

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

In latest 2.3.4 playing different announcements to different players act as a queue, new ones will not play until old ones finish.
Working as expected with 2.3.3.

### How to reproduce

```
alias: New automation
description: ""
triggers: []
conditions: []
actions:
  - parallel:
      - action: music_assistant.play_announcement
        target:
          entity_id: media_player.player1
        data:
          url: https://ha/api/tts_proxy/SVpKUPauFcNb0HncR7Wicg.mp3
      - action: music_assistant.play_announcement
        target:
          entity_id: media_player.player2
        data:
          url: https://ha/api/tts_proxy/FUEud_yNiw-XffVjrv8MHg.mp3
mode: single
```

### Music Providers

Announcements from URL with `music_assistant.play_announcement` and `tts.speak`.

### Player Providers

I have tried Squeezelite and Fully kiosk players.

### What version of Home Assistant Core are your running

2024.12.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
