### ISSUE TITLE
Documentation: get_library example does not work

### ISSUE THREAD

**Issue by Vitani** [music-assistant/support#3445]
### What version of Music Assistant has the issue?

2.3.6

### What version of the Home Assistant Integration have you got installed?

2025.1.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The example on the [get_library page of the documentation](https://www.music-assistant.io/faq/get_library/) does not work

```
script:
  create_random_queue:
    mode: single
    sequence:
      - service: music_assistant.get_library
        data:
          limit: 10
          media_type: track
          order_by: random
        response_variable: random_tracks
      - repeat:
          count: "{{ random_tracks | length + 1}}"
          sequence:
            - action: music_assistant.play_media
              data:
                media_id: "{{ random_tracks.items[repeat.index - 1].uri }}"
                media_type: track
                enqueue: add
              target:
                entity_id: media_player.ma_kitchen_speaker
```

I get the error

> Error rendering data template: UndefinedError: builtin_function_or_method object has no element 0

### How to reproduce

1. Copy the example to a new script or automation
2. In the first step, select your Music Assistant Instance
3. In the second step, change the speaker to one of your own
4. Run the script/automation

### Music Providers

Spotify

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2025.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
