### ISSUE TITLE
music_assistant.search seems to prioritize collaborations above the individual artist

### ISSUE THREAD

**Issue by jeroenterheerdt** [music-assistant/support#3459]
### What version of Music Assistant has the issue?

2.4.0b12

### What version of the Home Assistant Integration have you got installed?

n/a (built-in)

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If you use `music_assistant.search` to search for an artist such as 'Joe Cocker' the results prioritize collaborations instead of the individual artist.

### How to reproduce

1. Call service `music_assistant.search` with an artist in your library. For example, I called: 

```
action: music_assistant.search
data:
  limit: 1
  config_entry_id: xyz
  media_type:
    - artist
  name: Joe Cocker
```

2. Notice how if your library contains collaborations by that artist, such as "Joe Cocker and [Someone]", the result will be that instead of what you actually were searching for, the artist itself.
3. If you remove the `limit: 1` you can confirm that indeed the artist itself is returned as well:
```
artists:
  - media_type: artist
    uri: library://artist/1225
    name: Jennifer Warnes & Joe Cocker
    version: ""
    image: null
  - media_type: artist
    uri: plex://artist//library/metadata/171326
    name: Joe Cocker
    version: ""
    image: >-
      http://172.30.32.1:8095/imageproxy?path=/library/metadata/171326/thumb/1736946209&provider=plex--vJGBjSdX&size=0
  - media_type: artist
    uri: library://artist/259
    name: Joe Cocker
    version: ""
    image: >-
      http://172.30.32.1:8095/imageproxy?path=/library/metadata/171326/thumb/1728733967&provider=plex--vJGBjSdX&size=0
  - media_type: artist
    uri: library://artist/1368
    name: Joe Cocker & Jennifer Warnes
    version: ""
    image: null
albums: []
tracks: []
playlists: []
radio: []
```

### Music Providers

plex

### Player Providers

slimproto

### Full log output

[music_assistant.log](https://github.com/user-attachments/files/18433005/music_assistant.log)

### What version of Home Assistant Core are your running

2025.1.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
