### ISSUE TITLE
Global Announcements not resuming music when music is playing in a single Google cast group

### ISSUE THREAD

**Issue by Doug411** [music-assistant/support#3480]
### What version of Music Assistant has the issue?

2.40b18

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

I have 4 Google Cast Receivers (2 Nvidia Shields and 2 Nest Hubs).  I have created 3 speaker groups in  the Google Home app:  All Hubs, All Shields, All Cast (containing all 4 devices.  If I am playing music to the All Hubs Group, and make an announcement to the All Cast Group, the music does not resume

What does Resume Successfully: 
- Playing Music and making Announcement to the same group (eg playing music on All Hubs, making an announcement on All Hubs, or playing Music on All Cast and making an Announcement on All Cast)
- Playing Music to a group and making an Announcement to a speaker directly instead of a group.   (eg playing music on All Cast and making an announcement on Living Room Hub)
- Playing Music to a group and making an unsynced announcement to multiple individual speakers (eg playing music to All Cast and making announcement on Master Bedroom Hub, Living Room Hub, Living Room Shield and Master Bedroom Shield).  Big disadvantage is the announcement is not synced and sounds awful as they all fire off out of sync

Is this a bug?  Can this be addressed?  It seems like a common use case to want to send a synced announcement to the whole house, when there is music playing in just one group.

This is what works but sounds terrible because its out of sync

```
action: tts.speak
metadata: {}
data:
  cache: true
  media_player_entity_id: 
    - media_player.master_bedroom_display_2
    - media_player.kitchen_display_2
    - media_player.master_bedroom_shield_2
    - media_player.living_room_shield
  message: Welcome Home
  language: en-gb
target:
  entity_id: tts.google_en_com
```

### How to reproduce

play music to a group in your home that has a subset of the cast speaker
Play announcement to a group in your home that has all the speakers

action: tts.speak
metadata: {}
data:
  cache: true
  media_player_entity_id: 
    - media_player.all_cast
  message: Welcome Home
  language: en-gb
target:
  entity_id: tts.google_en_com

### Music Providers

Sirius, YTM, Audiobookshelf, Jellyfin, RadioBrowser

### Player Providers

Google Cast

### What version of Home Assistant Core are your running

2025.1.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
