### ISSUE TITLE
Music assistant beta 2.4.0b27 radio favourites missing or unplayable

### ISSUE THREAD

**Issue by limitless-code** [music-assistant/support#3571]
### What version of Music Assistant has the issue?

2.4.0b27

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

After upgrading to Music assistant beta 2.4.0b27 from 2.4.0b25 my radio favourites added from radio browser are missing after a few hours since the update to beta 2.40.b27. when I add another radio favourite to Music assistant it continues from the last added e.g. new favorite is library://radio/18 instead of library://radio/1

The reason I am using the beta version seems here   https://github.com/home-assistant/core/issues/134989

Issue originally post here:

https://github.com/home-assistant/core/issues/138416

### How to reproduce

Automation snippet from home assistant below along with with MA 2.4.0b27 or 28

```
choose:
  - conditions:
      - condition: trigger
        id:
          - Play Classic F-M
    sequence:
      - action: media_player.play_media
        target:
          entity_id: " {{ (voice_assistant_device) }} "
        data:
          media_content_id: library://radio/1
          media_content_type: music
        metadata:
          title: Classic FM (UK)
          thumbnail: https://www.classicfm.com/assets_v4r/classic/img/favicon-196x196.png
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: music_assistant
              media_content_id: radio
        enabled: true
```

### Music Providers

Radio Browser 

### Player Providers

Home assistant MediaPlayers 

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/18800026/music-assistant.log)

### Additional information

After adding a new radio station library://radio/18 I tried restarting the Music Assistant add-on but nothing changed. The next day I rebooted HASSIO and all radio stations came back however they have been added starting from library://radio/18 which was added after the other radio stations disappeared.

Also the meta data has now disappeared so the media player is not showing what is playing in either the home assistant entity or the media player in Music Assistant.

### What version of Home Assistant Core are your running

2025.2.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
