### ISSUE TITLE
HA: Using media_player.join results in unusual data in media_player.group_members

### ISSUE THREAD

**Issue by msm595** [music-assistant/support#3651]
# What version of Music Assistant has the issue?

2.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

# The problem

The MA integration in HA seems to be incorrectly reporting the `group_members` attribute for `media_player` entities when using temporary sync groups. These `group_members` are listed in alphabetical order instead of being listed with the "master" player in the first position of this list.

Here are two different media player cards implementations, both of which check the first member of the media_player entity's `group_members` attribute to determine if a player is the "master" one in a group:

1. [custom-sonos-card aka maxi-media-player](https://github.com/punxaphil/custom-sonos-card/blob/3f009218530be4d84b6ecd0b3fd79bd54ae215df/src/model/store.ts#L155)
2. [mini-media-player](https://github.com/kalkih/mini-media-player/blob/c2ff27ff000be808335b78fe7c7623a0d14c19ca/src/model.ts#L125-L127)

Because of this incorrect listing, both cards show buggy or incorrect information when trying to group players or play media for a group.

# How to reproduce

## Main Reproduction Steps

1. Join two Sonos players to Music Assistant
2. Name one "Bar" and the other "Pizza Oven". The names do not matter, just make sure it is clear which one comes first alphabetically.
3. Set up the MA integration in HA.
4. Use MA to start playing music on "Pizza Oven" (the one that comes later alphabetically), then add "Bar" using the checkbox in MA.
    ![Image](https://github.com/user-attachments/assets/7f1485b9-69be-4423-94c0-1f3176d14333)
5. Set up `maxi-media-player` in HA with the two entities:
    ```yaml
      type: custom:maxi-media-player
      sections:
        - player
        - volumes
        - grouping
        - groups
      startSection: player
      entities:
        - media_player.bar
        - media_player.pizza_oven
      entityId: media_player.pizza_oven
      adjustVolumeRelativeToMainPlayer: true
      hidePlayerControlPowerButton: true
      showAudioInputFormat: true
      hideVolumeCogwheel: true
      ```
6. Observe `maxi-media-player` refuse to show or select the "Pizza Oven" source:
    ![Image](https://github.com/user-attachments/assets/774ab714-9705-4f81-8895-c916e4a980a0)
7. Observe `maxi-media-player` refuse to show `media_player.pizza_oven` in it's join/unjoin page:
    ![Image](https://github.com/user-attachments/assets/b57f0715-7704-4180-a9d4-28bf616e3bf9)
8. Observe in HA's developer tools that the value of `media_player.pizza_oven`'s `group_members` attribute is `media_player.bar, media_player.pizza_oven` (master is last) instead of `media_player.pizza_oven, media_player.bar` (master player first in list).

## Additional Errors
The above demonstrates the weirdness that occurs when the "master" player is not listed first in the `group_members` list. So when we set up conditions in our favor, such that the alphabetically listing also has the "master" player first, I will show the intended behavior.

Though there is still one issue in this case as well.

1. Join two Sonos players to Music Assistant
2. Name one "Bar" and the other "Pizza Oven". The names do not matter, just make sure it is clear which one comes first alphabetically.
3. Set up the MA integration in HA.
4. Use MA to start playing music on "Bar" (the one that comes first alphabetically), then add "Pizza Oven" using the checkbox in MA.
    ![Image](https://github.com/user-attachments/assets/4eb4d16a-03d8-4fef-8d87-fa7ffae9e672)
5. Set up `maxi-media-player` in HA with the two entities:
    ```yaml
      type: custom:maxi-media-player
      sections:
        - player
        - volumes
        - grouping
        - groups
      startSection: player
      entities:
        - media_player.bar
        - media_player.pizza_oven
      entityId: media_player.bar
      adjustVolumeRelativeToMainPlayer: true
      hidePlayerControlPowerButton: true
      showAudioInputFormat: true
      hideVolumeCogwheel: true
      ```
6. Observe that `maxi-media-player` does allow you to control the "Bar" media player and additionally shows that "Pizza Oven" is synced as well:
    ![Image](https://github.com/user-attachments/assets/722610e4-190d-45ea-afa3-9479a34d5f3a)
7. But observe on the join/unjoin page that "Pizza Oven" is listed twice!
    ![Image](https://github.com/user-attachments/assets/3e960f41-3db3-47ff-ae34-cb127c123652)
8. Additionally observe that the value of `media_player.bar`'s `group_members` attribute is an empty string instead of `media_player.pizza_oven, media_player.bar` (showing bar is in a group, but not the master player).

# Music Providers

In this case, I was testing out with the Plex Music Provider, but the error also occurs when no music is playing or queued at all. The issue is a data syncing issue with Home Assistant.

# Player Providers

I've tried this with the Sonos player provider only. Unfortunately I do not have access to other players. As stated, this was tested using Temporary Sync groups.

# Full log output

N/A

# Additional information

The reproduction steps show the problem when playback is initiated in MA's UI. But I have observed this very same incorrect data in the entity attributes when using the `media_player.join` and `media_player.unjoin` actions from HA as well.

# What version of Home Assistant Core are your running

2025.2.5

# What type of installation are you running?

Home Assistant Container

# On what type of hardware are you running?

Linux
