### ISSUE TITLE
New ESPHome Media Player (media_pipeline) not working in Music Assistant

### ISSUE THREAD

**Issue by GSVil** [music-assistant/support#3687]
### What version of Music Assistant has the issue?

2.4.3 and 2.4.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

Because of issues with the original ESPHome Media Player functionality I created a new ESPHome Media Player using the new functionality to see Music Assistant handles it better. It does not work, there appears to be a communication problem between Music Assistant Server and the added ESPHome Media Player. Broadcasts work, its the media_pipeline that is not working.  I also noticed that I cant change the "HTTP profile" or the "Codec" for the added speaker in Music Assistant. In the original ESPHome Media Player I changed these to "Chunked" and "MP3" to get it working, but as its not available I cant experiment.

### How to reproduce

1) Create an ESPHome Media Player using the new Media Player functionality:

################################################################################
# Audio and MediaPlayer
################################################################################

```
i2s_audio:
  - id: i2s_speaker
    i2s_lrclk_pin: GPIO6 #LRC Pin of the MAX98357A Audio Amplifier
    i2s_bclk_pin: GPIO7  #BCLK Pin of the MAX98357A Audio Amplifier

speaker:
  - platform: i2s_audio
    id: speaker_id
    i2s_audio_id: i2s_speaker
    dac_type: external
    i2s_dout_pin: GPIO8   #  DIN Pin of the MAX98357A Audio Amplifier
    channel: mono
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input

media_player:
  - platform: speaker
    name: "Media Player"
    id: media_player_id
    media_pipeline:
        speaker: media_spk_mixer_input
        num_channels: 1
    announcement_pipeline:
        speaker: announcement_spk_mixer_input
        num_channels: 1
```

2) Add the ESPHome Media Player to Music Assistant using the the "Home Assistant Player" provider
3) Try streaming music to the player, nothing appears to happen. Lots of errors in the logs.

### Music Providers

Spotify & PLEX

### Player Providers

Home Assistant Media Players

### Full log output

[d5369777_music_assistant_2025-03-08T16-53-11.907Z.log](https://github.com/user-attachments/files/19144840/d5369777_music_assistant_2025-03-08T16-53-11.907Z.log)

### Additional information

![Image](https://github.com/user-attachments/assets/2ac9a170-97ff-4177-a9bd-8a5c9ef7abef)

### What version of Home Assistant Core are your running

2025.3.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes
