### ISSUE TITLE
Crash on start after "Permission denied: '/.audio'"

### ISSUE THREAD

**Issue by I-G-1-1** [music-assistant/support#3791]
### What version of Music Assistant has the issue?

2.5.0b16 - 2.5.0b17 - 2.5.0b18

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

Hi, 

starting  from beta version 2.5.0b16 I get this error and music assistant crashes

```
music-assistant-server  | 2025-03-28 17:05:26.232 INFO (MainThread) [music_assistant] Starting Music Assistant Server (REDACTED) version 2.5.0b18 - HA add-on: False - Safe mode: False
music-assistant-server  | 2025-03-28 17:05:26.266 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
music-assistant-server  | 2025-03-28 17:05:26.306 DEBUG (MainThread) [music_assistant.cache] Compacting database...
music-assistant-server  | 2025-03-28 17:05:26.333 DEBUG (MainThread) [music_assistant.cache] Compacting database done
music-assistant-server  | 2025-03-28 17:05:26.339 DEBUG (MainThread) [music_assistant.cache] Running automatic cleanup...
music-assistant-server  | 2025-03-28 17:05:26.446 DEBUG (MainThread) [music_assistant.cache] Automatic cleanup finished (cleaned up 0 records)
music-assistant-server  | 2025-03-28 17:05:26.467 INFO (MainThread) [ffmpeg] Detected ffmpeg version 7.1 with libsoxr support
music-assistant-server  | 2025-03-28 17:05:31.780 ERROR (MainThread) [music_assistant] Error doing task: Task exception was never retrieved
music-assistant-server  | Traceback (most recent call last):
music-assistant-server  |   File "/app/venv/lib/python3.12/site-packages/aiorun/__init__.py", line 223, in new_coro
music-assistant-server  |     await coro
music-assistant-server  |   File "/app/venv/lib/python3.12/site-packages/music_assistant/__main__.py", line 214, in start_mass
music-assistant-server  |     await mass.start()
music-assistant-server  |   File "/app/venv/lib/python3.12/site-packages/music_assistant/mass.py", line 170, in start
music-assistant-server  |     await self.streams.setup(await self.config.get_core_config("streams"))
music-assistant-server  |   File "/app/venv/lib/python3.12/site-packages/music_assistant/controllers/streams.py", line 260, in setup
music-assistant-server  |     await asyncio.to_thread(os.makedirs, self._audio_cache_dir)
music-assistant-server  |   File "/usr/local/lib/python3.12/asyncio/threads.py", line 25, in to_thread
music-assistant-server  |     return await loop.run_in_executor(None, func_call)
music-assistant-server  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
music-assistant-server  |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
music-assistant-server  |     result = self.fn(*self.args, **self.kwargs)
music-assistant-server  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
music-assistant-server  |   File "<frozen os>", line 225, in makedirs
music-assistant-server  | PermissionError: [Errno 13] Permission denied: '/.audio'
```

I'm running MusicAssistant on docker as non privileged user (as already explained [here](https://github.com/music-assistant/support/issues/2956#issuecomment-2382511984) for an old fixed issue), and it seems a permission problem.

I think could be related to [this](https://github.com/music-assistant/support/issues/2956) resolved issue.

The last working version is 2.5.0b15

Thanks

### How to reproduce

1. update the docker container to 2.5.0b16  or 2.5.0b17 or 2.5.0b18
2. force recreation of the container (sudo /usr/bin/docker compose up --force-recreate)
3. get the error

### Music Providers

none

### Player Providers

Chromecast

### Full log output

Cannot download from MA SETTINGS>>CORE, MusicAssistant crash on start.

### Additional information

HomeAssistant running on raspberry pi. MusicAssistant running on different x86-64 machine.

### What version of Home Assistant Core are your running

2025.03.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
Confirm the docker container has been installed with all of the privileges required as documented here https://www.music-assistant.io/installation/#docker-image

**Comment by jojo141185** [comment]
I encounter the same PermissionError when attempting to run the latest beta Docker container (v2.5.0b18) of Music Assistant with a non-privileged user. All settings from the official [installation documentation](https://www.music-assistant.io/installation/#docker-image) have been applied. 
Downgrading to the previous beta version (2.5.0b15) resolves the issue.

**Comment by OzGav** [comment]
You must be doing something different as thousands of people run this in docker

**Comment by marcelveldt** [comment]
Can you check if 2.5.0 BETA 19 resolves the issue ?

**Comment by I-G-1-1** [comment]
@marcelveldt Infinitely thank you.. now it works!

Here is how I normally run MusicAssistant, as I don't need MusicAssistant to mount any SAMBA share I didn't use `SYS_ADMIN` and `DAC_READ_SEARCH` and I run it as `musicassistant` user.

```
services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:beta # <<< Desired release version here (change beta to latest once there is a stable release)
    container_name: music-assistant-server
    user: 1001:1001 # musicassistant should be owner of volumes
    ports:
      - "8095:8095"
      - "8098:8098"
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - /home/pi/.config/musicassistant/data:/data/
    # privileged caps needed to mount smb folders within the container
    #cap_add:
      #- SYS_ADMIN #<-- I don't need this, I mount my SAMBA share system wide. But tried with this enable still not working
      #- DAC_READ_SEARCH
    #privileged: true
    privileged: false
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug, verbose)
      - LOG_LEVEL=info
```


> You must be doing something different as thousands of people run this in docker

@OzGav I'm extremely grateful for your time, your work, your suggestions and the piece of software you and the other developer are gifting us, but please for the future change attitude. 
It seem that for you is always end user fault! Yes @jojo141185 and I for security reason don't run this docker whit the root user as the other thousand of people (as already explained in the issue i linked), but It's really very difficult to get to the bottom of an issue with this attitude.

Again thanks @marcelveldt to fix this issue!
