### ISSUE TITLE
Unable to play directly to a speaker that was part of a group using the Home Assistant integration

### ISSUE THREAD

**Issue by brian-maher** [music-assistant/support#3842]
### What version of Music Assistant has the issue?

2.6.0b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

When using grouped players with the Home Assistant integration it is impossible to play music directly to a speaker that has been playing as part of a group. No combination of clearing queues, etc, seems to make this work. The group/ungroup functionality doesn't appear to work correctly when using `music_assistant.play_media`.

Before the group changes, this was consistently possible using `media_player.turn_off` and `media_player.clear_playlist`

#### Setup

- Create 2 AirPlay Players: Player A, Player B
- Create 1 AirPlay PlayerGroup: Group A
- Add Player A + Player B to Group A.
- Disable Dynamic Group membership (doesn't make a difference really but it's less confusing for the purpose of testing)

#### Test

- Play Music on Group A:
```
action: music_assistant.play_media
metadata: {}
data:
  media_type: playlist
  enqueue: replace
  media_id: 9
target:
  entity_id: media_player.group_a
```
- Clear Queues 
```
action: media_player.clear_playlist
metadata: {}
data: {}
target:
  entity_id:
    - media_player.player_a
    - media_player.group_a

```
- Play Music on Player A:
```
action: music_assistant.play_media
metadata: {}
data:
  media_type: playlist
  enqueue: replace
  media_id: 9
target:
  entity_id: media_player.player_a
```

#### Expected Outcome:

Music plays on Player A.

#### Actual Outcome:

Behaviour appears to vary based on whether Player A happened to be the group leader whilst playing on the group. Usually, it will either:

1. Continue playing on the group
2. Occasionally play on Player A (I think this is when Player B was the group leader, but not 100% certain)
3. Play for a couple of seconds on the group then just stop.

If (3) occurs, playing media on Player A a second time usually works.

Using join/unjoin and dynamic groups does not solve the issue, and using fake power controls appears to work, but when playing to a group again it refuses to power the speaker back on.

### Music Providers

Tested Spotify + Deezer 

### Player Providers

Issue occurs with AirPlay and Sonos.

### Full log output

[music-assistant.log.log](https://github.com/user-attachments/files/19639281/music-assistant.log.log)

### Additional information

No unusual networking, etc, and this was all working up to 2.2.3.

### What version of Home Assistant Core are your running

2025.3.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes
