### ISSUE TITLE
Docker Image version of 2.5.1 reports error in `finish_response` noting `resp.prepare` as 'bool' object has no 'prepare'

### ISSUE THREAD

**Issue by jrconlin** [music-assistant/support#3873]
### What version of Music Assistant has the issue?

2.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

I am running the docker image of Music Assistant Server (5e733041a2c145aba6f47b741d84a924). 

When I attempt to play music to a chromecast group Player, Music Assist silently fails to play the track. It is able to play the track to individual devices. See the attached log for details. 

I do not see this error when running the docker image for 2.5.0, nor do I see it when running locally using the `dev` branch outside of docker. 

I suspect that there may be an error in the Docker image build for 2.5.1 which is causing the failure. 

### How to reproduce

1) Start Music Assistant with the following docker compose file:

```
services:
  music-assistant-server:
    #image: ghcr.io/music-assistant/server:stable # <<< Desired release version here (or use beta to get the latest beta version)
    image: ghcr.io/music-assistant/server:2.5.1 # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - ${USERDIR:-$HOME}/data:/data/
      - /home/music:/music
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - PORT=4095
      - LOG_LEVEL=info
```
(`debug` does not appear to give a deeper backtrace for this.)

2) Select a Chromecast Group containing more than one device.

3) Select an individual track or playlist and click "Play".

No music is played. Error is logged.

### Music Providers

* Filesystem
* Music Assistant

### Player Providers

* Chromecast
* Music Assistant
* Playergroup

### Full log output

[musicassist.log](https://github.com/user-attachments/files/19727924/musicassist.log)

### Additional information

I am running MusicAssist on a different machine than my HomeAssistant. 

### What version of Home Assistant Core are your running

2025.3.0

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes
