### ISSUE TITLE
Get Library search unreliable

### ISSUE THREAD

**Issue by jorbig** [music-assistant/support#3943]
### What version of Music Assistant has the issue?

2.6.0b5 & 2.5.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

With this action:

```
action: music_assistant.get_library
data:
  config_entry_id: 01JS2BHC9PB00EWJZ7C9D42MMH
  media_type: album
  search: Kinderboeken
  limit: 1
  offset: 0
  order_by: random
response_variable: random_album
```

I sometimes correctly get a response like this:

```
items:
  - media_type: album
    uri: library://album/1
    name: Abeltje
    version: ""
    image: null
    artists:
      - media_type: artist
        uri: library://artist/317
        name: Kinderboeken
        version: ""
        image: null
limit: 1
offset: 0
order_by: random
media_type: album
```

But very often (I'd say it's about fifty-fifty) I get this:
```
items: []
limit: 1
offset: 0
order_by: random
media_type: album
```

When I leave the search part out, it never returns an empty response.
Could you please confirm and solve this bug? Thanks in advance!

### How to reproduce

See above.

### Music Providers

Filesystem localhost

### Player Providers

Doesn't matter.

### Full log output

I don't think this is necessary here.

### Additional information

None.

### What version of Home Assistant Core are your running

2025.4.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Windows

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
This item is already on the backlog. I believe it has to do with the order the filters are applied. If you don’t use random it would work fine.

**Comment by jorbig** [comment]
The issue isn't solved. When using the 'Search' parameter, the search happens after getting the item(s), but it should happen before, so it will always return an item even when limiting the results to 1. Currently it will often still return empty responses in the example of my first post.

**Comment by OzGav** [comment]
The item is still on the backlog.

**Comment by jorbig** [comment]
It is said to be fixed, but the issue remains with 2.6.0b14:

> The issue isn't solved. When using the 'Search' parameter, the search happens after getting the item(s), but it should happen before, so it will always return an item even when limiting the results to 1. Currently it will often still return empty responses in the example of my first post.

Again, the problem is only happening when using 'search'.

**Comment by OzGav** [comment]
This is now working fine for me

```
action: music_assistant.get_library
data:
  config_entry_id: 01JMYCMQJ55CR9E7YZW3VKEA4F
  media_type: album
  limit: 1
  order_by: random
  search: live
```
