### ISSUE TITLE
Error: Entity <entity name> does not support action media_player.volume_set

### ISSUE THREAD

**Issue by limitless-code** [music-assistant/support#3967]
### What version of Music Assistant has the issue?

2.6.0b6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

Not sure where the problem is. MA, HA or the Voice PE devices I am using so posting here first. It used to work.

When triggering an automation I get the following error for various media player actions. volume_set, volume_mute, volume_umute all fail with the same error
```
Error: Entity media_player.small_bedroom_assistant_media_player does not support action media_player.volume_set
```

However media_player.media_pause works.

In the logs it refers to:

```media_player.home_assistant_voice_0974ab_media_player/Small Bedroom assistant Media Player```

But the entity id used in the automation is:

```media_player.small_bedroom_assistant_media_player```

I can increase and decrease volume using the MA webui in HA.

### How to reproduce

HA core 2025.5.0
MA 2.6.0b6

Use MA entity id

Use the following automation 

```
alias: Voice assistant controls
description: ""
triggers:
  - trigger: conversation
    command:
      - (stop|top|shut up)
      - Top [playing] [media] [player]
      - Stop [playing] [media] [player]
    id: Stop
  - trigger: conversation
    command:
      - Pause [(media|player)]
    id: Pause
  - trigger: conversation
    command:
      - "[Set] (volume|sound) [to] (1|5|10|15|20|30|40|50|60|70|80|90|100)"
    id: Volume
    variables:
      volume_level_sentence: " {{ trigger.sentence }} "
      volume_level: " {{ (volume_level_sentence) |regex_findall('\\d+')|first|int|multiply(0.01) }} "
      volume: " {{ (volume_level) }} "
  - trigger: conversation
    command:
      - (Mute|nute)
    id: mute
  - trigger: conversation
    command:
      - (unmute|unnute)
    id: unmute
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Stop
        sequence:
          - action: media_player.media_stop
            metadata: {}
            data: {}
            target:
              entity_id: " {{ (voice_assistant_device) }} "
      - conditions:
          - condition: trigger
            id:
              - Pause
        sequence:
          - action: media_player.media_pause
            metadata: {}
            data: {}
            target:
              entity_id: " {{ (voice_assistant_device) }} "
      - conditions:
          - condition: trigger
            id:
              - Volume
        sequence:
          - action: media_player.volume_set
            metadata: {}
            data:
              volume_level: " {{ (volume) }} "
            target:
              entity_id: " {{ (voice_assistant_device) }}  "
      - conditions:
          - condition: trigger
            id:
              - mute
        sequence:
          - action: media_player.volume_mute
            metadata: {}
            data:
              is_volume_muted: true
            target:
              entity_id: " {{ (voice_assistant_device) }} "
            enabled: true
      - conditions:
          - condition: trigger
            id:
              - unmute
        sequence:
          - action: media_player.volume_mute
            metadata: {}
            data:
              is_volume_muted: false
            target:
              entity_id: " {{ (voice_assistant_device) }} "
            enabled: true
variables:
  media_player_id: " {{ trigger.device_id }} "
  media_player: " {{ device_entities(media_player_id) |select('search','^media_player.')|first }} "
  friendly_name: " {{ states[media_player]['attributes']['friendly_name'] }} "
  prepend: media_player.
  voice_assistant_device: " {{ prepend ~ (friendly_name) | slugify}} "
mode: parallel
max: 5
```

### Music Providers

Not relevant music providers are working perfectly.

### Player Providers

I don't think this is relevant? As above regarding music providers?

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/20093485/music-assistant.log)

### Additional information

Volume can be controlled in the UI but via automation actions some media player actions fail.

### What version of Home Assistant Core are your running

2025.5.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes
