### ISSUE TITLE
Shorter files played from URL for announcements not playing via snapcast

### ISSUE THREAD

**Issue by bbrennan1301** [music-assistant/support#4008]
### What version of Music Assistant has the issue?

2.5.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

Shorter audio files being played via URL for announcements triggered by a Home Assistant automation won't play via two snapcast players. For example, I have Music Assistant 2.4.4 playing a chime sound when external doors or windows are opened. The sound file is only 1 second long. This works fine. However, when I upgrade to 2.5.2, it's as if the player doesn't start outputting sound until after the sound has been played. 

My automation is set up to run the announcement over two players in parallel, which works in 2.4.4, but 2.5.2 seems to play them in sequence as confirmed by a test, replacing the short sound file URL with a longer one in the automation. (This is another issue in 2.5.2 that isn't in 2.4.4. Please let me know if I should submit this as a separate issue.) Sometimes I'll hear the very end of the chime on the second player, but not every time, leading me to believe the sound is being streamed to the players before the players are initialized to play it.

I've also tried adding silence to the beginning of the sound file to make it play longer. However this doesn't work. It seems the players are initialized, but delayed only when there is an audio signal present.

Here is the yaml for my automation:

```
alias: Smart Speaker - Notification - Balcony Door Chime
description: >-
  Plays a chime sound through both smart speakers when the balcony door is
  opened.
triggers:
  - entity_id:
      - binary_sensor.balcony_door_sensor_opening
    to: "on"
    from: null
    trigger: state
conditions: []
actions:
  - parallel:
      - data:
          url: http://192.168.1.180:8123/local/notifications/Door Chime.wav
        action: music_assistant.play_announcement
        target:
          entity_id: media_player.minixz64_livingroom
      - data:
          url: http://192.168.1.180:8123/local/notifications/Door Chime.wav
        action: music_assistant.play_announcement
        target:
          entity_id: media_player.minix_z64_master_bedroom
mode: single
```

My snapcast players are x86-64 devices running Ubuntu 24.04.1 LTS. I'm currently running snapclient 0.27.0 revision 54a3d862, which seems to be the newest version available in the Ubuntu repositories for this distro.

### How to reproduce

Run the automation stated above on Music Assistant 2.5.2 with a sound file that is 1 second long. There is also a delay in playing at the beginning of longer audio files.

### Music Providers

I use Tidal with Music Assistant, but the source for this issue is a file on my local network.

### Player Providers

Snapcast. These players are not grouped, but the automation is set to run in parallel, so they should play at the same time. However, they do not in Music Assistant 2.5.2. They play in sequence instead, which is not the behaviour witnessed in 2.4.4.

### Full log output

[music-assistant-2.4.4-successful-playback.log](https://github.com/user-attachments/files/20432164/music-assistant-2.4.4-successful-playback.log)

[music-assistant-2.5.2-unsuccesful-playback.log](https://github.com/user-attachments/files/20432165/music-assistant-2.5.2-unsuccesful-playback.log)

### Additional information

I ran the automation three times previous to outputting the logs above. Both while on 2.4.4, which worked, and after a recent upgrade to 2.5.2, which did not work.

### What version of Home Assistant Core are your running

2025.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes
