### ISSUE TITLE
ERROR: [youtube+GetPOT] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats

### ISSUE THREAD

**Issue by cvigo** [music-assistant/support#4010]
### What version of Music Assistant has the issue?

2.5.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

YouTube music integration shows this error

<img width="395" alt="Image" src="https://github.com/user-attachments/assets/fd86a298-962e-4afa-9e91-8f2d4092b37e" />

I thought it might be related to the cookie, so I got a new one, but when I save the configuration, the same error appears.

The log doesn't say much more:

``` 
2025-05-25 20:49:07.256 DEBUG (MainThread) [music_assistant.ytmusic] Log level configured to DEBUG
2025-05-25 20:49:07.259 DEBUG (MainThread) [music_assistant.ytmusic] PO Token server responded with 200
2025-05-25 20:49:09.288 ERROR (MainThread) [music_assistant.webserver] Error handling message: config/providers/save: ERROR: [youtube+GetPOT] dQw4w9WgXcQ: Requested format is not available. Use --list-formats for a list of available formats
```

### How to reproduce

Nothing special, just save the YouTube Music provider settings

### Music Providers

- YouTube music does not work
- TuneIn works

### Player Providers

All providers are working:
- Chromecast
- Sonos

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/20432684/music-assistant.log)

### Additional information

I am in Docker setup, with this compose:

```
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest # <<< Desired release version here (or use beta to get the latest beta version)
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/music-assistant-server/data:/data/
    # privileged caps (and security-opt) needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug)
      - LOG_LEVEL=info
```

PO Token Server run in Docker at:
http://127.0.0.1:4416

### What version of Home Assistant Core are your running

2025.5.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes
