### ISSUE TITLE
TTS playback via Home Assistant frequently fails due to "announcement in progress" lock

### ISSUE THREAD

**Issue by joopdo** [music-assistant/support#4051]
### What version of Music Assistant has the issue?

2.5.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

I'm a new Music Assistant user -thanks for the great solution! I'm using Music Assistant together with Home Assistant for two purposes (local) media playback and TTS announcements from Homeassistant in a combined SnapCast server (SnapCast server from Music Assistant). I send TTS messages via the tts.speak service to a media player (media_player.tts) that maps to a Snapcast player group in Music Assistant.

However, when sending a TTS message (using cache: true) while a previous announcement is still considered "in progress", the playback fails. This happens often even when there is no active media playing anymore — the system seems stuck in some kind of internal announcement lock.

I'd like to be able to override or interrupt any "announcement in progress" when a new TTS message is issued.

### How to reproduce

1. Set up a Snapcast group as a player in Music Assistant.
2. Use Home Assistant to send a TTS message via tts.speak to a media_player exposed by Music Assistant.
3. Next I'm not completely sure, it's a mix of playing music but not on media.tts, that is on another music player called media.livingroom
4. Attempt to send another TTS message shortly after.
5. Observe the second one often fails due to an "announcement in progress" lock, even if playback has already stopped.

```music-assistant-server    | 2025-06-14 18:50:52.509 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue tts - crossfade: disabled
music-assistant-server    | 2025-06-14 18:50:52.537 ERROR (MainThread) [music_assistant.audio.media_stream] Error while streaming builtin://track/http://homeassistant.local/local/localmp3/trumpet.mp3: No audio was received
music-assistant-server    | 2025-06-14 18:50:52.537 WARNING (MainThread) [music_assistant.audio.media_stream] Output #0, f32le, to 'pipe:':
music-assistant-server    | Metadata:
music-assistant-server    | Software        : Lavf60.3.100
music-assistant-server    | encoder         : Lavf61.7.100
music-assistant-server    | Stream #0:0: Audio: pcm_f32le, 48000 Hz, stereo, flt, 3072 kb/s
music-assistant-server    | Metadata:
music-assistant-server    | encoder         : Lavc61.19.100 pcm_f32le
music-assistant-server    | [out#0/f32le @ 0x7bd4b241d980] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
music-assistant-server    | [out#0/f32le @ 0x7bd4b241d980] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
music-assistant-server    | size=       0KiB time=N/A bitrate=N/A speed=N/A
music-assistant-server    | 2025-06-14 18:50:52.537 INFO (MainThread) [music_assistant.streams] Finished Queue Flow stream for Queue tts
music-assistant-server    | 2025-06-14 18:53:07.693 WARNING (MainThread) [music_assistant.player_queues] Ignore queue command: An announcement is in progress
````

### Music Providers

1. Built-in
2. iTunes Podcasts
3. Local filesystem
4. RadioBrowser

No issues observed here.

### Player Providers

1. Snapcast
2. Home Assistant players
3. Player group (Snapcast sync group used for TTS)

Problem observed when targeting Snapcast-based group via Home Assistant.

### Full log output

[log.log](https://github.com/user-attachments/files/20739929/log.log)

### Additional information

````
- service: tts.speak
  data:
    cache: true
    media_player_entity_id: media_player.tts
    message: auto
    language: nl-NL
  target:
    entity_id: tts.home_assistant_cloud
````

### What version of Home Assistant Core are your running

2025.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
How soon after starting one announcement are you trying to send a second announcement? What happens if a single player is targeted? Per the troubleshooting docs you haven’t detailed what other player types you have tried, why not?  Did you just rename the the HA entity to media_player.tts?

**Comment by joopdo** [comment]
Thank you for your reply. Great suggestion on the single player, to test I have moved all 45 tts events from the player group to a single speaker just now. 

For the time in between, I would say about three seconds, but I have many TTS events, they can all differ. (It waits till the player device becomes idle before continuing)

I can give more information, this s a typical event for our house:
```
actions:
  - target:
      entity_id: media_player.tts
    data:
      media_type: track
      media_id: http://192.168.2.238/local/localmp3/goodmorning.mp3
      enqueue: replace
    action: music_assistant.play_media
  - wait_template: '{{ is_state(''media_player.tts'', ''idle'') }}'
    continue_on_timeout: true
    timeout: '60'
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.tts
      message: Good morning!
      language: nl-NL
    target:
      entity_id: tts.home_assistant_cloud
```
