### ISSUE TITLE
[Music Assistant] Volume redirection (and Mute status redirection?) not working properly on Wiim Pro devices (Airplay 2/Linkplay)

### ISSUE THREAD

**Issue by maxi1134** [music-assistant/support#4071]
### What version of Music Assistant has the issue?

2.6.0b11

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

First of all, thank you guys for this wonderful piece of software!
It is a pleasure to use, and the support is great!

I am encountering a new issue lately where the volume redirection from MA to a [linkplay ]( https://www.home-assistant.io/integrations/linkplay/)[Linkplay])speaker (namely 7 Wiim Pros in my case) where the sound is controlled but always reverts to 0 after a few seconds.

The speakers are linked through Airplay in `Music Assistant` and through Linkplay in `Home Assistant`

To better explain; 
If I set the volume speaker to `.45`(45%) on the `Linkplay Entity`. 
Both the `Link play Entity` and the `Music Assistant Entity` will be set to `.45`(45%).
But after a few seconds, the `Music Assistant Entity` volume will "change" to `0`(0%), but only server-side, meaning that the speaker still actively emits volume at the same level.
While the `Link play Entity` remains unchanged.

Here is also a video showing the issue:

https://github.com/user-attachments/assets/dba5b2e1-b408-4758-be17-e3daf8697050

And a picture of my MA settings for those entities:

![Image](https://github.com/user-attachments/assets/75bb9cf9-cd41-4e3c-9ea5-2642fa345bb5)

I am also unaware as to when this last worked, as it never did for me.

### How to reproduce

By trying to use a Wiim Pr(Linkplay integration) o as volume target for the volume rerouting from an Airplay 2 device.

### Music Providers

Problem presents when using Spotify, Filesystem Remote Share, Soundcloud or Tidal.

### Player Providers

Airplay 
( 7*Wiim Pros)

### Full log output

[home-assistant_music_assistant_2025-06-16T21-30-23.326Z.log](https://github.com/user-attachments/files/20764827/home-assistant_music_assistant_2025-06-16T21-30-23.326Z.log)

|<<<>>>|<<<>>>|<<<>>>|<<<>>>|<<<>>>|<<<>>>|

[home-assistant_linkplay_2025-06-16T21-31-52.324Z.log](https://github.com/user-attachments/files/20764838/home-assistant_linkplay_2025-06-16T21-31-52.324Z.log)

### Additional information

The playback is isually instigated through LLM script or Sergice calls

### What version of Home Assistant Core are your running

core-2025.6.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes

**Comment by OzGav** [comment]
Can you clarify why you are using link play entities for volume and mute?

**Comment by maxi1134** [comment]
> Can you clarify why you are using link play entities for volume and mute?

The Music assistant Airplay 2 entities for those devices don't support it natively.

But the linkplay HA entities do

**Comment by OzGav** [comment]
This will be closed soon due to no followup

**Comment by OzGav** [comment]
Any update here?

**Comment by OzGav** [comment]
Did you try the MA “fake” option which tries to simulate it?

**Comment by maxi1134** [comment]
> Did you try the MA “fake” option which tries to simulate it?

This seems to take the volume to 0.

I use both the 'volume_level' and the 'is_volume_muted' attributes for many automations.

Ideally, that standard attribute ('is_volume_muted') would be used instead of just lowering the volume to 0.

**Comment by maxi1134** [comment]
> So are you using the HA player provider or AirPlay player provider to this device? Also is this still a problem in the 2.7.0 beta?

Both; I currently control the volume thruogh the Linkplay entity itself with a Universal Media player since the volume redirection was not working.

Let me try without it and see if the issue is still present.

The code I currently use looks like this:

```
  - platform: universal
    name: Universal workshop Speakers
    unique_id: universal_workshop_speakers
    children:
      - media_player.mass_workshop_airplay_wiim_speaker
      - media_player.wiim_workshop_linkplay
      - media_player.group_mass_home_group_speakers
    active_child_template: >-
                  {% set mass_speaker = 'media_player.mass_workshop_airplay_wiim_speaker' %}
                  {% set linkplay_speaker = 'media_player.wiim_workshop_linkplay' %}
                  {% set mass_home_group = 'media_player.group_mass_home_group_speakers' %}
                  {% if states(linkplay_speaker) == 'idle' and states(mass_speaker) == 'idle' %}
                    {{ linkplay_speaker }}
                  {% else %}             
                    {{ mass_speaker }}
                  {% endif %}
    state_template: >-
                  {% set mass_speaker = 'media_player.mass_workshop_airplay_wiim_speaker' %}
                  {% set linkplay_speaker = 'media_player.wiim_workshop_linkplay' %}
                  {% set mass_home_group = 'media_player.group_mass_home_group_speakers' %}
                  {% if states(linkplay_speaker) == 'idle' and states(mass_speaker) == 'idle' %}
                  off
                  {% else %}             
                    {{ states(mass_speaker) }}
                  {% endif %}
    commands:
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: 
            - media_player.wiim_workshop_linkplay
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: 
            - media_player.wiim_workshop_linkplay
      volume_mute:
        service: media_player.volume_mute
        target:
          entity_id: 
            - media_player.wiim_workshop_linkplay
        data:
          is_volume_muted: "{{ is_volume_muted }}"
      volume_set:
        service: media_player.volume_set
        target:
          entity_id: 
            - media_player.wiim_workshop_linkplay
        data:
          volume_level: "{{ volume_level }}"
      turn_off:
        service: media_player.clear_playlist
        target:
          entity_id: 
            - media_player.mass_workshop_airplay_wiim_speaker
      turn_on:
        service: media_player.media_play
        target:
          entity_id: 
            - media_player.mass_workshop_airplay_wiim_speaker
    attributes:
      is_volume_muted: media_player.wiim_workshop_linkplay|is_volume_muted
      volume_level: media_player.wiim_workshop_linkplay|volume_level
```
