### ISSUE TITLE
Yamaha MusicCast can't play songs with non-ASCII characters in name

### ISSUE THREAD

**Issue by llego** [music-assistant/support#4083]
### What version of Music Assistant has the issue?

2.6.0b13

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [x] Yes

### The problem

It seems that it's not possible to play songs that have non-ASCII characters in the name, such as å, ä, and ö. I have tried this with Finnish albums containing songs with ASCII-only song names and songs with non-ASCII characters in their names. Songs that have non-ASCII characters fail to play, while songs with only ASCII characters successfully play. 

The same problem is present when trying to play a full album where either the album artist or album name have non-ASCII characters in the name.

I have tested this with Jellyfin and Tidal providers. This bug affects only Yamaha MusicCast player.

### How to reproduce

Play song on Yamaha MusicCast player with non-ASCII characters in the name.

### Music Providers

Jellyfin, Tidal

### Player Providers

Yamaha MusicCast.

I don't see this problem with Chromecast.

### Full log output

[mass log.txt](https://github.com/user-attachments/files/20969966/mass.log.txt)

### Additional information

Instigated play from UI.

I have MASS installed as a docker container:

```
  music-assistant-server:
    image: ghcr.io/music-assistant/server:beta
    container_name: music-assistant-server
    restart: unless-stopped
    volumes:
      - /mnt/illby/docker/data/homeassistant/music-assistant-server/data:/data/
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=debug
```

### What version of Home Assistant Core are your running

2025.6.3

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

### Have you included ALL of the information specified in the Troubleshooting FAQ or explained why you cannot

- [x] Yes
